build:
    go build -o bin/op-deployer cmd/op-deployer/main.go

download-artifacts checksum outfile:
    curl -o {{outfile}} -L https://storage.googleapis.com/oplabs-contract-artifacts/artifacts-v1-{{checksum}}.tar.gz

calculate-artifacts-hash checksum:
    just download-artifacts {{checksum}} /tmp/artifact.tgz
    sha256sum /tmp/artifact.tgz
    rm /tmp/artifact.tgz
