#!/bin/bash
export SEQUENCER_ADDRESS=0xabba
export SEQUENCER_WARNING_THRESHOLD=1000
export SEQUENCER_DANGER_THRESHOLD=100

export PROPOSER_ADDRESS=0xacdc
export PROPOSER_WARNING_THRESHOLD=2000
export PROPOSER_DANGER_THRESHOLD=200

yarn ts-mocha src/*.spec.ts
