package selector

import (
	"sort"
	"strings"

	"github.com/ethereum-optimism/optimism/ops/checks/catalog"
	"github.com/ethereum-optimism/optimism/ops/checks/graph"
)

// importScopeCandidates is the fallback for scopeable checks when no
// coverage edges point at the changed files. Reverse-BFS walks
// *incoming* import edges from the changed nodes to find everything
// that transitively imports them — the set of files whose compilation
// or behavior could break when the changed file changes.
//
// This catches cases coverage misses:
//   - Test helper changes (test/helpers/Foo.sol has no tested_by edge
//     pointing at it, so coverage finds nothing; but test files that
//     import it must re-run because their compilation can break).
//   - Source changes in modules where coverage hasn't been collected.
//
// Edge direction: the Solidity adapter writes `importer → imported`,
// so to find consumers of a changed node we walk `EdgesTo(cur)` and
// propagate from edge.From (the importer).
//
// Only consumers that are themselves test files, and that have a
// tested_by edge to this check, become scope candidates; the scope is
// the specific test file path (e.g. `./test/L1/X.t.sol`), not a
// directory glob.
//
// Producers discovered on the walk are attached to each Candidate's
// Prerequisites so the scheduler knows to run them before the consumer.
func importScopeCandidates(g *graph.Graph, ct *catalog.CheckType, changedIDs []string) []Candidate {
	checkNodeID := "check:" + ct.ID

	wr := walkForScope(g, changedIDs, 0.01)
	if len(wr.consumers) == 0 {
		return nil
	}

	type emit struct {
		nodeID string
		signal float64
	}
	var hits []emit
	for nodeID, signal := range wr.consumers {
		// isCandidateTestNode enforces language AND granularity
		// (test-file for Solidity; package for Go; crate for Rust) —
		// strictly tighter than the deleted hasTestedByEdge filter,
		// which only gated on a builder-emitted language match.
		if !isCandidateTestNode(nodeID, ct) {
			continue
		}
		hits = append(hits, emit{nodeID, signal})
	}
	_ = checkNodeID // retained for signature stability; language-matching is now via isCandidateTestNode
	if len(hits) == 0 {
		return nil
	}

	sort.Slice(hits, func(i, j int) bool { return hits[i].signal > hits[j].signal })

	producers := sortedKeys(wr.producers)
	// Don't list a candidate as its own prerequisite (a walker can
	// legitimately hit its own check via a tested_by edge; that's not
	// a dep).
	filteredProducers := make([]string, 0, len(producers))
	for _, p := range producers {
		if p != ct.ID {
			filteredProducers = append(filteredProducers, p)
		}
	}

	seen := make(map[string]bool)
	out := make([]Candidate, 0, len(hits))
	for _, h := range hits {
		scope := scopeForCandidate(h.nodeID, ct)
		if scope == "" || seen[scope] {
			continue
		}
		seen[scope] = true
		out = append(out, Candidate{
			CheckID: ct.ID,
			Scope:   scope,
			Signal:  h.signal,
			Provenance: []SignalContribution{{
				Source:       graph.SourceStatic,
				EdgeKind:     graph.EdgeImports,
				Contribution: h.signal,
				Raw: map[string]any{
					"via_node": h.nodeID,
					"reason":   "transitive_importer",
				},
			}},
			Prerequisites: filteredProducers,
		})
	}
	return out
}

// sortedKeys returns the map's keys in deterministic order.
func sortedKeys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// walkResult carries everything the reverse-BFS discovers: per-node
// signal (for later scope-candidate emission) and a set of check IDs
// encountered as producers of nodes the walk passed through (for
// Candidate.Prerequisites population).
type walkResult struct {
	consumers map[string]float64
	producers map[string]bool
}

// walkForScope performs reverse-BFS from each changed node, following
// incoming `imports` edges and outgoing `generates` edges. Whenever it
// visits a node that some check `produces`, the producer is collected
// so downstream consumers can declare it as a per-file prerequisite.
//
// Three edge kinds participate:
//   - imports (followed REVERSE): "Foo.sol imports Bar.sol" means
//     changing Bar should re-run anything that imports Bar. Walk from
//     Bar follows EdgesTo(Bar) where Kind=imports, landing on Foo.
//   - generates (followed FORWARD): "src/Foo.sol generates
//     interfaces/IFoo.sol" means changing Foo implicitly changes
//     IFoo (regenerated by tooling). Walk from src/Foo follows
//     EdgesFrom(src/Foo) where Kind=generates, landing on IFoo —
//     then the imports reverse-walk continues from IFoo into every
//     test that imports the interface.
//   - produces (passive, reverse-looked-up): if any node on the walk
//     has an incoming `produces` edge from a check node, that check
//     is recorded as a producer. The walk doesn't follow produces as
//     a traversal edge — it's metadata about the node.
func walkForScope(g *graph.Graph, changedIDs []string, minSignal float64) walkResult {
	best := make(map[string]float64)
	producers := make(map[string]bool)
	type item struct {
		id     string
		signal float64
	}
	queue := make([]item, 0, len(changedIDs))
	for _, id := range changedIDs {
		if g.GetNode(id) == nil {
			continue
		}
		best[id] = 1.0
		queue = append(queue, item{id, 1.0})
	}
	for len(queue) > 0 {
		cur := queue[0]
		queue = queue[1:]
		if cur.signal < best[cur.id] {
			continue
		}
		// Collect producers for this node (passive lookup; doesn't
		// extend the walk).
		for _, edge := range g.EdgesTo(cur.id) {
			if edge.Kind != graph.EdgeProduces {
				continue
			}
			if strings.HasPrefix(edge.From, "check:") {
				producers[strings.TrimPrefix(edge.From, "check:")] = true
			}
		}
		// Reverse walk on imports: find consumers of this node.
		for _, edge := range g.EdgesTo(cur.id) {
			if edge.Kind != graph.EdgeImports {
				continue
			}
			s := cur.signal * edge.Strength * edge.Confidence
			if s < minSignal {
				continue
			}
			importer := edge.From
			if existing, ok := best[importer]; !ok || s > existing {
				best[importer] = s
				queue = append(queue, item{importer, s})
			}
		}
	}
	return walkResult{consumers: best, producers: producers}
}

