// Code generated by tygo. DO NOT EDIT.

//////////
// source: deposits.go

export interface DepositItem {
  guid: string;
  from: string;
  to: string;
  timestamp: number /* uint64 */;
  L1TxHash: string;
  L2TxHash: string;
  Block: string;
  amount: string;
  l1Token: string;
  l2Token: string;
}
export interface DepositResponse {
  cursor: string;
  hasNextPage: boolean;
  items: DepositItem[];
}

//////////
// source: routes.go

export interface Routes {
  Logger: any /* log.Logger */;
  BridgeTransfersView: any /* database.BridgeTransfersView */;
  Router?: any /* chi.Mux */;
}

//////////
// source: withdrawals.go

export interface WithdrawalItem {
  guid: string;
  from: string;
  to: string;
  transactionHash: string;
  timestamp: number /* uint64 */;
  l2BlockHash: string;
  amount: string;
  proof: string;
  claim: string;
  l1Token: string;
  l2Token: string;
}
export interface WithdrawalResponse {
  cursor: string;
  hasNextPage: boolean;
  items: WithdrawalItem[];
}
