# All the files we depend on. We are using a negative pattern to not include anything by accident.
# node_modules, packages (contains git submodules and node modules etc.), devnet dirs etc. all add up a lot.
*

!/cannon
!/op-core
!/op-batcher
!/op-chain-ops
!/op-deployer
!/op-dripper
!/op-challenger
!/packages/contracts-bedrock/snapshots
!/op-dispute-mon
!/op-conductor
!/op-node
!/op-preimage
!/op-program
!/op-proposer
!/op-service
!/op-supervisor
!/op-supernode
!/op-interop-filter
!/op-test-sequencer
!/op-validator
!/op-wheel
!/op-alt-da
!/op-faucet
!/op-interop-mon
!/rust
# Exclude large rust build artifacts
rust/target
rust/.git
!/go.mod
!/go.sum
!/justfiles
!/mise.toml
!/op-e2e/e2eutils
!./ops/scripts/install_mise.sh

**/bin
**/testdata
**/tests

# Re-include rust/bin which is excluded by **/bin above
!/rust/**/bin
