[package]
name = "rollup-boost"
version = "0.7.13"
edition.workspace = true
description = "Rollup Boost is a sidecar for optimism rollups that enables rollup extensions"
rust-version.workspace = true
license.workspace = true
readme = "../../README.md"

[dependencies]
# Internal
rollup-boost-types.workspace = true

tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "json", "fmt", "std"] }
clap = { workspace = true, features = ["derive", "env"] }
futures.workspace = true
thiserror.workspace = true
serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true, features = ["std"] }
metrics.workspace = true
tokio = { workspace = true, features = ["full"] }
eyre.workspace = true
url.workspace = true
sha2.workspace = true
moka = { workspace = true, features = ["future"] }
ed25519-dalek.workspace = true
blake3.workspace = true
hex.workspace = true

op-alloy-rpc-types-engine = { workspace = true, features = ["serde"] }
alloy-rpc-types-engine = { workspace = true, features = ["serde", "jwt"] }
alloy-rpc-types-eth = { workspace = true, features = ["serde"] }
alloy-primitives = { workspace = true, features = ["rand", "serde"] }
alloy-serde.workspace = true
alloy-rlp.workspace = true

tokio-tungstenite = { workspace = true, features = ["native-tls"] }
metrics-derive.workspace = true

jsonrpsee = { workspace = true, features = ["server", "http-client", "macros"] }
http.workspace = true
dotenvy.workspace = true
tower = { workspace = true, features = ["timeout"] }
tower-http = { workspace = true, features = [
    "decompression-full",
    "sensitive-headers",
] }
http-body-util.workspace = true
hyper = { workspace = true, features = ["full"] }
hyper-util = { workspace = true, features = ["full"] }
hyper-rustls = { workspace = true, features = ["ring"] }
rustls = { workspace = true, features = ["ring"] }
opentelemetry = { workspace = true, features = ["trace"] }
opentelemetry-otlp = { workspace = true, features = [
    "http-proto",
    "http-json",
    "reqwest-client",
    "trace",
    "grpc-tonic",
] }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio"] }
tracing-opentelemetry.workspace = true
metrics-exporter-prometheus.workspace = true
metrics-util.workspace = true
paste.workspace = true
parking_lot.workspace = true
tokio-util.workspace = true
dashmap.workspace = true
backoff.workspace = true
uuid = { workspace = true, features = ["v7"] }
bytes.workspace = true
lru.workspace = true

[dev-dependencies]
tempfile.workspace = true
serial_test.workspace = true
rand.workspace = true
time.workspace = true
op-alloy-consensus.workspace = true
alloy-eips = { workspace = true, features = ["serde"] }
alloy-consensus = { workspace = true, features = ["serde"] }
anyhow.workspace = true
ctor.workspace = true
reqwest.workspace = true
testcontainers.workspace = true

[features]
integration = []

[build-dependencies]
vergen = { workspace = true, features = ["build", "cargo", "emit_and_set"] }
vergen-git2.workspace = true

[[bin]]
name = "rollup-boost"
path = "src/bin/main.rs"

[lib]
path = "src/lib.rs"
