"""Exercise real Git discovery, complete source inventories and failure receipts."""
import base64
import copy
import importlib.util
import json
import os
from pathlib import Path
import shutil
import signal
import subprocess
import sys
import tempfile
import threading
import time
import unittest
from unittest.mock import patch
from ci_test_fixtures import preserve_working_directory

SPEC=importlib.util.spec_from_file_location('nut_provenance',Path(__file__).resolve().parents[1] / 'runtime' / 'nut-provenance.py')
N=importlib.util.module_from_spec(SPEC);SPEC.loader.exec_module(N)


class _ProvenanceTestsFixtures:

    def git(self, root, *argv):
        return subprocess.check_output(['git', *argv], cwd=root).strip()

    def commit(self, root):
        self.git(root, 'add', '.')
        self.git(root, '-c', 'user.name=CI fixture', '-c', 'user.email=ci-fixture@example.invalid', 'commit', '-qm', 'Actual provenance fixture')
        return self.git(root, 'rev-parse', 'HEAD').decode()

    def setUp(self):
        temp = tempfile.TemporaryDirectory()
        self.addCleanup(temp.cleanup)
        self.temp = Path(temp.name)
        self.root = self.temp / 'source'
        self.root.mkdir()
        self.git(self.root, 'init', '-q')
        self.nested = self.temp / 'nested'
        self.nested.mkdir()
        self.git(self.nested, 'init', '-q')
        (self.nested / 'Nested.sol').write_text('contract Nested {}\n')
        self.nested_sha = self.commit(self.nested)
        self.library = self.temp / 'library'
        self.library.mkdir()
        self.git(self.library, 'init', '-q')
        (self.library / 'Library.sol').write_text('contract Library {}\n')
        self.git(self.library, '-c', 'protocol.file.allow=always', 'submodule', 'add', '-q', str(self.nested), 'lib/nested')
        self.library_sha = self.commit(self.library)
        inputs = {'mise.toml': '[tools]\nforge = "1.2.3"\njust = "1.46.0"\n', 'packages/contracts-bedrock/justfile': 'generate-nut-bundle:\n  forge script original-generator\n', 'packages/contracts-bedrock/foundry.toml': '[profile.default]\nsrc = "src"\n', '.gitignore': '.ci/\n'}
        for name, data in inputs.items():
            path = self.root / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(data)
        for name in ('main-checks.py', 'pr-checks.py', 'rust-workspace-report.py', 'ci-report.py'):
            path = self.root / 'ops/ci/runtime' / name
            path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(N.ROOT / 'ops/ci/runtime' / name, path)
        self.git(self.root, 'add', '.')
        self.git(self.root, '-c', 'protocol.file.allow=always', 'submodule', 'add', '-q', str(self.library), 'packages/contracts-bedrock/lib/fixture')
        self.git(self.root, '-c', 'protocol.file.allow=always', 'submodule', 'add', '-q', str(self.library), 'rollup-boost')
        self.git(self.root, '-c', 'user.name=CI fixture', '-c', 'user.email=ci-fixture@example.invalid', 'commit', '-qm', 'Historical generator source')
        self.recorded = self.git(self.root, 'rev-parse', 'HEAD').decode()
        self.index = subprocess.check_output(['git', 'ls-files', '--stage', '-z'], cwd=self.root)
        self.bundle = b'{"fixture":"actual regenerated bytes"}\n'
        path = self.root / 'op-core/nuts/bundles/karst_nut_bundle.json'
        path.parent.mkdir(parents=True)
        path.write_bytes(self.bundle)
        self.entry = {'bundle': str(path.relative_to(self.root)), 'hash': 'sha256:' + N.S.digest(path), 'commit': self.recorded}
        self.write_locks({'karst': self.entry})
        self.git(self.root, 'add', 'op-core')
        self.git(self.root, '-c', 'user.name=CI fixture', '-c', 'user.email=ci-fixture@example.invalid', 'commit', '-qm', 'Current locked bundle')
        self.sha = self.git(self.root, 'rev-parse', 'HEAD').decode()
        self.git(self.root, 'update-ref', 'refs/remotes/origin/develop', self.sha)
        self.git(self.root, '-c', 'protocol.file.allow=always', 'submodule', 'update', '--init', '--recursive', '--', 'packages/contracts-bedrock/lib/fixture')
        self.git(self.root, 'submodule', 'deinit', '-f', '--', 'rollup-boost')
        for module in (N, N.M):
            handle = patch.object(module, 'ROOT', self.root)
            handle.start()
            self.addCleanup(handle.stop)
        self.env = {'CI_COMMIT_SHA': self.sha, 'CI_BRANCH': 'codex/rwx-ci-pilot', 'CI': 'true', 'RWX_RUN_ID': 'a' * 32, 'RWX_TASK_ATTEMPT_NUMBER': '1', 'GOFLAGS': ''}

    def write_locks(self, entries):
        (self.root / N.LOCK).write_text(''.join(('[' + fork + ']\n' + ''.join((k + ' = ' + json.dumps(v) + '\n' for k, v in entry.items())) for fork, entry in entries.items())))

    def report(self, directory, provider):
        directory.mkdir(parents=True)
        selection, current, base, error, historical = N.discover(self.root, True)
        N.S.write(directory / 'selection.json', selection)
        N.S.write(directory / 'settings.json', {'source_sha': self.sha, 'branch': 'codex/rwx-ci-pilot', 'input_sha256': N.M.inputs(), 'environment': {}, 'go_version': 'fixture Go', 'prepare_only': False, 'provider': provider})
        for name, data in [('fork_lock.toml', current), ('base-fork-lock.toml', base), ('base-discovery.stderr', error)]:
            (directory / name).write_bytes(data)
        fork = directory / 'forks/karst'
        raw = fork / 'originals'
        raw.mkdir(parents=True)
        entry = selection['entries']['karst']
        N.S.write(fork / 'generation.stage.json', {'exit_code': 0, 'argv': N.prefix(entry['historical_tools']) + ['go', 'run', './ops/scripts/nut-provenance-verify', 'karst']})
        (fork / 'generation.log').write_text('Compiling 1 files with Solc 0.8.15\nPASS: bundle hash matches lock\nPASS: regenerated bundle matches committed bundle\n')
        N.S.write(raw / 'source.json', {'fork': 'karst', 'entry': {k.title(): self.entry[k] for k in self.entry}, 'generator_argv': ['just', 'generate-nut-bundle']})
        for name, path in [('mise.toml', 'mise.toml'), ('contracts.justfile', 'packages/contracts-bedrock/justfile'), ('foundry.toml', 'packages/contracts-bedrock/foundry.toml')]:
            (raw / name).write_bytes((self.root / path).read_bytes())
        for name in ('locked-bundle.json', 'regenerated-bundle.json'):
            (raw / name).write_bytes(self.bundle)
        (raw / 'tracked-stage.bin').write_bytes(self.index)
        (raw / 'worktree-status.txt').write_bytes(b'')
        module = 'packages/contracts-bedrock/lib/fixture'
        nested = module + '/lib/nested'
        (raw / 'submodules.txt').write_text(' ' + self.library_sha + ' ' + module + '\n ' + self.nested_sha + ' ' + nested + '\n-' + self.library_sha + ' rollup-boost\n')
        N.S.write(raw / 'submodule-inventories.json', {name: {'head': sha, 'tracked_stage': base64.b64encode(subprocess.check_output(['git', 'ls-files', '--stage', '-z'], cwd=root)).decode(), 'status': ''} for name, root, sha in [(module, self.library, self.library_sha), (nested, self.nested, self.nested_sha)]})
        N.S.write(fork / 'tools.json', {name: {'version': version, 'binary_sha256': 'b' * 64, 'binary_path': '/' + provider + '/' + name} for name, version in [('forge', 'forge Version: 1.2.3-v1.2.3'), ('just', 'just 1.46.0'), ('go', 'fixture Go')]})
        N.S.write(fork / 'compilers.json', {'0.8.15': {'version': 'Version: 0.8.15+fixture', 'binary_sha256': 'd' * 64, 'binary_path': '/' + provider + '/solc'}})
        self.reseal(directory)
        return directory

    def reseal(self, directory):
        hashes = {k: v for k, v in N.seal(directory).items() if k != 'final.json'}
        N.S.write(directory / 'final.json', {'exit_code': 0, 'report_errors': [], 'tests': 0, 'original_sha256': hashes})

    def executor(self, argv, provider='circleci', **kwargs):
        selection = N.discover(self.root, True)
        selection[0]['go_argv'] = argv
        command = N.command

        def call(*args, **params):
            return 'fixture Go' if args == ('go', 'version') else command(*args, **params)
        stage = N.S.stage

        def run(directory, name, args, **params):
            return 0 if name in ('tool-prepare', 'compiler-prepare') else stage(directory, name, args, **params)
        with preserve_working_directory(), patch.dict(os.environ, self.env), patch.object(N, 'command', side_effect=call), patch.object(N, 'discover', return_value=selection), patch.object(N, 'prefix', return_value=[]), patch.object(N, 'tool_identity', return_value={}), patch.object(N, 'compiler_identity', return_value=None), patch.object(N.S, 'stage', side_effect=run):
            result = N.execute(provider, True, **kwargs)
        directory = self.root / '.ci/nut-provenance' / ('toolchain' if kwargs.get('prepare') else 'run')
        return (result, directory, N.G.read(directory / 'final.json'))


class ProvenanceTests(_ProvenanceTestsFixtures, unittest.TestCase):

    def test_discovery_preserves_changed_policy_and_selects_every_full_fork(self):
        self.assertEqual(N.discover(self.root, False)[0]['selected_forks'], [])
        selection = N.discover(self.root, True)[0]
        self.assertEqual(selection['selected_forks'], ['karst'])
        self.assertEqual(selection['excluded'], [])
        self.assertEqual(selection['entries']['karst']['historical_tools'], {'forge': '1.2.3', 'just': '1.46.0'})
        path = self.root / 'op-core/nuts/bundles/jovian_nut_bundle.json'
        path.write_bytes(self.bundle)
        self.write_locks({'karst': self.entry, 'jovian': self.entry | {'bundle': str(path.relative_to(self.root))}})
        self.assertEqual(N.discover(self.root, False)[0]['selected_forks'], ['jovian'])
        self.assertEqual(N.discover(self.root, True)[0]['selected_forks'], ['jovian', 'karst'])
        self.git(self.root, 'update-ref', '-d', 'refs/remotes/origin/develop')
        fallback = N.discover(self.root, False)[0]
        self.assertFalse(fallback['base_lock_available'])
        self.assertEqual(fallback['selected_forks'], ['jovian', 'karst'])

    def test_discovery_rejects_empty_missing_corrupt_and_unpinned_sources(self):
        for change in ('empty', 'missing-bundle', 'bad-hash', 'bad-commit', 'unsafe', 'duplicate-bundle', 'extra-setting'):
            entry = copy.deepcopy(self.entry)
            if change == 'missing-bundle':
                entry['bundle'] = 'op-core/nuts/bundles/missing.json'
            elif change == 'bad-hash':
                entry['hash'] = 'sha256:' + '0' * 64
            elif change == 'bad-commit':
                entry['commit'] = '0' * 40
            elif change == 'unsafe':
                entry['bundle'] = 'op-core/nuts/bundles/../../foreign.json'
            elif change == 'extra-setting':
                entry['override'] = 'not-authoritative'
            entries = {} if change == 'empty' else {'karst': entry}
            if change == 'duplicate-bundle':
                entries['jovian'] = dict(entry)
            self.write_locks(entries)
            with self.subTest(change=change), self.assertRaises((ValueError, FileNotFoundError, subprocess.CalledProcessError)):
                N.discover(self.root, True)

    def test_resealed_missing_changed_uninitialized_and_extra_contract_gitlinks_fail(self):
        report = self.report(self.temp / 'native', 'rwx')
        directory = report / 'forks/karst'
        raw = directory / 'originals'
        text = (raw / 'submodules.txt').read_text()
        for changed in (text.replace(' ' + self.library_sha, '+' + self.library_sha, 1), text.replace(' ' + self.library_sha, '-' + self.library_sha, 1), text.replace(self.nested_sha, 'c' * 40), text + ' ' + self.library_sha + ' foreign/module\n', text.splitlines()[0] + '\n', text + text):
            (raw / 'submodules.txt').write_text(changed)
            self.reseal(report)
            with self.subTest(changed=changed), self.assertRaises(ValueError):
                N.validate_fork(directory, N.G.read(report / 'selection.json')['entries']['karst'], 'karst')

    def test_corruption_extra_unsealed_files_duplicate_json_and_failed_receipts_fail(self):
        report = self.report(self.temp / 'native', 'rwx')
        path = report / 'selection.json'
        original = path.read_bytes()
        path.write_bytes(original + b' ')
        with self.assertRaisesRegex(ValueError, 'corrupt'):
            N.originals(report)
        path.write_bytes(original)
        (report / 'extra').write_text('extra')
        with self.assertRaisesRegex(ValueError, 'unsealed'):
            N.originals(report)
        (report / 'extra').unlink()
        N.S.write(report / 'final.json', {'exit_code': 1, 'report_errors': [], 'tests': 0, 'original_sha256': {}})
        with self.assertRaises(ValueError):
            N.originals(report)
        path.write_text('{"entries":{},"entries":{}}')
        with self.assertRaises(ValueError):
            N.G.read(path)

    def test_native_preparation_retry_retains_attempt_and_runtime_dependencies_still_required(self):
        self.env['RWX_TASK_ATTEMPT_NUMBER'] = '2'
        result, directory, final = self.executor([], provider='rwx', prepare=True)
        self.assertEqual(result, 0)
        self.assertEqual(final['exit_code'], 0)
        self.assertEqual(N.G.read(directory / 'settings.json')['rwx_task_attempt'], '2')
        self.assertEqual(N.G.read(directory / 'selection.json')['selected_forks'], ['karst'])
        self.assertEqual(N.originals(directory)['tests'], 0)
        for attempt in ('', '0', '01', '-1', 'unbound'):
            self.env['RWX_TASK_ATTEMPT_NUMBER'] = attempt
            result, directory, final = self.executor([], provider='rwx', prepare=True)
            self.assertEqual(result, 1)
            self.assertIn('invalid task attempt', final['report_errors'][0])
        self.env['RWX_TASK_ATTEMPT_NUMBER'] = '3'
        result, directory, final = self.executor([], provider='rwx')
        self.assertEqual(result, 1)
        self.assertIn('requires verified modules and historical tools', final['report_errors'][0])

    def test_actual_successful_process_with_invalid_reports_returns_failure(self):
        result, directory, final = self.executor([sys.executable, '-c', "print('actual successful fixture subprocess')"])
        self.assertEqual(result, 1)
        self.assertEqual(final['exit_code'], 1)
        self.assertTrue(final['report_errors'])
        self.assertEqual(N.G.read(directory / 'forks/karst/generation.stage.json')['exit_code'], 0)
        self.assertTrue(final['original_sha256'])

    def test_actual_tool_stdout_stays_distinct_from_original_stderr_diagnostics(self):
        directory = self.temp / 'streams'
        directory.mkdir()
        argv = [sys.executable, '-c', "import sys;print('go version fixture');print('mise WARN missing unrelated tool',file=sys.stderr)"]
        self.assertEqual(N.S.stage(directory, 'identity', argv, cwd=str(directory), stdout_file='version.txt'), 0)
        self.assertEqual((directory / 'version.txt').read_text(), 'go version fixture\n')
        self.assertEqual((directory / 'identity.log').read_text(), 'mise WARN missing unrelated tool\n')
        stage = N.G.read(directory / 'identity.stage.json')
        self.assertEqual(stage['stdout_sha256'], N.S.digest(directory / 'version.txt'))
        self.assertEqual(stage['log_sha256'], N.S.digest(directory / 'identity.log'))
        with self.assertRaises(ValueError):
            N.S.stage(directory, 'unsafe', argv, stdout_file='../outside')

    def test_actual_failure_and_cancellation_retain_original_status_and_partial_logs(self):
        result, directory, final = self.executor([sys.executable, '-c', "print('intentional original failure');raise SystemExit(17)"])
        self.assertEqual(result, 17)
        self.assertEqual(final['exit_code'], 17)
        marker = self.temp / 'ready'

        def cancel():
            deadline = time.monotonic() + 10
            while not marker.exists() and time.monotonic() < deadline:
                time.sleep(0.02)
            os.kill(os.getpid(), signal.SIGTERM)
        thread = threading.Thread(target=cancel)
        thread.start()
        result, directory, final = self.executor([sys.executable, '-c', 'import pathlib,time;print("original partial output",flush=True);pathlib.Path(' + repr(str(marker)) + ").write_text('ready');time.sleep(30)"])
        thread.join()
        self.assertEqual(result, 143)
        self.assertEqual(final['exit_code'], 143)
        self.assertEqual(N.G.read(directory / 'forks/karst/generation.stage.json')['exit_code'], -signal.SIGTERM)
        self.assertIn('original partial output', (directory / 'forks/karst/generation.log').read_text())
        self.assertTrue(final['original_sha256'])


if __name__=='__main__':unittest.main()
