queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - and:
        - "#review-threads-unresolved=0"
        - "#approved-reviews-by>=1"
        - "#changes-requested-reviews-by=0"
        - "label!=do-not-merge"
        - "label!=multiple-reviewers"
        - "label!=mergify-ignore"
        - "label!=M-do-not-merge"
        - "label!=M-multiple-reviewers"
        - "label!=M-mergify-ignore"
        - "base=develop"
    actions:
      queue:
        name: default
        method: merge
        merge_bot_account: OptimismBot
  - name: Add merge train label
    conditions:
      - "queue-position >= 0"
    actions:
      comment:
          message: |
            This PR has been added to the merge queue, and will be merged soon.
      label:
        add:
          - S-on-merge-train
  - name: Remove merge train label
    conditions:
      - "queue-position = -1"
    actions:
      label:
        remove:
          - S-on-merge-train
  - name: Ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: Hey @{{author}}! This PR has merge conflicts. Please fix them before continuing review.
      label:
        add:
          - S-conflict
  - name: Remove conflicts label when conflicts gone
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - S-conflict
  - name: Notify author when added to merge queue
    conditions:
      - "check-pending=Queue: Embarked in merge train"
    actions:
      comment:
        message: |
          This PR is next in line to be merged, and will be merged as soon as checks pass.
  - name: Notify author on queue failure
    conditions:
      - 'check-failure=Queue: Embarked in merge train'
    actions:
      comment:
        message: >
          Hey @{{ author }}, this pull request failed to merge and has been
          dequeued from the merge train.  If you believe your PR failed in
          the merge train because of a flaky test, requeue it by commenting
          with `@mergifyio requeue`.

          More details can be found on the `Queue: Embarked in merge train`
          check-run.
  - name: Add A-indexer label and ecopod reviewers
    conditions:
      - 'files~=^indexer/'
    actions:
      label:
        add:
          - A-indexer
      request_reviews:
        users:
          - roninjin10
  - name: Add A-pkg-sdk label and ecopod reviewers
    conditions:
      - 'files~=^packages/sdk/'
    actions:
      label:
        add:
          - A-pkg-sdk
      request_reviews:
        users:
          - roninjin10
  - name: Add A-pkg-common-ts label and ecopod reviewers
    conditions:
      - 'files~=^packages/common-ts/'
    actions:
      label:
        add:
          - A-pkg-common-ts
      request_reviews:
        users:
          - roninjin10
  - name: Add A-op-node label
    conditions:
      - 'files~=^op-node/'
    actions:
      label:
        add:
          - A-op-node
  - name: Add A-op-batcher label
    conditions:
      - 'files~=^op-batcher/'
    actions:
      label:
        add:
          - A-op-batcher
  - name: Add A-cannon label
    conditions:
      - 'files~=^cannon/'
    actions:
      label:
        add:
          - A-cannon
  - name: Add A-op-program label
    conditions:
      - 'files~=^op-program/'
    actions:
      label:
        add:
          - A-op-program
  - name: Add A-op-challenger label
    conditions:
      - 'files~=^op-challenger/'
    actions:
      label:
        add:
          - A-op-challenger
  - name: Add A-pkg-contracts-bedrock label
    conditions:
      - 'files~=^packages/contracts-bedrock/'
    actions:
      label:
        add:
          - A-pkg-contracts-bedrock
  - name: Add M-docs label
    conditions:
      - 'files~=^technical-documents/'
      - 'files~=^specs/'
    actions:
      label:
        add:
          - A-pkg-contracts-bedrock
  - name: Add M-deletion label when files are removed
    conditions:
      - 'removed-files~=^/'
    actions:
      label:
        add:
          - M-deletion
  - name: Add M-ci label when ci files are modified
    conditions:
      - 'files~=^.github/'
      - 'files~=^.circleci/'
      - 'files~=^.husky/'
    actions:
      label:
        add:
          - M-ci
