//! Shared NUT bundle parsing and codegen.
//!
//! Included by `build.rs` at build-script compile time and by
//! `tests/build_codegen.rs` at integration-test compile time. That dual role
//! is the reason these helpers live at the crate root instead of under `src/`.

// This module is included via `#[path = ...]` from two different compilation
// units. Each unit uses a subset of the public items; suppress the
// per-compilation-unit dead-code warnings rather than gating every item.
#![allow(dead_code, unreachable_pub)]

use anyhow::{Context, Result, anyhow};
use serde::Deserialize;

/// Supported NUT bundle schema version.
pub const SUPPORTED_VERSION: &str = "1.0.0";

#[derive(Deserialize)]
pub struct BundleMetadata {
    pub version: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BundleTransaction {
    pub intent: String,
    pub from: String,
    pub to: Option<String>,
    pub data: String,
    pub gas_limit: u64,
}

#[derive(Deserialize)]
pub struct BundleFile {
    pub metadata: BundleMetadata,
    pub transactions: Vec<BundleTransaction>,
}

/// Parse a NUT bundle from JSON, validating its schema version.
pub fn parse_bundle(json: &str) -> Result<BundleFile> {
    let bundle: BundleFile = serde_json::from_str(json).context("parse NUT bundle JSON")?;
    if bundle.metadata.version != SUPPORTED_VERSION {
        return Err(anyhow!(
            "unsupported NUT bundle version: got {:?}, want {:?}",
            bundle.metadata.version,
            SUPPORTED_VERSION
        ));
    }
    Ok(bundle)
}

/// Capitalize the first character of `name` — `"karst"` becomes `"Karst"`.
///
/// The NUT bundle's `fork_name` feeds into the source-hash derivation and must
/// match the capitalized form used by op-node.
pub fn capitalize(name: &str) -> String {
    let mut c = name.chars();
    c.next().map_or_else(String::new, |first| first.to_uppercase().collect::<String>() + c.as_str())
}

/// Generate the Rust source for a `fn {name}_nut_bundle() -> &'static NutBundle` constructor.
///
/// The generated function wraps the bundle construction in a function-scoped
/// `once_cell::race::OnceBox` so the bundle is allocated at most once per
/// process, with subsequent calls returning a reference to the cached value.
/// `OnceBox` is lock-free (AtomicPtr-based) and works on `no_std` targets
/// without requiring a `critical-section` implementation — critical for the
/// cannon/asterisc fault-proof VM targets.
///
/// `fork_display` is the capitalized form of `name` (see [`capitalize`]).
pub fn format_bundle(name: &str, fork_display: &str, bundle: &BundleFile) -> String {
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit.\n\n");
    code.push_str(&format!(
        "pub(crate) fn {name}_nut_bundle() -> &'static op_alloy_consensus::NutBundle {{\n"
    ));
    code.push_str(
        "    static BUNDLE: once_cell::race::OnceBox<op_alloy_consensus::NutBundle>\n        = once_cell::race::OnceBox::new();\n",
    );
    code.push_str(&format!(
        "    BUNDLE.get_or_init(|| alloc::boxed::Box::new(op_alloy_consensus::NutBundle {{\n        fork_name: alloc::string::String::from({fork_display:?}),\n        transactions: alloc::vec![\n"
    ));

    for tx in &bundle.transactions {
        let to_expr = tx.to.as_ref().map_or_else(
            || "None".to_string(),
            |addr| {
                format!(
                    "Some(alloy_primitives::address!({:?}))",
                    addr.strip_prefix("0x").unwrap_or(addr)
                )
            },
        );
        let data_hex = tx.data.strip_prefix("0x").unwrap_or(&tx.data);
        let from_hex = tx.from.strip_prefix("0x").unwrap_or(&tx.from);

        code.push_str("            op_alloy_consensus::NetworkUpgradeTransaction {\n");
        code.push_str(&format!(
            "                intent: alloc::string::String::from({:?}),\n",
            tx.intent
        ));
        code.push_str(&format!(
            "                from: alloy_primitives::address!({from_hex:?}),\n"
        ));
        code.push_str(&format!("                to: {to_expr},\n"));
        code.push_str(&format!(
            "                data: alloy_primitives::Bytes::from_static(&alloy_primitives::hex!({data_hex:?})),\n"
        ));
        code.push_str(&format!("                gas_limit: {},\n", tx.gas_limit));
        code.push_str("            },\n");
    }

    code.push_str("        ],\n    }))\n}\n");
    code
}
