//! Build script for `kona-hardforks`.
//!
//! Reads NUT bundle JSON files from `op-core/nuts/bundles/` and generates Rust source
//! that constructs [`NutBundle`] values at runtime without serde.

use std::{env, fs, path::PathBuf};

use serde::Deserialize;

/// JSON schema for NUT bundle metadata.
#[derive(Deserialize)]
struct BundleMetadata {
    version: String,
}

/// JSON schema for a single network upgrade transaction.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct BundleTransaction {
    intent: String,
    from: String,
    to: Option<String>,
    data: String,
    gas_limit: u64,
}

/// JSON schema for a NUT bundle file.
#[derive(Deserialize)]
struct BundleFile {
    metadata: BundleMetadata,
    transactions: Vec<BundleTransaction>,
}

/// Generate Rust code for a NUT bundle that constructs a [`NutBundle`] at runtime.
///
/// The generated file defines a function `fn karst_nut_bundle() -> NutBundle` that
/// builds the bundle from inline constants. This runs in `no_std` without serde.
fn generate_bundle(name: &str, json_path: &PathBuf, out_dir: &str) {
    let json = fs::read_to_string(json_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", json_path.display()));

    let bundle: BundleFile =
        serde_json::from_str(&json).unwrap_or_else(|e| panic!("failed to parse NUT bundle: {e}"));

    assert_eq!(
        bundle.metadata.version, "1.0.0",
        "unsupported NUT bundle version: {}",
        bundle.metadata.version
    );

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit.\n\n");
    code.push_str(&format!(
        "pub(crate) fn {name}_nut_bundle() -> op_alloy_consensus::NutBundle {{\n"
    ));
    code.push_str(&format!(
        "    op_alloy_consensus::NutBundle {{\n        fork_name: alloc::string::String::from({name:?}),\n        transactions: alloc::vec![\n"
    ));

    // Capitalize the fork name for the bundle constructor.
    let fork_display = {
        let mut c = name.chars();
        c.next().map_or_else(String::new, |first| {
            let upper: String = first.to_uppercase().collect();
            upper + c.as_str()
        })
    };

    // Override fork_name with properly capitalized version.
    code.clear();
    code.push_str("// Auto-generated by build.rs — do not edit.\n\n");
    code.push_str(&format!(
        "pub(crate) fn {name}_nut_bundle() -> op_alloy_consensus::NutBundle {{\n"
    ));
    code.push_str(&format!(
        "    op_alloy_consensus::NutBundle {{\n        fork_name: alloc::string::String::from({fork_display:?}),\n        transactions: alloc::vec![\n"
    ));

    for tx in &bundle.transactions {
        let to_expr = tx.to.as_ref().map_or_else(
            || "None".to_string(),
            |addr| {
                format!(
                    "Some(alloy_primitives::address!({:?}))",
                    addr.strip_prefix("0x").unwrap_or(addr)
                )
            },
        );

        let data_hex = tx.data.strip_prefix("0x").unwrap_or(&tx.data);

        code.push_str("            op_alloy_consensus::NetworkUpgradeTransaction {\n");
        code.push_str(&format!("                intent: alloc::string::String::from({:?}),\n", tx.intent));
        code.push_str(&format!(
            "                from: alloy_primitives::address!({:?}),\n",
            tx.from.strip_prefix("0x").unwrap_or(&tx.from)
        ));
        code.push_str(&format!("                to: {to_expr},\n"));
        code.push_str(&format!(
            "                data: alloy_primitives::Bytes::from_static(&alloy_primitives::hex!({data_hex:?})),\n"
        ));
        code.push_str(&format!("                gas_limit: {},\n", tx.gas_limit));
        code.push_str("            },\n");
    }

    code.push_str("        ],\n    }\n}\n");

    let out_path = PathBuf::from(out_dir).join(format!("{name}_nut_bundle.rs"));
    fs::write(&out_path, code)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_path.display()));
}

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");

    // The bundle JSON lives in op-core/nuts/bundles/ at the monorepo root.
    // From this crate's directory: ../../../../op-core/nuts/bundles/
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));
    let monorepo_root = manifest_dir
        .ancestors()
        .find(|p| p.join("op-core").is_dir())
        .expect("could not find monorepo root (looking for op-core/ directory)")
        .to_path_buf();

    let karst_bundle = monorepo_root.join("op-core/nuts/bundles/karst_nut_bundle.json");

    // Re-run if the bundle file changes.
    println!("cargo::rerun-if-changed={}", karst_bundle.display());

    generate_bundle("karst", &karst_bundle, &out_dir);
}
