//! Build script for `kona-hardforks`.
//!
//! Reads NUT bundle JSON files from `bundles/` inside this crate and generates Rust source
//! that constructs [`NutBundle`] values at runtime without serde.
//!
//! The canonical bundle lives at `op-core/nuts/bundles/<fork>_nut_bundle.json`. A byte-identical
//! copy is kept in this crate's `bundles/` directory so the Docker build (which scopes its
//! context to `rust/`) can find it. Both copies are written together by
//! `ops/scripts/nut-snapshot-for` and verified in CI by `ops/scripts/check-nut-locks`.

use std::{env, fs, path::PathBuf};

use serde::Deserialize;

/// JSON schema for NUT bundle metadata.
#[derive(Deserialize)]
struct BundleMetadata {
    version: String,
}

/// JSON schema for a single network upgrade transaction.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct BundleTransaction {
    intent: String,
    from: String,
    to: Option<String>,
    data: String,
    gas_limit: u64,
}

/// JSON schema for a NUT bundle file.
#[derive(Deserialize)]
struct BundleFile {
    metadata: BundleMetadata,
    transactions: Vec<BundleTransaction>,
}

/// Generate Rust code for a NUT bundle that constructs a [`NutBundle`] at runtime.
///
/// The generated file defines a function `fn karst_nut_bundle() -> NutBundle` that
/// builds the bundle from inline constants. This runs in `no_std` without serde.
fn generate_bundle(name: &str, json_path: &PathBuf, out_dir: &str) {
    let json = fs::read_to_string(json_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", json_path.display()));

    let bundle: BundleFile =
        serde_json::from_str(&json).unwrap_or_else(|e| panic!("failed to parse NUT bundle: {e}"));

    assert_eq!(
        bundle.metadata.version, "1.0.0",
        "unsupported NUT bundle version: {}",
        bundle.metadata.version
    );

    // The NutBundle's fork_name must match the capitalized form used by op-node
    // (e.g. "Karst"), since it feeds into the source-hash derivation.
    let fork_display = {
        let mut c = name.chars();
        c.next().map_or_else(String::new, |first| {
            let upper: String = first.to_uppercase().collect();
            upper + c.as_str()
        })
    };

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit.\n\n");
    code.push_str(&format!(
        "pub(crate) fn {name}_nut_bundle() -> op_alloy_consensus::NutBundle {{\n"
    ));
    code.push_str(&format!(
        "    op_alloy_consensus::NutBundle {{\n        fork_name: alloc::string::String::from({fork_display:?}),\n        transactions: alloc::vec![\n"
    ));

    for tx in &bundle.transactions {
        let to_expr = tx.to.as_ref().map_or_else(
            || "None".to_string(),
            |addr| {
                format!(
                    "Some(alloy_primitives::address!({:?}))",
                    addr.strip_prefix("0x").unwrap_or(addr)
                )
            },
        );

        let data_hex = tx.data.strip_prefix("0x").unwrap_or(&tx.data);

        code.push_str("            op_alloy_consensus::NetworkUpgradeTransaction {\n");
        code.push_str(&format!("                intent: alloc::string::String::from({:?}),\n", tx.intent));
        code.push_str(&format!(
            "                from: alloy_primitives::address!({:?}),\n",
            tx.from.strip_prefix("0x").unwrap_or(&tx.from)
        ));
        code.push_str(&format!("                to: {to_expr},\n"));
        code.push_str(&format!(
            "                data: alloy_primitives::Bytes::from_static(&alloy_primitives::hex!({data_hex:?})),\n"
        ));
        code.push_str(&format!("                gas_limit: {},\n", tx.gas_limit));
        code.push_str("            },\n");
    }

    code.push_str("        ],\n    }\n}\n");

    let out_path = PathBuf::from(out_dir).join(format!("{name}_nut_bundle.rs"));
    fs::write(&out_path, code)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_path.display()));
}

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");

    // Bundle JSONs are copied into this crate's bundles/ directory by
    // `ops/scripts/nut-snapshot-for` so they are reachable inside the Docker build
    // context (which is scoped to `rust/`). `ops/scripts/check-nut-locks` verifies
    // the copy is byte-identical to op-core/nuts/bundles/<fork>_nut_bundle.json.
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));
    let karst_bundle = manifest_dir.join("bundles/karst_nut_bundle.json");

    // Re-run if the bundle file changes.
    println!("cargo::rerun-if-changed={}", karst_bundle.display());

    generate_bundle("karst", &karst_bundle, &out_dir);
}
