{
 "title": "Kona Node",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "query_result(kona_node_info)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kona_node_info{instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Build Timestamp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kona_node_info{instance=~\"$instance\"}",
     "legendFormat": "{{build_timestamp}}"
    }
   ]
  },
  {
   "title": "Git SHA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kona_node_info{instance=~\"$instance\"}",
     "legendFormat": "{{git_sha}}"
    }
   ]
  },
  {
   "title": "Build Profile",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kona_node_info{instance=~\"$instance\"}",
     "legendFormat": "{{build_profile}}"
    }
   ]
  },
  {
   "title": "Target Triple",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kona_node_info{instance=~\"$instance\"}",
     "legendFormat": "{{target_triple}}"
    }
   ]
  },
  {
   "title": "Cargo Features",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kona_node_info{instance=~\"$instance\"}",
     "legendFormat": "{{cargo_features}}"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kona_node_swarm_peer_count{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Tags",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kona_node_block_labels{instance=~\"$instance\", label=~\"unsafe\"}",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "kona_node_block_labels{instance=~\"$instance\", label=~\"cross-unsafe\"}",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "kona_node_block_labels{instance=~\"$instance\", label=~\"local-safe\"}",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "kona_node_block_labels{instance=~\"$instance\", label=~\"safe\"}",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "kona_node_block_labels{instance=~\"$instance\", label=~\"finalized\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "kona_node_block_labels{instance=~\"$instance\"}",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "kona_node_derivation_l1_origin{instance=~\"$instance\"}",
     "legendFormat": "derivation-l1-origin"
    }
   ]
  },
  {
   "title": "Engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Seconds per Unsafe L2 Block",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "seconds/block" } },
     "targets": [
      {
       "expr": "1/avg(rate(kona_node_block_labels{instance=~\"$instance\", label=\"unsafe\"}[$__rate_interval]))",
       "legendFormat": "L2 Unsafe Sync Rate"
      },
      {
       "expr": "1/avg(rate(kona_node_block_labels{instance=~\"$instance\", label=\"unsafe\"}[5m]))",
       "legendFormat": "L2 Unsafe Sync Rate (5m avg)"
      },
      {
       "expr": "1/avg(rate(kona_node_block_labels{instance=~\"$instance\", label=\"unsafe\"}[10m]))",
       "legendFormat": "L2 Unsafe Sync Rate (10m avg)"
      }
     ]
    },
    {
     "title": "L2 Sync Speed (blocks/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "max(rate(kona_node_block_labels{instance=~\"$instance\", label=\"unsafe\"}[$__rate_interval]))",
       "legendFormat": "unsafe"
      },
      {
       "expr": "max(rate(kona_node_block_labels{instance=~\"$instance\", label=\"safe\"}[$__rate_interval]))",
       "legendFormat": "safe"
      }
     ]
    },
    {
     "title": "`engine_newPayload` request duration heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "kona_node_engine_method_request_duration{instance=~\"$instance\", method=\"engine_newPayload\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "`engine_forkchoiceUpdated` request duration heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "targets": [
      {
       "expr": "kona_node_engine_method_request_duration{instance=~\"$instance\", method=\"engine_forkchoiceUpdated\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "`engine_getPayload` request duration heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "kona_node_engine_method_request_duration{instance=~\"$instance\", method=\"engine_getPayload\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Engine Task Enqueue Rate / min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "targets": [
      {
       "expr": "sum by(type) (rate(kona_node_engine_task_count{instance=~\"$instance\"}[$__rate_interval])) * 60",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Engine Resets",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_engine_reset_count{instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "L1 Reorganization Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_l1_reorg_count{instance=~\"$instance\"}",
       "legendFormat": "L1 Reorg Count"
      }
     ]
    }
   ]
  },
  {
   "title": "P2P",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Peer Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
     "targets": [
      {
       "expr": "kona_node_swarm_peer_count{instance=\"$instance\"}",
       "legendFormat": "swarm_peer_count"
      },
      {
       "expr": "kona_node_discovery_peer_count{instance=~\"$instance\"}",
       "legendFormat": "discovery_peer_count"
      }
     ]
    },
    {
     "title": "Peers Dialed / min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
     "targets": [
      {
       "expr": "sum(rate(kona_node_dial_peer{instance=~\"$instance\"}[$__interval])) * 60",
       "legendFormat": "Peer Dial Rate / min"
      },
      {
       "expr": "sum(rate(kona_node_dial_peer_error{type=\"already_connected\", instance=\"$instance\"}[$__interval])) * 60",
       "legendFormat": "Already connected Rate / min"
      },
      {
       "expr": "sum(rate(kona_node_dial_peer_error{instance=\"$instance\", type=\"already_dialing\"}[$__interval])) * 60",
       "legendFormat": "Already dialing Rate / min"
      },
      {
       "expr": "sum(rate(kona_node_dial_peer_error{type=\"threshold_reached\", instance=\"$instance\"}[$__interval])) * 60",
       "legendFormat": "Threshold reached rate / min"
      }
     ]
    },
    {
     "title": "GossipSub Connection Events / min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
     "targets": [
      {
       "expr": "sum by(type) (rate(kona_node_gossipsub_connection{instance=~\"$instance\"}[$__rate_interval])) * 60",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Gossip Events / min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
     "targets": [
      {
       "expr": "sum by(type) (rate(kona_node_gossip_events{instance=~\"$instance\"}[$__rate_interval])) * 60",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Discovery Events / min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
     "targets": [
      {
       "expr": "sum by(type) (rate(kona_node_discovery_events{instance=~\"$instance\"}[$__rate_interval])) * 60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Find Node Request Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
     "targets": [
      {
       "expr": "kona_node_find_node_requests{instance=~\"$instance\", find_node=\"find_node\"}",
       "legendFormat": "find-node requests"
      }
     ]
    },
    {
     "title": "ENR Store Time",
     "type": "heatmap",
     "description": "Time taken to store an ENR in the on-disk peerstore",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
     "targets": [
      {
       "expr": "kona_node_enr_store_time{instance=~\"$instance\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Derivation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prepared Payload Attributes",
     "type": "timeseries",
     "description": "The cumulative number of prepared attributes by the derivation pipeline.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "kona_derive_prepared_attributes{instance=~\"$instance\"}",
       "legendFormat": "Derived Payload Attributes"
      },
      {
       "expr": "kona_derive_payload_tx_count{instance=\"$instance\"}",
       "legendFormat": "Tx Count"
      }
     ]
    },
    {
     "title": "L1 Transactions Ingested by Data Source [Stage: L1 Retrieval]",
     "type": "timeseries",
     "description": "Which data source the pipeline is reading txs from. Either calldata or blobs.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "kona_derive_dap_sources{instance=~\"$instance\"}",
       "legendFormat": "{{source}} txs"
      }
     ]
    },
    {
     "title": "Latest System Config Update",
     "type": "gauge",
     "description": "The latest block height at which the system config was updated.",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_genesis_latest_system_config_update{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "System Config Update Error",
     "type": "gauge",
     "description": "The latest block height at which the system config update errored. This is a critical error and will halt the node. If this gauge is non-zero (is set to a block height, there is a bug).",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_genesis_sys_config_update_error{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pipeline Signals",
     "type": "bargauge",
     "description": "Number of pipeline signals grouped by type.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_derive_pipeline_signals{instance=\"$instance\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Pipeline L1 Origin",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_derive_pipeline_origin{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "L2 Block Height",
     "type": "stat",
     "description": "The latest l2 block height the pipeline was stepped on.",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_derive_pipeline_step_block{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Parsed Frames [Stage: Frame Queue]",
     "type": "timeseries",
     "description": "The last recorded number of frames read in by the `FrameQueue` stage. This metric does not track that current number of frames in the buffer since it updates too quickly for prometheus to scrape the metrics.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "kona_derive_frame_queue_buffer{instance=~\"$instance\"}",
       "legendFormat": "frame count"
      },
      {
       "expr": "kona_derive_frame_queue_mem{instance=~\"$instance\"}",
       "legendFormat": "frame size (bytes)"
      }
     ]
    },
    {
     "title": "Pipeline Steps / Min",
     "type": "timeseries",
     "description": "The number of pipeline steps per minute",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "max(rate(kona_derive_pipeline_steps{instance=\"$instance\"}[$__rate_interval])) * 60",
       "legendFormat": "pipeline steps"
      }
     ]
    },
    {
     "title": "Channel Count",
     "type": "gauge",
     "description": "The number of channels held in the `ChannelAssembler` stage of the derivation pipeline.",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_derive_channel_buffer{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Channel Timeout",
     "type": "gauge",
     "description": "The number of blocks until the current channel times out.",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_derive_blocks_until_channel_timeout{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Reading Batch",
     "type": "gauge",
     "description": "If the batch reader is set.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_derive_batch_reader_set{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Payload Attributes Build Time",
     "type": "heatmap",
     "description": "The time it took to build payload attributes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "kona_derive_attributes_build_duration{instance=\"$instance\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Channel Size [Stage: Channel Assembler]",
     "type": "timeseries",
     "description": "The current size of channels held in the `ChannelAssembler` stage of the derivation pipeline.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "kona_derive_channel_mem{instance=~\"$instance\"}",
       "legendFormat": "channel size (bytes)"
      },
      {
       "expr": "kona_derive_max_rlp_bytes{instance=\"$instance\"}",
       "legendFormat": "max size"
      }
     ]
    },
    {
     "title": "Cumulative Batches by Type",
     "type": "timeseries",
     "description": "The batches read by type.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "kona_derive_read_batches{instance=~\"$instance\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Decompressed Batch Size + Type [Stage: Channel Reader]",
     "type": "timeseries",
     "description": "The decompressed batch size and type.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "kona_derive_latest_decompressed_batch_size{instance=~\"$instance\"}",
       "legendFormat": "decompressed batch size"
      },
      {
       "expr": "kona_derive_latest_decompressed_batch_type{instance=\"$instance\"}",
       "legendFormat": "decompression type"
      }
     ]
    },
    {
     "title": "Derived Batches [Stage: Batch Stream]",
     "type": "timeseries",
     "description": "The number and size of singular batches pulled into the `BatchStream` stage of the derivation pipeline.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "kona_derive_batch_buffer{instance=~\"$instance\"}",
       "legendFormat": "batch count"
      },
      {
       "expr": "kona_derive_batch_mem{instance=~\"$instance\"}",
       "legendFormat": "batch size (bytes)"
      }
     ]
    },
    {
     "title": "Batch Validation L1 Blocks",
     "type": "timeseries",
     "description": "The l1 blocks in the `BatchValidator` stage of the derivation pipeline.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "kona_derive_l1_blocks_start{instance=~\"$instance\"}",
       "legendFormat": "l1 blocks start"
      },
      {
       "expr": "kona_derive_l1_blocks_end{instance=~\"$instance\"}",
       "legendFormat": "l1 blocks end"
      }
     ]
    },
    {
     "title": "Origin Advance Duration Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "kona_derive_pipeline_origin_advance{instance=\"$instance\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Batch Prefix Check Heatmap",
     "type": "heatmap",
     "description": "Duration for checking batch prefixes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "kona_derive_check_batch_prefix_duration{instance=\"$instance\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Batch Validity",
     "type": "timeseries",
     "description": "Batches grouped by batch validity",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "kona_derive_batch_validity{instance=~\"$instance\"}",
       "legendFormat": "{{validity}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Derivation RPC Providers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Beacon Requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "kona_providers_beacon_requests{instance=\"$instance\"}",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Chain Provider Cache Misses",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "kona_providers_chain_cache_misses{instance=\"$instance\"}",
       "legendFormat": "{{cache}}"
      }
     ]
    },
    {
     "title": "Beacon Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "kona_providers_beacon_errors{instance=\"$instance\"}",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Chain Provider Cache Hits",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "kona_providers_chain_cache_hits{instance=\"$instance\"}",
       "legendFormat": "{{cache}}"
      }
     ]
    },
    {
     "title": "L1 Provider RPC Calls",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "kona_providers_chain_rpc_calls{instance=\"$instance\"}",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "L2 Provider Rpc Requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "kona_providers_l2_chain_requests{instance=\"$instance\"}",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "L1 Provider RPC Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "kona_providers_chain_rpc_errors{instance=\"$instance\"}",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "L2 Provider RPC Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "kona_providers_l2_chain_errors{instance=\"$instance\"}",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Beacon Provider RPC Calls",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "kona_providers_blob_sidecar_fetches{instance=\"$instance\"}",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Beacon Provider RPC Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "kona_providers_blob_sidecar_errors{instance=\"$instance\"}",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Cache Entries",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "kona_providers_cache_entries{instance=\"$instance\"}",
       "legendFormat": "{{cache}}"
      }
     ]
    },
    {
     "title": "Cache Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "expr": "kona_providers_cache_memory_bytes{instance=\"$instance\"}",
       "legendFormat": "{{cache}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sequencer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attributes Build Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kona_node_sequencer_attributes_build_duration{instance=~\"$instance\"}",
       "legendFormat": "Attributes Build Duration"
      }
     ]
    },
    {
     "title": "Block Building Seal Task Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kona_node_sequencer_block_building_seal_task_duration{instance=~\"$instance\"}",
       "legendFormat": "Block Building Seal Task Duration"
      }
     ]
    },
    {
     "title": "Sequencer Active",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 48 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_sequencer_state{instance=~\"$instance\"}",
       "legendFormat": "{{active}}"
      }
     ]
    },
    {
     "title": "Recovery Mode",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 48 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_sequencer_state{instance=~\"$instance\"}",
       "legendFormat": "{{recovery}}"
      }
     ]
    },
    {
     "title": "Conductor Commitment Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kona_node_sequencer_conductor_commitment_duration{instance=~\"$instance\"}",
       "legendFormat": "Conductor Commitment Duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Dynamic Protocol Configuration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unsafe Block Signer Address",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 126 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_runtime_loader{instance=~\"$instance\"}",
       "legendFormat": "{{unsafe_block_signer_address}}"
      }
     ]
    },
    {
     "title": "Required Protocol Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 126 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_runtime_loader{instance=~\"$instance\"}",
       "legendFormat": "{{required_protocol_version}}"
      }
     ]
    },
    {
     "title": "Recommended Protocol Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 126 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_runtime_loader{instance=~\"$instance\"}",
       "legendFormat": "{{recommended_protocol_version}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rollup Configuration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hardfork Activation Times",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 15, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort(kona_node_hardforks{instance=~\"$instance\"} >= 0) * 1000",
       "legendFormat": "{{fork}}"
      }
     ]
    },
    {
     "title": "Unscheduled Hardforks",
     "type": "stat",
     "description": "Hardforks that the node supports, but are not scheduled within the RollupConfig for the current chain.\n\nSome chains do not enable optional hardforks (such as Pectra Blob Schedule,) and some forks are WIPs that have not yet received an activation timestamp.",
     "gridPos": { "h": 10, "w": 9, "x": 15, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_hardforks{instance=~\"$instance\"} < 0",
       "legendFormat": "{{fork}}"
      }
     ]
    },
    {
     "title": "Genesis L2 Time",
     "type": "stat",
     "description": "Genesis L2 Time",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 137 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_rollup_config{instance=~\"$instance\"}",
       "legendFormat": "{{genesis_l2_time}}"
      }
     ]
    },
    {
     "title": "L2 Block Time",
     "type": "stat",
     "description": "L2 Block Time",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 137 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_rollup_config{instance=~\"$instance\"}",
       "legendFormat": "{{block_time}}"
      }
     ]
    },
    {
     "title": "L1 Chain ID",
     "type": "stat",
     "description": "L1 Chain ID",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 137 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_rollup_config{instance=~\"$instance\"}",
       "legendFormat": "{{l1_chain_id}}"
      }
     ]
    },
    {
     "title": "Batch Inbox Address",
     "type": "stat",
     "description": "The Batch Inbox Address (Can be changed in the `SystemConfig`. The RollupConfig's value is _only_ the value at genesis, and may not be the chain's current batch inbox.)",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 137 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_rollup_config{instance=~\"$instance\"}",
       "legendFormat": "{{batch_inbox_address}}"
      }
     ]
    },
    {
     "title": "Genesis L1 Block",
     "type": "stat",
     "description": "Genesis L1 Block",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 139 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_rollup_config{instance=~\"$instance\"}",
       "legendFormat": "{{l1_genesis_block_num}}"
      }
     ]
    },
    {
     "title": "Genesis L2 Block",
     "type": "stat",
     "description": "Genesis L2 Block",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 139 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_rollup_config{instance=~\"$instance\"}",
       "legendFormat": "{{l2_genesis_block_num}}"
      }
     ]
    },
    {
     "title": "L2 Chain ID",
     "type": "stat",
     "description": "L2 Chain ID",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 139 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_rollup_config{instance=~\"$instance\"}",
       "legendFormat": "{{l2_chain_id}}"
      }
     ]
    },
    {
     "title": "Deposit Contract Address",
     "type": "stat",
     "description": "Deposit Contract Address",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 139 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_rollup_config{instance=~\"$instance\"}",
       "legendFormat": "{{deposit_contract_address}}"
      }
     ]
    },
    {
     "title": "Granite Channel Timeout",
     "type": "stat",
     "description": "Granite Channel Timeout",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 141 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_rollup_config{instance=~\"$instance\"}",
       "legendFormat": "{{granite_channel_timeout}}"
      }
     ]
    },
    {
     "title": "Seq Window Size",
     "type": "stat",
     "description": "Sequencer Window Size",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 141 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_rollup_config{instance=~\"$instance\"}",
       "legendFormat": "{{sequencer_window_size}}"
      }
     ]
    },
    {
     "title": "Max Seq Drift",
     "type": "stat",
     "description": "Max Sequencer Drift",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 141 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_rollup_config{instance=~\"$instance\"}",
       "legendFormat": "{{max_sequencer_drift}}"
      }
     ]
    },
    {
     "title": "L1 System Config Address",
     "type": "stat",
     "description": "L1 System Config Address",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 141 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_rollup_config{instance=~\"$instance\"}",
       "legendFormat": "{{l1_system_config_address}}"
      }
     ]
    },
    {
     "title": "Protocol Versions Address",
     "type": "stat",
     "description": "Protocol Versions Address",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 143 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_node_rollup_config{instance=~\"$instance\"}",
       "legendFormat": "{{protocol_versions_address}}"
      }
     ]
    }
   ]
  },
  {
   "title": "P2P Configuration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Peer Scoring",
     "type": "stat",
     "description": "The peer scoring level configured via the cli flag.",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 128 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_cli_opts{instance=~\"$instance\"}",
       "legendFormat": "{{kona_node_peer_scoring_level}}"
      }
     ]
    },
    {
     "title": "Peer Redial",
     "type": "stat",
     "description": "The amount of times peers are able to be redialed",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 128 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_cli_opts{instance=~\"$instance\"}",
       "legendFormat": "{{kona_node_peer_redialing}}"
      }
     ]
    },
    {
     "title": "Ban Peers",
     "type": "stat",
     "description": "Whether P2P Peer Banning is enabled.",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 128 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_cli_opts{instance=~\"$instance\"}",
       "legendFormat": "{{kona_node_banning_enabled}}"
      }
     ]
    },
    {
     "title": "Gossip Mesh D",
     "type": "stat",
     "description": "Gossip Mesh D",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 128 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_cli_opts{instance=~\"$instance\"}",
       "legendFormat": "{{kona_node_gossip_mesh_d}}"
      }
     ]
    },
    {
     "title": "Discv5 Peers Lo",
     "type": "stat",
     "description": "Low-tide peer count. The discv5 service will automatically search for peers if its peer count falls below this number.",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 128 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_cli_opts{instance=~\"$instance\"}",
       "legendFormat": "{{kona_node_peers_lo}}"
      }
     ]
    },
    {
     "title": "Resources",
     "type": "text",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 128 },
     "options": {
      "content": "- [Kona Monorepo](https://github.com/op-rs/kona)\n- [Optimism Monorepo](https://github.com/ethereum-optimism/optimism)\n- [Op Alloy](https://github.com/alloy-rs/op-alloy)\n- [Reth](https://github.com/paradigmxyz/reth)\n- [Revm](https://github.com/bluealloy/revm)"
     }
    },
    {
     "title": "Advertise IP",
     "type": "stat",
     "description": "The P2P IP Address advertised by the node's ENR.",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 130 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_cli_opts{instance=~\"$instance\"}",
       "legendFormat": "{{kona_node_advertise_ip}}"
      }
     ]
    },
    {
     "title": "Advertise TCP Port",
     "type": "stat",
     "description": "The TCP Port advertised by the node's ENR.",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 130 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_cli_opts{instance=~\"$instance\"}",
       "legendFormat": "{{kona_node_advertise_tcp}}"
      }
     ]
    },
    {
     "title": "Advertise UDP Port",
     "type": "stat",
     "description": "The UDP Port advertised in the node's ENR.",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 130 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_cli_opts{instance=~\"$instance\"}",
       "legendFormat": "{{kona_node_advertise_udp}}"
      }
     ]
    },
    {
     "title": "Gossip Mesh D Lo",
     "type": "stat",
     "description": "This is the gossipsub topic stable mesh low watermark.",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 130 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_cli_opts{instance=~\"$instance\"}",
       "legendFormat": "{{kona_node_gossip_mesh_d_lo}}"
      }
     ]
    },
    {
     "title": "Discv5 Peers Hi",
     "type": "stat",
     "description": "High-tide peer count. The discv5 service will start pruning peer connections slowly after reaching this number.",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 130 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_cli_opts{instance=~\"$instance\"}",
       "legendFormat": "{{kona_node_peers_hi}}"
      }
     ]
    },
    {
     "title": "Topic Scoring",
     "type": "stat",
     "description": "Whether P2P Topic Scoring is enabled.",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 132 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_cli_opts{instance=~\"$instance\"}",
       "legendFormat": "{{kona_node_topic_scoring_enabled}}"
      }
     ]
    },
    {
     "title": "Topic Scoring",
     "type": "stat",
     "description": "Whether P2P Topic Scoring is enabled.",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 132 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_cli_opts{instance=~\"$instance\"}",
       "legendFormat": "{{kona_node_topic_scoring_enabled}}"
      }
     ]
    },
    {
     "title": "Discovery Interval",
     "type": "stat",
     "description": "The interval at which to query the discv5 service for new nodes through a `FINDNODES` request.",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 132 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_cli_opts{instance=~\"$instance\"}",
       "legendFormat": "{{kona_node_discovery_interval}}"
      }
     ]
    },
    {
     "title": "Gossip Mesh D Hi",
     "type": "stat",
     "description": "This is the gossipsub topic stable mesh high watermark.",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 132 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_cli_opts{instance=~\"$instance\"}",
       "legendFormat": "{{kona_node_gossip_mesh_d_hi}}"
      }
     ]
    },
    {
     "title": "Gossip Mesh D Lazy",
     "type": "stat",
     "description": "Gossip Mesh D Lazy",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 132 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_cli_opts{instance=~\"$instance\"}",
       "legendFormat": "{{kona_node_gossip_mesh_d_lazy}}"
      }
     ]
    },
    {
     "title": "Ban Duration",
     "type": "stat",
     "description": "The duration to ban nodes in seconds.",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 132 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kona_cli_opts{instance=~\"$instance\"}",
       "legendFormat": "{{kona_node_ban_duration}}"
      }
     ]
    }
   ]
  }
 ]
}