language: "en"
early_access: false
reviews:
  high_level_summary: false
  poem: false
  review_status: false
  collapse_walkthrough: true
  path_filters:
    - "!**/*.json"
    - "!op-bindings/bindings/**"
  path_instructions:
    - path: "**.sol"
      instructions: "Focus on the following areas:
        - Security
        - Identifying test cases which are lacking
        - Removing unnecessary code
      "
  auto_review:
    enabled: false
    drafts: false
    base_branches:
      - "develop"
      - "feat/*"
chat:
  auto_reply: true
