codecov:
  require_ci_to_pass: false
comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: true
  flags:
    - contracts-bedrock-tests

ignore:
  - "op-e2e"
  - "op-bindings/bindings/*.go"
  - "**/*.t.sol"
  - "packages/contracts-bedrock/test/**/*.sol"
  - "packages/contracts-bedrock/scripts/**/*.sol"
  - "packages/contracts-bedrock/contracts/vendor/WETH9.sol"
  - 'packages/contracts-bedrock/contracts/EAS/**/*.sol'
coverage:
  status:
    patch:
      default:
        target: auto  # target coverage is equal to the PR base
        threshold: 0% # coverage is not allowed to reduce vs. the PR base
        base: auto
        informational: true
        enabled: true
    project:
      default:
        informational: true
flag_management:
  # Note: flags should have the same name as the circleci job in which they
  # are uploaded.
  individual_flags:
    - name: contracts-bedrock-tests
      paths:
        - packages/contracts-bedrock/src
      statuses:
        - type: patch
          target: 100%
    - name: bedrock-go-tests
    - name: contracts-tests
    - name: chain-mon-tests
    - name: sdk-tests
