FROM node:11

WORKDIR /server
COPY . /server
RUN yarn

# Copy live env config updates file to /server so that it may be updated while running.
COPY ./packages/rollup-core/config/env_var_updates.config /server

WORKDIR /server/packages/rollup-core

# This is required for the wait_for_postgres script
RUN sudo apt-get install -y postgresql-client

ENTRYPOINT [ "bash", "./exec/wait_for_postgres.sh", "yarn", "run", "services" ]
