FROM node:11

# Used to mount the code so image isn't re-built every time code changes
WORKDIR /mnt/optimism-monorepo/packages/rollup-services

# This is required for the wait_for_postgres script
RUN apt-get update
RUN apt-get install -y postgresql-client
RUN yarn global add --ignore-engines wsrun rimraf typescript mocha

EXPOSE 8545
ENTRYPOINT [ "bash", "./exec/build_and_run.sh", "yarn", "run", "services" ]
