[tools]

# Core dependencies
bun = "1.2.5"
go = "1.24.13"
golangci-lint = "2.8.0"
gotestsum = "1.12.3"
mockery = "2.53.3"
rust = [
  { version = "1.94.0", components = "clippy,rustfmt,llvm-tools-preview", targets = "riscv32imac-unknown-none-elf,wasm32-unknown-unknown,wasm32-wasip1" },
  { version = "nightly-2026-02-20", components = "rustfmt" },
]
python = "3.12.13"
uv = "0.5.5"
jq = "1.7.1"
yq = "4.44.5"
shellcheck = "0.10.0"
shfmt = "3.11.0"
direnv = "2.35.0"
just = "1.46.0"
make = "4.4.1"

svm-rs = "0.5.19"

# Rust tooling
"github:crate-ci/cargo-release" = { version = "1.1.2" }

"github:nextest-rs/nextest" = { version = "0.9.132", version_prefix = "cargo-nextest-", bin = "cargo-nextest" }
"github:EmbarkStudios/cargo-deny" = "0.19.4"
"github:ggwpez/zepter" = { version = "1.88.0", version_prefix = "v" }
"github:crate-ci/typos" = { version = "1.45.1", version_prefix = "v" }
"github:est31/cargo-udeps" = { version = "0.1.60", version_prefix = "v" }
"github:taiki-e/cargo-hack" = { version = "0.6.44", version_prefix = "v" }
"github:taiki-e/cargo-llvm-cov" = { version = "0.8.5", version_prefix = "v" }
"github:lycheeverse/lychee" = { version = "0.23.0", version_prefix = "lychee-v", bin = "lychee" }

# Go dependencies
"go:github.com/ethereum/go-ethereum/cmd/abigen" = "1.15.10"
"go:github.com/ethereum/go-ethereum/cmd/geth" = "1.16.4"    # Osaka testnet release.

# Python dependencies
"pipx:slither-analyzer" = "0.10.2"
"pipx:semgrep" = "1.137.0"
"pipx:md_toc" = "9.0.0"

# Foundry dependencies
# Foundry is a special case because it supplies multiple binaries at the same
# GitHub release, so we need to use the aliasing trick to get mise to not error
# The git ref here should be on the `stable` branch.
# Updated to use the specific nightly build
forge = "1.2.3"
cast = "1.2.3"
anvil = "1.2.3"

# Other dependencies
codecov-uploader = "0.8.0"
goreleaser-pro = "2.11.2"
git-cliff = "2.12.0"

# Fake dependencies
# Put things here if you need to track versions of tools or projects that can't
# actually be managed by mise (yet). Make sure that anything you put in here is
# also found inside of disabled_tools or mise will try to install it.
kontrol = "1.0.90"
binary_signer = "1.0.4"

[tool_alias]
forge = "github:foundry-rs/foundry[bin=forge,version_prefix=v]"
cast = "github:foundry-rs/foundry[bin=cast,version_prefix=v]"
anvil = "github:foundry-rs/foundry[bin=anvil,version_prefix=v]"
just = "github:casey/just"
codecov-uploader = "github:codecov/uploader[version_prefix=v]"
goreleaser-pro = "github:goreleaser/goreleaser-pro[bin=goreleaser,version_prefix=v]"
gotestsum = "github:gotestyourself/gotestsum[version_prefix=v]"
mockery = "github:vektra/mockery[version_prefix=v]"
svm-rs = "github:alloy-rs/svm-rs[bin=svm,version_prefix=v]"
# These are disabled, but latest mise versions error if they don't have a known
# install source even though it won't ever actually use that source.
kontrol = "github:ethereum-optimism/fake-kontrol"
binary_signer = "github:ethereum-optimism/fake-binary_signer"

[settings]
experimental = true
pipx.uvx = true
disable_tools = ["kontrol", "binary_signer"]
