[package]
name = "kona-sp1-super-range"
version = "0.0.1"
publish = false
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
kona-proof.workspace = true
kona-sp1-client-utils.workspace = true
kona-sp1-ethereum-client-utils.workspace = true
rkyv.workspace = true
sp1-zkvm.workspace = true

[lints]
workspace = true
