FROM golang:1.18.0-alpine3.15 as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git jq bash

COPY Makefile /app/Makefile
COPY go.mod /app/go.mod
COPY go.sum /app/go.sum

WORKDIR /app

COPY ./l2os /app/l2os
COPY ./opnode /app/opnode
RUN make l2os

FROM alpine:3.15

COPY --from=builder /app/bin/l2os /usr/local/bin

CMD ["l2os"]
