// Code generated - DO NOT EDIT.
// This file is a generated binding and any manual changes will be lost.

package bindings

var Sources = []string{
    "../../node_modules/.pnpm/@openzeppelin+contracts-upgradeable@4.7.3/node_modules/@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol",
    "../../node_modules/.pnpm/@openzeppelin+contracts-upgradeable@4.7.3/node_modules/@openzeppelin/contracts-upgradeable/utils/AddressUpgradeable.sol",
    "../../node_modules/.pnpm/@openzeppelin+contracts-upgradeable@4.7.3/node_modules/@openzeppelin/contracts-upgradeable/utils/ContextUpgradeable.sol",
    "../../node_modules/.pnpm/@openzeppelin+contracts@4.7.3/node_modules/@openzeppelin/contracts/token/ERC721/IERC721.sol",
    "../../node_modules/.pnpm/@openzeppelin+contracts@4.7.3/node_modules/@openzeppelin/contracts/utils/Context.sol",
    "../../node_modules/.pnpm/@openzeppelin+contracts@4.7.3/node_modules/@openzeppelin/contracts/utils/introspection/IERC165.sol",
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/Base.sol",
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdAssertions.sol",
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdChains.sol",
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdCheats.sol",
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdError.sol",
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdInvariant.sol",
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdJson.sol",
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdMath.sol",
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdStorage.sol",
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdStyle.sol",
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdUtils.sol",
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/Vm.sol",
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/console.sol",
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/console2.sol",
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/interfaces/IMulticall3.sol",
    "contracts/EAS/Common.sol",
    "contracts/EAS/IEAS.sol",
    "contracts/EAS/ISchemaRegistry.sol",
    "contracts/EAS/resolver/ISchemaResolver.sol",
    "contracts/L2/CrossDomainOwnable.sol",
    "contracts/dispute/DisputeGameFactory.sol",
    "contracts/dispute/interfaces/IBondManager.sol",
    "contracts/dispute/interfaces/IDisputeGame.sol",
    "contracts/dispute/interfaces/IDisputeGameFactory.sol",
    "contracts/dispute/interfaces/IFaultDisputeGame.sol",
    "contracts/dispute/interfaces/IInitializable.sol",
    "contracts/dispute/lib/LibClock.sol",
    "contracts/dispute/lib/LibHashing.sol",
    "contracts/dispute/lib/LibPosition.sol",
    "contracts/libraries/Bytes.sol",
    "contracts/libraries/Clone.sol",
    "contracts/libraries/DisputeErrors.sol",
    "contracts/libraries/DisputeTypes.sol",
    "contracts/libraries/Encoding.sol",
    "contracts/libraries/Hashing.sol",
    "contracts/libraries/LegacyCrossDomainUtils.sol",
    "contracts/libraries/Predeploys.sol",
    "contracts/libraries/Types.sol",
    "contracts/libraries/rlp/RLPReader.sol",
    "contracts/libraries/rlp/RLPWriter.sol",
    "contracts/libraries/trie/MerkleTrie.sol",
    "contracts/libraries/trie/SecureMerkleTrie.sol",
    "contracts/periphery/AssetReceiver.sol",
    "contracts/periphery/Transactor.sol",
    "contracts/periphery/drippie/IDripCheck.sol",
    "contracts/test/Clones.t.sol",
    "contracts/test/LibClock.t.sol",
    "contracts/test/LibPosition.t.sol",
    "contracts/test/RLP.t.sol",
    "contracts/universal/IOptimismMintableERC20.sol",
    "contracts/universal/IOptimismMintableERC721.sol",
    "contracts/universal/Semver.sol",
    "contracts/vendor/AddressAliasHelper.sol",
    "node_modules/@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol",
    "node_modules/@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol",
    "node_modules/@openzeppelin/contracts-upgradeable/utils/AddressUpgradeable.sol",
    "node_modules/@openzeppelin/contracts-upgradeable/utils/ContextUpgradeable.sol",
    "node_modules/@openzeppelin/contracts/access/Ownable.sol",
    "node_modules/@openzeppelin/contracts/token/ERC721/IERC721.sol",
    "node_modules/@openzeppelin/contracts/token/ERC721/extensions/IERC721Enumerable.sol",
    "node_modules/@openzeppelin/contracts/utils/Context.sol",
    "node_modules/@openzeppelin/contracts/utils/Strings.sol",
    "node_modules/@openzeppelin/contracts/utils/introspection/IERC165.sol",
    "node_modules/@rari-capital/solmate/src/auth/Owned.sol",
    "node_modules/@rari-capital/solmate/src/tokens/ERC20.sol",
    "node_modules/@rari-capital/solmate/src/tokens/ERC721.sol",
    "node_modules/@rari-capital/solmate/src/utils/Bytes32AddressLib.sol",
    "node_modules/clones-with-immutable-args/src/ClonesWithImmutableArgs.sol",
    "node_modules/ds-test/src/test.sol",
    "node_modules/forge-std/src/Base.sol",
    "node_modules/forge-std/src/StdAssertions.sol",
    "node_modules/forge-std/src/StdChains.sol",
    "node_modules/forge-std/src/StdCheats.sol",
    "node_modules/forge-std/src/StdError.sol",
    "node_modules/forge-std/src/StdInvariant.sol",
    "node_modules/forge-std/src/StdJson.sol",
    "node_modules/forge-std/src/StdMath.sol",
    "node_modules/forge-std/src/StdStorage.sol",
    "node_modules/forge-std/src/StdStyle.sol",
    "node_modules/forge-std/src/StdUtils.sol",
    "node_modules/forge-std/src/Test.sol",
    "node_modules/forge-std/src/Vm.sol",
    "node_modules/forge-std/src/console.sol",
    "node_modules/forge-std/src/console2.sol",
    "node_modules/forge-std/src/interfaces/IMulticall3.sol",
}

var SourceToId = map[string]uint{
    "../../node_modules/.pnpm/@openzeppelin+contracts-upgradeable@4.7.3/node_modules/@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol": 0,
    "../../node_modules/.pnpm/@openzeppelin+contracts-upgradeable@4.7.3/node_modules/@openzeppelin/contracts-upgradeable/utils/AddressUpgradeable.sol": 1,
    "../../node_modules/.pnpm/@openzeppelin+contracts-upgradeable@4.7.3/node_modules/@openzeppelin/contracts-upgradeable/utils/ContextUpgradeable.sol": 2,
    "../../node_modules/.pnpm/@openzeppelin+contracts@4.7.3/node_modules/@openzeppelin/contracts/token/ERC721/IERC721.sol": 3,
    "../../node_modules/.pnpm/@openzeppelin+contracts@4.7.3/node_modules/@openzeppelin/contracts/utils/Context.sol": 4,
    "../../node_modules/.pnpm/@openzeppelin+contracts@4.7.3/node_modules/@openzeppelin/contracts/utils/introspection/IERC165.sol": 5,
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/Base.sol": 6,
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdAssertions.sol": 7,
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdChains.sol": 8,
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdCheats.sol": 9,
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdError.sol": 10,
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdInvariant.sol": 11,
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdJson.sol": 12,
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdMath.sol": 13,
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdStorage.sol": 14,
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdStyle.sol": 15,
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdUtils.sol": 16,
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/Vm.sol": 17,
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/console.sol": 18,
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/console2.sol": 19,
    "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/interfaces/IMulticall3.sol": 20,
    "contracts/EAS/Common.sol": 21,
    "contracts/EAS/IEAS.sol": 22,
    "contracts/EAS/ISchemaRegistry.sol": 23,
    "contracts/EAS/resolver/ISchemaResolver.sol": 24,
    "contracts/L2/CrossDomainOwnable.sol": 25,
    "contracts/dispute/DisputeGameFactory.sol": 26,
    "contracts/dispute/interfaces/IBondManager.sol": 27,
    "contracts/dispute/interfaces/IDisputeGame.sol": 28,
    "contracts/dispute/interfaces/IDisputeGameFactory.sol": 29,
    "contracts/dispute/interfaces/IFaultDisputeGame.sol": 30,
    "contracts/dispute/interfaces/IInitializable.sol": 31,
    "contracts/dispute/lib/LibClock.sol": 32,
    "contracts/dispute/lib/LibHashing.sol": 33,
    "contracts/dispute/lib/LibPosition.sol": 34,
    "contracts/libraries/Bytes.sol": 35,
    "contracts/libraries/Clone.sol": 36,
    "contracts/libraries/DisputeErrors.sol": 37,
    "contracts/libraries/DisputeTypes.sol": 38,
    "contracts/libraries/Encoding.sol": 39,
    "contracts/libraries/Hashing.sol": 40,
    "contracts/libraries/LegacyCrossDomainUtils.sol": 41,
    "contracts/libraries/Predeploys.sol": 42,
    "contracts/libraries/Types.sol": 43,
    "contracts/libraries/rlp/RLPReader.sol": 44,
    "contracts/libraries/rlp/RLPWriter.sol": 45,
    "contracts/libraries/trie/MerkleTrie.sol": 46,
    "contracts/libraries/trie/SecureMerkleTrie.sol": 47,
    "contracts/periphery/AssetReceiver.sol": 48,
    "contracts/periphery/Transactor.sol": 49,
    "contracts/periphery/drippie/IDripCheck.sol": 50,
    "contracts/test/Clones.t.sol": 51,
    "contracts/test/LibClock.t.sol": 52,
    "contracts/test/LibPosition.t.sol": 53,
    "contracts/test/RLP.t.sol": 54,
    "contracts/universal/IOptimismMintableERC20.sol": 55,
    "contracts/universal/IOptimismMintableERC721.sol": 56,
    "contracts/universal/Semver.sol": 57,
    "contracts/vendor/AddressAliasHelper.sol": 58,
    "node_modules/@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol": 59,
    "node_modules/@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol": 60,
    "node_modules/@openzeppelin/contracts-upgradeable/utils/AddressUpgradeable.sol": 61,
    "node_modules/@openzeppelin/contracts-upgradeable/utils/ContextUpgradeable.sol": 62,
    "node_modules/@openzeppelin/contracts/access/Ownable.sol": 63,
    "node_modules/@openzeppelin/contracts/token/ERC721/IERC721.sol": 64,
    "node_modules/@openzeppelin/contracts/token/ERC721/extensions/IERC721Enumerable.sol": 65,
    "node_modules/@openzeppelin/contracts/utils/Context.sol": 66,
    "node_modules/@openzeppelin/contracts/utils/Strings.sol": 67,
    "node_modules/@openzeppelin/contracts/utils/introspection/IERC165.sol": 68,
    "node_modules/@rari-capital/solmate/src/auth/Owned.sol": 69,
    "node_modules/@rari-capital/solmate/src/tokens/ERC20.sol": 70,
    "node_modules/@rari-capital/solmate/src/tokens/ERC721.sol": 71,
    "node_modules/@rari-capital/solmate/src/utils/Bytes32AddressLib.sol": 72,
    "node_modules/clones-with-immutable-args/src/ClonesWithImmutableArgs.sol": 73,
    "node_modules/ds-test/src/test.sol": 74,
    "node_modules/forge-std/src/Base.sol": 75,
    "node_modules/forge-std/src/StdAssertions.sol": 76,
    "node_modules/forge-std/src/StdChains.sol": 77,
    "node_modules/forge-std/src/StdCheats.sol": 78,
    "node_modules/forge-std/src/StdError.sol": 79,
    "node_modules/forge-std/src/StdInvariant.sol": 80,
    "node_modules/forge-std/src/StdJson.sol": 81,
    "node_modules/forge-std/src/StdMath.sol": 82,
    "node_modules/forge-std/src/StdStorage.sol": 83,
    "node_modules/forge-std/src/StdStyle.sol": 84,
    "node_modules/forge-std/src/StdUtils.sol": 85,
    "node_modules/forge-std/src/Test.sol": 86,
    "node_modules/forge-std/src/Vm.sol": 87,
    "node_modules/forge-std/src/console.sol": 88,
    "node_modules/forge-std/src/console2.sol": 89,
    "node_modules/forge-std/src/interfaces/IMulticall3.sol": 90,
}

var IdToSource = map[uint]string{
    0: "../../node_modules/.pnpm/@openzeppelin+contracts-upgradeable@4.7.3/node_modules/@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol",
    1: "../../node_modules/.pnpm/@openzeppelin+contracts-upgradeable@4.7.3/node_modules/@openzeppelin/contracts-upgradeable/utils/AddressUpgradeable.sol",
    2: "../../node_modules/.pnpm/@openzeppelin+contracts-upgradeable@4.7.3/node_modules/@openzeppelin/contracts-upgradeable/utils/ContextUpgradeable.sol",
    3: "../../node_modules/.pnpm/@openzeppelin+contracts@4.7.3/node_modules/@openzeppelin/contracts/token/ERC721/IERC721.sol",
    4: "../../node_modules/.pnpm/@openzeppelin+contracts@4.7.3/node_modules/@openzeppelin/contracts/utils/Context.sol",
    5: "../../node_modules/.pnpm/@openzeppelin+contracts@4.7.3/node_modules/@openzeppelin/contracts/utils/introspection/IERC165.sol",
    6: "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/Base.sol",
    7: "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdAssertions.sol",
    8: "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdChains.sol",
    9: "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdCheats.sol",
    10: "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdError.sol",
    11: "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdInvariant.sol",
    12: "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdJson.sol",
    13: "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdMath.sol",
    14: "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdStorage.sol",
    15: "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdStyle.sol",
    16: "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/StdUtils.sol",
    17: "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/Vm.sol",
    18: "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/console.sol",
    19: "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/console2.sol",
    20: "../../node_modules/.pnpm/github.com+foundry-rs+forge-std@e8a047e3f40f13fa37af6fe14e6e06283d9a060e/node_modules/forge-std/src/interfaces/IMulticall3.sol",
    21: "contracts/EAS/Common.sol",
    22: "contracts/EAS/IEAS.sol",
    23: "contracts/EAS/ISchemaRegistry.sol",
    24: "contracts/EAS/resolver/ISchemaResolver.sol",
    25: "contracts/L2/CrossDomainOwnable.sol",
    26: "contracts/dispute/DisputeGameFactory.sol",
    27: "contracts/dispute/interfaces/IBondManager.sol",
    28: "contracts/dispute/interfaces/IDisputeGame.sol",
    29: "contracts/dispute/interfaces/IDisputeGameFactory.sol",
    30: "contracts/dispute/interfaces/IFaultDisputeGame.sol",
    31: "contracts/dispute/interfaces/IInitializable.sol",
    32: "contracts/dispute/lib/LibClock.sol",
    33: "contracts/dispute/lib/LibHashing.sol",
    34: "contracts/dispute/lib/LibPosition.sol",
    35: "contracts/libraries/Bytes.sol",
    36: "contracts/libraries/Clone.sol",
    37: "contracts/libraries/DisputeErrors.sol",
    38: "contracts/libraries/DisputeTypes.sol",
    39: "contracts/libraries/Encoding.sol",
    40: "contracts/libraries/Hashing.sol",
    41: "contracts/libraries/LegacyCrossDomainUtils.sol",
    42: "contracts/libraries/Predeploys.sol",
    43: "contracts/libraries/Types.sol",
    44: "contracts/libraries/rlp/RLPReader.sol",
    45: "contracts/libraries/rlp/RLPWriter.sol",
    46: "contracts/libraries/trie/MerkleTrie.sol",
    47: "contracts/libraries/trie/SecureMerkleTrie.sol",
    48: "contracts/periphery/AssetReceiver.sol",
    49: "contracts/periphery/Transactor.sol",
    50: "contracts/periphery/drippie/IDripCheck.sol",
    51: "contracts/test/Clones.t.sol",
    52: "contracts/test/LibClock.t.sol",
    53: "contracts/test/LibPosition.t.sol",
    54: "contracts/test/RLP.t.sol",
    55: "contracts/universal/IOptimismMintableERC20.sol",
    56: "contracts/universal/IOptimismMintableERC721.sol",
    57: "contracts/universal/Semver.sol",
    58: "contracts/vendor/AddressAliasHelper.sol",
    59: "node_modules/@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol",
    60: "node_modules/@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol",
    61: "node_modules/@openzeppelin/contracts-upgradeable/utils/AddressUpgradeable.sol",
    62: "node_modules/@openzeppelin/contracts-upgradeable/utils/ContextUpgradeable.sol",
    63: "node_modules/@openzeppelin/contracts/access/Ownable.sol",
    64: "node_modules/@openzeppelin/contracts/token/ERC721/IERC721.sol",
    65: "node_modules/@openzeppelin/contracts/token/ERC721/extensions/IERC721Enumerable.sol",
    66: "node_modules/@openzeppelin/contracts/utils/Context.sol",
    67: "node_modules/@openzeppelin/contracts/utils/Strings.sol",
    68: "node_modules/@openzeppelin/contracts/utils/introspection/IERC165.sol",
    69: "node_modules/@rari-capital/solmate/src/auth/Owned.sol",
    70: "node_modules/@rari-capital/solmate/src/tokens/ERC20.sol",
    71: "node_modules/@rari-capital/solmate/src/tokens/ERC721.sol",
    72: "node_modules/@rari-capital/solmate/src/utils/Bytes32AddressLib.sol",
    73: "node_modules/clones-with-immutable-args/src/ClonesWithImmutableArgs.sol",
    74: "node_modules/ds-test/src/test.sol",
    75: "node_modules/forge-std/src/Base.sol",
    76: "node_modules/forge-std/src/StdAssertions.sol",
    77: "node_modules/forge-std/src/StdChains.sol",
    78: "node_modules/forge-std/src/StdCheats.sol",
    79: "node_modules/forge-std/src/StdError.sol",
    80: "node_modules/forge-std/src/StdInvariant.sol",
    81: "node_modules/forge-std/src/StdJson.sol",
    82: "node_modules/forge-std/src/StdMath.sol",
    83: "node_modules/forge-std/src/StdStorage.sol",
    84: "node_modules/forge-std/src/StdStyle.sol",
    85: "node_modules/forge-std/src/StdUtils.sol",
    86: "node_modules/forge-std/src/Test.sol",
    87: "node_modules/forge-std/src/Vm.sol",
    88: "node_modules/forge-std/src/console.sol",
    89: "node_modules/forge-std/src/console2.sol",
    90: "node_modules/forge-std/src/interfaces/IMulticall3.sol",
}
