[profile.default]
src = "src"
out = "out"
libs = ["../../../op-contracts/lib"]

optimizer = true
optimizer_runs = 999999

remappings = [
  'forge-std/=../../../op-contracts/lib/forge-std/src',
  'safe-contracts/=../../../op-contracts/lib/safe-contracts/contracts',
]
