import '../justfiles/go.just'

# Build ldflags string
_LDFLAGSSTRING := "'" + trim(
    "-X main.GitCommit=" + GITCOMMIT + " " + \
    "-X main.GitDate=" + GITDATE + " " + \
    "-X main.Version=" + VERSION + " " + \
    "") + "'"

BINARY := justfile_directory() + "/bin/da-server"
PACKAGE := justfile_directory() + "/cmd/daserver"

# Build the da-server binary
da-server: (go_build BINARY PACKAGE "-ldflags" _LDFLAGSSTRING)

# Remove build artifacts
clean:
    rm -f {{BINARY}}

# Run tests
test: (go_test "./...")
