import '../justfiles/prerequisites.just'

KURTOSIS_PACKAGE := "./optimism-package-trampoline/"

test: _prerequisites
    go test --tags=testonly ./...

_kurtosis-run PACKAGE_NAME ARG_FILE ENCLAVE:
	kurtosis run {{PACKAGE_NAME}} --args-file {{ARG_FILE}} --enclave {{ENCLAVE}} --show-enclave-inspect=false --image-download=missing

_prestate-build PATH='.':
    docker buildx build --output {{PATH}} --progress plain -f ../op-program/Dockerfile.repro ../

_docker_build TAG TARGET CONTEXT DOCKERFILE *ARGS: _prerequisites
    #!/usr/bin/env bash
    # --load is needed to ensure the image ends up in the local registry
    # --provenance=false is needed to make the build idempotent
    docker buildx build \
        --load \
        --provenance=false \
        -t {{TAG}} \
        -f {{CONTEXT}}/{{DOCKERFILE}} \
        {{ if TARGET != '' {  "--target " + TARGET } else { "" } }} \
        --build-arg GIT_COMMIT={git_commit} \
        --build-arg GIT_DATE={git_date} \
        {{ ARGS }} \
        {{CONTEXT}}

_docker_build_stack TAG TARGET *ARGS: (_docker_build TAG TARGET "../" "ops/docker/op-stack-go/Dockerfile" ARGS)

cannon-image TAG='cannon:devnet': (_docker_build_stack TAG "cannon-target")
da-server-image TAG='da-server:devnet': (_docker_build_stack TAG "da-server-target")
op-batcher-image TAG='op-batcher:devnet': (_docker_build_stack TAG "op-batcher-target")
# TODO: this is a temporary hack to get the kona + asterisc version right.
# Ideally the Dockerfile should be self-sufficient (right now we depend on
# docker-bake.hcl to do the right thing).
op-challenger-image TAG='op-challenger:devnet': (_docker_build_stack TAG "op-challenger-target" "--build-arg" "KONA_VERSION=1.0.1" "--build-arg" "ASTERISC_VERSION=v1.3.0")
op-conductor-image TAG='op-conductor:devnet': (_docker_build_stack TAG "op-conductor-target")
op-deployer-image TAG='op-deployer:devnet': (_docker_build_stack TAG "op-deployer-target")
op-dispute-mon-image TAG='op-dispute-mon:devnet': (_docker_build_stack TAG "op-dispute-mon-target")
op-node-image TAG='op-node:devnet': (_docker_build_stack TAG "op-node-target")
op-program-image TAG='op-program:devnet': (_docker_build_stack TAG "op-program-target")
op-proposer-image TAG='op-proposer:devnet': (_docker_build_stack TAG "op-proposer-target")
op-supervisor-image TAG='op-supervisor:devnet': (_docker_build_stack TAG "op-supervisor-target")
op-wheel-image TAG='op-wheel:devnet': (_docker_build_stack TAG "op-wheel-target")
op-faucet-image TAG='op-faucet:devnet': (_docker_build_stack TAG "op-faucet-target")
op-interop-mon-image TAG='op-interop-mon:devnet': (_docker_build_stack TAG "op-interop-mon-target")

op-program-builder-image TAG='op-program-builder:devnet': _prerequisites
    just op-program-svc/op-program-svc {{TAG}}


# Devnet template recipe
# Note: Make sure that TEMPLATE_FILE is in the kurtosis-devnet/ directory.
#       Cannot use a file from the kurtosis-devnet/templates/ directory for example.
devnet TEMPLATE_FILE DATA_FILE="" NAME="" PACKAGE=KURTOSIS_PACKAGE: _prerequisites
    #!/usr/bin/env bash
    export DEVNET_NAME={{NAME}}
    if [ -z "{{NAME}}" ]; then
        export DEVNET_NAME=`basename {{TEMPLATE_FILE}} .yaml`
        if [ -n "{{DATA_FILE}}" ]; then
            export DATA_FILE_NAME=`basename {{DATA_FILE}} .json`
            export DEVNET_NAME="$DEVNET_NAME-$DATA_FILE_NAME"
        fi
    fi
    export ENCL_NAME="$DEVNET_NAME"-devnet
    go run cmd/main.go -kurtosis-package {{PACKAGE}} \
        -environment "tests/$ENCL_NAME.json" \
        -template "{{TEMPLATE_FILE}}" \
        -data "{{DATA_FILE}}" \
        -enclave "$ENCL_NAME" \
    && cat "tests/$ENCL_NAME.json"

devnet-test DEVNET *TEST: _prerequisites
    #!/usr/bin/env bash
    export TESTS=({{TEST}})
    # we need a timestamp in there to force kurtosis to not cache the test solely based on its name!
    export ARGS=$(printf '%s\n' "${TESTS[@]}" | jq -R . | jq -s . | jq -s '{devnet: "{{DEVNET}}", timestamp: "{{datetime("%s")}}", tests: add}')
    kurtosis run --enclave {{DEVNET}} \
        --show-enclave-inspect=false \
        ./tests/ "$ARGS"

# Devnet recipes

##### These are the main eigenda commands used by CI and automated tests #####

# Start an EigenDA devnet with the given values file (see options in eigenda-template-values/).
# The devnet will be named "eigenda-devnet" by default, but you can override this with the NAME argument.
# We also start a tx-fuzzer separately, since the optimism-package doesn't currently have that configurable as part of its package.
[group('eigenda')]
eigenda-devnet-start VALUES_FILE="eigenda-template-values/memstore-concurrent-large-blobs.json" ENCLAVE_PREFIX="eigenda": (devnet "eigenda.yaml" VALUES_FILE ENCLAVE_PREFIX)
  just eigenda-devnet-add-tx-fuzzer {{ENCLAVE_PREFIX}}-devnet
[group('eigenda')]
eigenda-devnet-clean ENCLAVE_NAME="eigenda-devnet":
    kurtosis enclave rm {{ENCLAVE_NAME}} --force
# Runs all tests that end with the `_Memstore` suffix, assuming the devnet was started with memstore proxy,
# meaning with a config file in eigenda-template-values/memstore-* .
[group('eigenda')]
eigenda-devnet-test-memstore *ARGS="":
    go test ./tests/eigenda/... -run "_Memstore$" -v -timeout 30m {{ARGS}}
# Runs all tests that end with the `_Holesky` suffix, assuming the devnet was started with proxy using holesky backend.
# To start the devnet with holesky backend, the files in eigenda-template-values/holesky-* need have secrets injected.
# Take a look at how CI does it in .github/workflows/kurtosis-devnet.yml .
[group('eigenda')]
eigenda-devnet-test-holesky *ARGS="":
    go test ./tests/eigenda/... -run "_Holesky$" -v -timeout 40m {{ARGS}}
[group('eigenda')]
eigenda-devnet-add-tx-fuzzer ENCLAVE_NAME="eigenda-devnet" *ARGS="":
  kurtosis service add {{ENCLAVE_NAME}} tx-fuzz ethpandaops/tx-fuzz:master -- \
    spam \
    --sk "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" \
    --rpc "http://op-el-1-op-geth-op-node-op-kurtosis:8545" \
    --slot-time 2 \
    --accounts 100 --txcount 1 \
    {{ARGS}}

##### EigenDA Commands below are for debugging and manual testing #####

# Cause proxy to start returning 503 errors to batcher, as a signal
# to failover to ethDA. Use `eigenda-devnet-failback` to revert.
[group('eigenda')]
eigenda-devnet-failover ENCLAVE_NAME="eigenda-devnet":
  #!/usr/bin/env bash
  PROXY_ENDPOINT=$(kurtosis port print {{ENCLAVE_NAME}} da-server-op-kurtosis http)
  curl -X PATCH $PROXY_ENDPOINT/memstore/config -d '{"PutReturnsFailoverError": true}'
[group('eigenda')]
eigenda-devnet-failback ENCLAVE_NAME="eigenda-devnet":
  #!/usr/bin/env bash
  PROXY_ENDPOINT=$(kurtosis port print {{ENCLAVE_NAME}} da-server-op-kurtosis http)
  curl -X PATCH $PROXY_ENDPOINT/memstore/config -d '{"PutReturnsFailoverError": false}'
[group('eigenda')]
eigenda-devnet-grafana ENCLAVE_NAME="eigenda-devnet":
  #!/usr/bin/env bash
  GRAFANA_URL=$(kurtosis port print {{ENCLAVE_NAME}} grafana http)
  open $GRAFANA_URL
[group('eigenda')]
eigenda-devnet-sync-status ENCLAVE_NAME="eigenda-devnet":
  #!/usr/bin/env bash
  OPNODE_ENDPOINT=$(kurtosis port print {{ENCLAVE_NAME}} op-cl-1-op-node-op-geth-op-kurtosis http)
  cast rpc optimism_syncStatus --rpc-url $OPNODE_ENDPOINT | jq
[group('eigenda')]
eigenda-devnet-configs ENCLAVE_NAME="eigenda-devnet":
  #!/usr/bin/env bash
  echo "OP-NODE ROLLUP CONFIG:"
  OPNODE_ENDPOINT=$(kurtosis port print {{ENCLAVE_NAME}} op-cl-1-op-node-op-geth-op-kurtosis http)
  cast rpc optimism_rollupConfig --rpc-url $OPNODE_ENDPOINT | jq
  echo "TEKU L1-CL SPEC:"
  TEKU_ENDPOINT=$(kurtosis port print {{ENCLAVE_NAME}} cl-1-teku-geth http)
  curl $TEKU_ENDPOINT/eth/v1/config/spec | jq
  echo "PROXY MEMSTORE CONFIG:"
  PROXY_ENDPOINT=$(kurtosis port print {{ENCLAVE_NAME}} da-server-op-kurtosis http)
  curl $PROXY_ENDPOINT/memstore/config | jq
  curl $PROXY_ENDPOINT/admin/eigenda-dispersal-backend | jq
[group('eigenda')]
eigenda-devnet-change-proxy-backend backend="V1" ENCLAVE_NAME="eigenda-devnet":
  #!/usr/bin/env bash
  PROXY_ENDPOINT=$(kurtosis port print {{ENCLAVE_NAME}} da-server-op-kurtosis http)
  curl -X PUT $PROXY_ENDPOINT/admin/eigenda-dispersal-backend \
    -H "Content-Type: application/json" \
    -d '{"eigenDADispersalBackend": "{{backend}}"}'
# We unfortunately have to restart the batcher in this ugly way right now just to change even a single flag.
# This is b/c op's kurtosis setup right now is not idempotent so if we change a param in a values file
# and rerun `just eigenda-devnet-start`, the entire devnet gets respun up which takes a long time.
# Track progress for fixing this in https://github.com/ethereum-optimism/optimism/issues/14390.
# Kurtosis also doesn't have a simple way to update a running service's config, like `kubectl edit` for k8s.
# See https://github.com/kurtosis-tech/kurtosis/issues/2628 for this issue.
# Restart batcher with new flags or image.
[group('eigenda')]
eigenda-devnet-restart-batcher ENCLAVE_NAME="eigenda-devnet":
  #!/usr/bin/env bash
  # IMAGE=op-batcher:{{ENCLAVE_NAME}}
  IMAGE=us-docker.pkg.dev/oplabs-tools-artifacts/images/op-batcher:v1.10.0
  kurtosis service add {{ENCLAVE_NAME}} op-batcher-op-kurtosis \
    $IMAGE \
    --ports "http=8548,metrics=9001" \
    -- op-batcher \
      --l2-eth-rpc=http://op-el-1-op-geth-op-node-op-kurtosis:8545 \
      --rollup-rpc=http://op-cl-1-op-node-op-geth-op-kurtosis:8547 \
      --poll-interval=1s \
      --sub-safety-margin=6 \
      --num-confirmations=1 \
      --safe-abort-nonce-too-low-count=3 \
      --resubmission-timeout=30s \
      --rpc.addr=0.0.0.0 \
      --rpc.port=8548 \
      --rpc.enable-admin \
      --metrics.enabled \
      --metrics.addr=0.0.0.0 \
      --metrics.port=9001 \
      --l1-eth-rpc=http://el-1-geth-teku:8545 \
      --private-key=0xb3d2d558e3491a3709b7c451100a0366b5872520c7aa020c17a0e7fa35b6a8df \
      --data-availability-type=calldata \
      --altda.enabled=True \
      --altda.da-server=http://da-server-op-kurtosis:3100 \
      --altda.da-service \
      --altda.max-concurrent-da-requests=100 \
      --max-pending-tx=100 \
      --max-channel-duration=10 \
      --target-num-frames=10 \
      --max-l1-tx-size-bytes=1000 \
      --batch-type=1 \
      --throttle-threshold=500_000 \
      --throttle-block-size=1000


# Simple devnet
simple-devnet: (devnet "simple.yaml")

# Interop devnet
interop-devnet: (devnet "interop.yaml")
interop-devnet-test: (devnet-test "interop-devnet" "interop-smoke-test.sh")

# User devnet
user-devnet DATA_FILE:
    {{just_executable()}} devnet "user.yaml" {{DATA_FILE}} {{file_stem(DATA_FILE)}}

# Pectra devnet
pectra-devnet: (devnet "pectra.yaml")

# Isthmus devnet
isthmus-devnet: (devnet "isthmus.yaml")

# Flashblocks devnet
flash-devnet: (devnet "flash.yaml")

# subshells
enter-devnet DEVNET CHAIN='Ethereum' NODE_INDEX='0': _prerequisites
    go run ../devnet-sdk/shell/cmd/enter/main.go --devnet kt://{{DEVNET}} --chain {{CHAIN}} --node-index {{NODE_INDEX}}
