version: '3.4'

volumes:
  l1_data:
  da_data:

networks:
  ops-network:
    name: ops-bedrock-shared
    external: true

services:
  l1:
    build:
      context: .
      dockerfile: Dockerfile.l1
    ports:
      - "8545:8545"
      - "8546:8546"
      - "7060:6060"
    volumes:
      - "l1_data:/db"
      - "${PWD}/../.devnet/genesis-l1.json:/genesis.json"
      - "${PWD}/test-jwt-secret.txt:/config/test-jwt-secret.txt"
    environment:
      GETH_MINER_RECOMMIT: 100ms
    networks:
      - ops-network

  da-server:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/da-server:devnet
    build:
      context: ../
      dockerfile: ops/docker/op-stack-go/Dockerfile
      target: da-server-target
    command: >
      da-server
      --file.path=/data
      --addr=0.0.0.0
      --port=3100
      --log.level=debug
    ports:
      - "3100:3100"
    volumes:
      - "da_data:/data"
    networks:
      - ops-network

  artifact-server:
    depends_on:
      - l1
    image: nginx:1.25-alpine
    ports:
      - "8080:80"
    volumes:
      - "${PWD}/../.devnet/:/usr/share/nginx/html/:ro"
    security_opt:
      - "no-new-privileges:true"
    networks:
      - ops-network
