FROM golang:1.18.0-alpine3.15 as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git jq bash

COPY ./op-node/go.mod /app/go.mod
COPY ./op-node/go.sum /app/go.sum

WORKDIR /app
RUN go mod download -x

COPY ./op-node /app

RUN go build -o ./bin/stateviz ./cmd/stateviz

FROM alpine:3.15

COPY --from=builder /app/bin/stateviz /usr/local/bin

CMD ["stateviz"]
