# exclude everything by default to limit context size and cache miss
*
# module definition
!go.*
# internal dependencies
!cannon/
!op-alt-da/
!op-node/
!op-preimage/
!op-program/
!op-service/
!op-supervisor/

**/bin
**/testdata
**/tests