ARG OP_STACK_GO_BUILDER=us-docker.pkg.dev/oplabs-tools-artifacts/images/op-stack-go:latest
FROM $OP_STACK_GO_BUILDER as builder

# FROM alpine:3.18

COPY --from=builder /usr/local/bin/op-program /usr/local/bin/op-program

CMD ["op-program"]
