# Runs e2e tests using the testsuite framework

name: e2e

on:
  pull_request:
  merge_group:
  push:
    branches: [unstable, main]

env:
  CARGO_TERM_COLOR: always
  SEED: rustethereumethereumrust
  RUSTC_WRAPPER: "sccache"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: e2e-testsuite
    runs-on: depot-ubuntu-latest-4
    env:
      RUST_BACKTRACE: 1
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Run e2e tests
        run: |
          cargo nextest run \
            --locked --features "asm-keccak" \
            --workspace \
            --exclude 'example-*' \
            --exclude 'exex-subscription' \
            --exclude 'reth-bench' \
            --exclude 'ef-tests' \
            --exclude 'op-reth' \
            --exclude 'reth' \
            -E 'binary(e2e_testsuite)'
