# default recipe to display help information
default:
  @just --list

# Check for unused dependencies in the crate graph.
check-udeps:
  cargo +nightly udeps --workspace --lib --examples --tests --benches --all-features --locked

# Run unit tests with optional edge storage feature
test edge='':
  #!/usr/bin/env bash
  set -euo pipefail
  RUST_BACKTRACE=1 cargo nextest run \
    --features "asm-keccak {{edge}}" --locked \
    --workspace \
    --no-tests=warn \
    -E "!kind(test) and not binary(e2e_testsuite)"

# Run integration tests for reth-optimism-node
test-integration:
  RUST_BACKTRACE=1 cargo nextest run --locked -p reth-optimism-node
