// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	context "context"
	big "math/big"

	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// L2ConfigProvider is an autogenerated mock type for the L2ConfigProvider type
type L2ConfigProvider struct {
	mock.Mock
}

// BlockByNumber provides a mock function with given fields: ctx, number
func (_m *L2ConfigProvider) BlockByNumber(ctx context.Context, number *big.Int) (*types.Block, error) {
	ret := _m.Called(ctx, number)

	var r0 *types.Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *big.Int) (*types.Block, error)); ok {
		return rf(ctx, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *big.Int) *types.Block); ok {
		r0 = rf(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Block)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *big.Int) error); ok {
		r1 = rf(ctx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewL2ConfigProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewL2ConfigProvider creates a new instance of L2ConfigProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewL2ConfigProvider(t mockConstructorTestingTNewL2ConfigProvider) *L2ConfigProvider {
	mock := &L2ConfigProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
