//! Contract bindings for the super-root ZK dispute game.
//!
//! Interface bindings are generated by `sol!` directly from the
//! contracts-bedrock ABI snapshots, so they cannot drift from the deployed
//! contract surface (the snapshots are CI-gated against the contracts).
//! Enums are hand-written: Solidity enums are `uint8` in the ABI, so their
//! discriminants are pinned here (and by unit tests) against the contract
//! sources instead:
//! - `packages/contracts-bedrock/src/dispute/zk/ZKDisputeGame.sol` (`ProposalStatus`)
//! - `packages/contracts-bedrock/src/dispute/lib/Types.sol` (`GameStatus`)

use alloy_primitives::U256;
use alloy_sol_types::sol;
use anyhow::{Error, anyhow};
use serde::{Deserialize, Serialize};

sol!(
    #[allow(missing_docs)]
    #[derive(Debug, PartialEq, Eq)]
    #[sol(rpc)]
    DisputeGameFactory,
    "../../../../../packages/contracts-bedrock/snapshots/abi/DisputeGameFactory.json"
);

sol!(
    #[allow(missing_docs)]
    #[derive(Debug, PartialEq, Eq)]
    #[sol(rpc)]
    ZKDisputeGame,
    "../../../../../packages/contracts-bedrock/snapshots/abi/ZKDisputeGame.json"
);

sol!(
    #[allow(missing_docs)]
    #[derive(Debug, PartialEq, Eq)]
    #[sol(rpc)]
    AnchorStateRegistry,
    "../../../../../packages/contracts-bedrock/snapshots/abi/AnchorStateRegistry.json"
);

sol!(
    #[allow(missing_docs)]
    #[derive(Debug, PartialEq, Eq)]
    #[sol(rpc)]
    DelayedWETH,
    "../../../../../packages/contracts-bedrock/snapshots/abi/DelayedWETH.json"
);

/// Proposal lifecycle status, mirroring ZKDisputeGame.sol `ProposalStatus`.
/// Hand-written: enums are `uint8` in the ABI, so the variant order is pinned
/// against the contract source (and by `proposal_status_values_match_zk_dispute_game_sol`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(u8)]
pub enum ProposalStatus {
    /// No challenge has been made against the proposal.
    Unchallenged = 0,
    /// The proposal has been challenged but no validity proof has been provided.
    Challenged = 1,
    /// A valid proof was provided without the proposal ever being challenged.
    UnchallengedAndValidProofProvided = 2,
    /// The proposal was challenged and then a valid proof was provided.
    ChallengedAndValidProofProvided = 3,
    /// The proposal has been resolved and can no longer transition.
    Resolved = 4,
}

impl TryFrom<u8> for ProposalStatus {
    type Error = Error;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::Unchallenged),
            1 => Ok(Self::Challenged),
            2 => Ok(Self::UnchallengedAndValidProofProvided),
            3 => Ok(Self::ChallengedAndValidProofProvided),
            4 => Ok(Self::Resolved),
            _ => Err(anyhow!("invalid proposal status: {value}")),
        }
    }
}

/// Game resolution status, mirroring
/// `packages/contracts-bedrock/src/dispute/lib/Types.sol` `GameStatus`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(u8)]
pub enum GameStatus {
    /// The game is in progress and awaiting resolution.
    InProgress = 0,
    /// The game resolved in favor of the challenger; the root claim was invalid.
    ChallengerWins = 1,
    /// The game resolved in favor of the defender; the root claim was valid.
    DefenderWins = 2,
}

impl TryFrom<u8> for GameStatus {
    type Error = Error;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::InProgress),
            1 => Ok(Self::ChallengerWins),
            2 => Ok(Self::DefenderWins),
            _ => Err(anyhow!("invalid game status: {value}")),
        }
    }
}

/// Decoded ZK game args (140-byte packed layout from `LibGameArgs.sol`;
/// mirrors `op-challenger/game/fault/contracts/gameargs` `ZKGameArgs`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ZKGameArgs {
    /// Absolute prestate hash committing to the ZK program being verified.
    pub absolute_prestate: alloy_primitives::B256,
    /// Address of the on-chain proof verifier contract.
    pub verifier: alloy_primitives::Address,
    /// Maximum duration, in seconds, during which the proposal may be challenged.
    pub max_challenge_duration: u64,
    /// Maximum duration, in seconds, allowed to supply a proof after a challenge.
    pub max_prove_duration: u64,
    /// Bond, in wei, a challenger must post to challenge the proposal.
    pub challenger_bond: U256,
    /// Address of the `AnchorStateRegistry` tracking the anchor game.
    pub anchor_state_registry: alloy_primitives::Address,
    /// Address of the `DelayedWETH` contract holding game bonds.
    pub weth: alloy_primitives::Address,
}

/// Exact length of the packed ZK game args blob.
pub const ZK_GAME_ARGS_LENGTH: usize = 140;

impl ZKGameArgs {
    /// Decodes the packed layout: absolutePrestate(32) || verifier(20) ||
    /// maxChallengeDuration(8) || maxProveDuration(8) || challengerBond(32)
    /// || anchorStateRegistry(20) || weth(20).
    pub fn decode(args: &[u8]) -> Result<Self, Error> {
        if args.len() != ZK_GAME_ARGS_LENGTH {
            return Err(anyhow!("invalid ZK game args length: {}", args.len()));
        }
        Ok(Self {
            absolute_prestate: alloy_primitives::B256::from_slice(&args[0..32]),
            verifier: alloy_primitives::Address::from_slice(&args[32..52]),
            max_challenge_duration: u64::from_be_bytes(args[52..60].try_into().unwrap()),
            max_prove_duration: u64::from_be_bytes(args[60..68].try_into().unwrap()),
            challenger_bond: U256::from_be_slice(&args[68..100]),
            anchor_state_registry: alloy_primitives::Address::from_slice(&args[100..120]),
            weth: alloy_primitives::Address::from_slice(&args[120..140]),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloy_primitives::{address, b256};

    /// Pins the enum numeric values to Types.sol / ZKDisputeGame.sol.
    #[test]
    fn game_status_values_match_types_sol() {
        assert_eq!(GameStatus::InProgress as u8, 0);
        assert_eq!(GameStatus::ChallengerWins as u8, 1);
        assert_eq!(GameStatus::DefenderWins as u8, 2);
        assert!(GameStatus::try_from(3).is_err());
    }

    #[test]
    fn proposal_status_values_match_zk_dispute_game_sol() {
        assert_eq!(ProposalStatus::Unchallenged as u8, 0);
        assert_eq!(ProposalStatus::Challenged as u8, 1);
        assert_eq!(ProposalStatus::UnchallengedAndValidProofProvided as u8, 2);
        assert_eq!(ProposalStatus::ChallengedAndValidProofProvided as u8, 3);
        assert_eq!(ProposalStatus::Resolved as u8, 4);
    }

    /// Same test vectors as Go's `TestZKGameArgsPack`
    /// (op-challenger/game/fault/contracts/gameargs).
    #[test]
    fn zk_game_args_decode() {
        let prestate = b256!("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
        let verifier = address!("1111111111111111111111111111111111111111");
        let asr = address!("2222222222222222222222222222222222222222");
        let weth = address!("3333333333333333333333333333333333333333");
        let bond = U256::from(10).pow(U256::from(18));

        let mut packed = Vec::with_capacity(ZK_GAME_ARGS_LENGTH);
        packed.extend_from_slice(prestate.as_slice());
        packed.extend_from_slice(verifier.as_slice());
        packed.extend_from_slice(&3600u64.to_be_bytes());
        packed.extend_from_slice(&7200u64.to_be_bytes());
        packed.extend_from_slice(&bond.to_be_bytes::<32>());
        packed.extend_from_slice(asr.as_slice());
        packed.extend_from_slice(weth.as_slice());

        let decoded = ZKGameArgs::decode(&packed).unwrap();
        assert_eq!(
            decoded,
            ZKGameArgs {
                absolute_prestate: prestate,
                verifier,
                max_challenge_duration: 3600,
                max_prove_duration: 7200,
                challenger_bond: bond,
                anchor_state_registry: asr,
                weth,
            }
        );

        assert!(ZKGameArgs::decode(&packed[..139]).is_err());
        assert!(ZKGameArgs::decode(&[]).is_err());
    }
}
