allowBuilds:
  '@reown/appkit': set this to true or false
  bigint-buffer: set this to true or false
  bufferutil: set this to true or false
  esbuild: set this to true or false
  sharp: set this to true or false
  utf-8-validate: set this to true or false
