op-program-base:
    docker buildx build -f ../../op-program/Dockerfile.repro --target=src -t op-program-base:latest ../..

op-program-svc: op-program-base
    docker buildx build -f Dockerfile -t op-program-svc:latest .
