// SPDX-License-Identifier: MIT
// This file was autogenerated by running `kontrol load-state`. Do not edit this file manually.

pragma solidity ^0.8.13;

// Will be generated by Kontrol
contract DeploymentSummaryFaultProofsCode { }
