set positional-arguments

# Run rollup-boost tests
test *args='':
  cargo nextest run -p rollup-boost -p rollup-boost-types -p flashblocks-websocket-proxy {{args}}

# Build rollup-boost binary (release)
build-release:
  cargo build --release --bin rollup-boost

# Build docker image
build-docker:
  docker buildx build --build-arg RELEASE=true -t flashbots/rollup-boost:develop .

# Build docker debug image
build-docker-debug:
  docker buildx build --build-arg RELEASE=false -t flashbots/rollup-boost:develop .
