version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      day: "tuesday"
      time: "14:30"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "dependabot(gomod): "
    labels:
      - "M-dependabot"

  # Kona - Rust/Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/kona"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "dependabot(cargo): "
    labels:
      - "M-dependabot"
      - "F-deps"
    ignore:
      - dependency-name: "*"
        # patch and minor updates don't matter for libraries
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
