build:
  go build -o bin/op-fetcher cmd/main.go

build-go: build
build-all: build-contracts build-go

build-contracts:
  #!/bin/bash
  mkdir -p ./pkg/fetcher/fetch/forge-artifacts
  cd ../packages/contracts-bedrock
  just clean
  just build-dev --deny-warnings --skip test
  cp -r forge-artifacts/FetchChainInfo.s.sol ../../op-fetcher/pkg/fetcher/fetch/forge-artifacts
