#!/usr/bin/env bash
# Recompile UndeliveredMessageExporter with the repository's DEFAULT foundry profile, validate the
# artifact (compiler version, full settings, init-code hash vs snapshots/semver-lock.json) BEFORE
# replacing anything, then record it and regenerate the Lean bytecode (ExporterEvm/Bytecode.lean),
# the EquiVM block summaries (ExporterEvm/Blocks/) and their import point
# (ExporterEvm/AllBlocks.lean). Adapted from ../evm-lean-bridge/scripts/regen.sh. Needs forge, jq,
# cast, python3, and `lake build` (or `lake update`) done once so that .lake/packages/EquiVM
# exists. Then run `lake build`.
set -euo pipefail
HERE=$(cd "$(dirname "$0")/.." && pwd)
CB=$(cd "$HERE/../../../.." && pwd)            # packages/contracts-bedrock
NAME=UndeliveredMessageExporter
EXPECT_SOLC="0.8.15+commit.e14f2714"
# All compiler settings except remappings/target, keys sorted (solc 0.8.15 caps evmVersion at
# london, which the default profile's `cancun` resolves to for this file).
EXPECT_SETTINGS='{"evmVersion":"london","libraries":{},"metadata":{"bytecodeHash":"none"},"optimizer":{"enabled":true,"runs":999999}}'

# Use the default profile only; drop any environment overrides of compiler settings.
while IFS= read -r v; do unset "$v"; done < <(env | grep -o '^FOUNDRY_[A-Z_]*' || true)
export FOUNDRY_PROFILE=default
echo "forge: $(forge --version | head -1)"
echo "commit: $(git -C "$CB" rev-parse HEAD)"

OUT=$(mktemp -d)
(cd "$CB" && forge build "src/L2/$NAME.sol" --out "$OUT" > /dev/null)
A="$OUT/$NAME.sol/$NAME.json"
SOLC=$(jq -r .metadata.compiler.version "$A")
SETTINGS=$(jq -cS '.metadata.settings | del(.remappings, .compilationTarget)' "$A")
INIT=$(cast keccak "$(jq -r .bytecode.object "$A")")
LOCK=$(jq -r ".\"src/L2/$NAME.sol:$NAME\".initCodeHash" "$CB/snapshots/semver-lock.json")
echo "solc:             $SOLC"
echo "settings:         $SETTINGS"
echo "keccak(initcode): $INIT"
echo "semver-lock:      $LOCK"
[ "$SOLC" = "$EXPECT_SOLC" ] || { echo "unexpected solc $SOLC"; exit 1; }
[ "$SETTINGS" = "$EXPECT_SETTINGS" ] || { echo "unexpected settings $SETTINGS"; exit 1; }
[ "$INIT" = "$LOCK" ] || { echo "init-code hash differs from semver-lock.json"; exit 1; }
# The contract has no immutables, so the deployed code is forge's deployedBytecode verbatim.
[ "$(jq -c '.deployedBytecode.immutableReferences // {}' "$A")" = "{}" ] \
  || { echo "unexpected immutables"; exit 1; }

# Stage the artifact in the temp dir and validate it there; only then replace tracked files.
jq -r .deployedBytecode.object "$A" > "$OUT/$NAME.runtime.hex"
echo "keccak(runtime):  $(cast keccak "$(cat "$OUT/$NAME.runtime.hex")")"
python3 - "$OUT/$NAME.runtime.hex" <<'PY'
import sys
rt = bytes.fromhex(open(sys.argv[1]).read().strip()[2:])
print(f"runtime: {len(rt)} bytes")
# The proof refers to these operands by pc; a layout change must be noticed here, not in Lean.
checks = {
    0x21: bytes.fromhex("63186e7328"),                                  # PUSH4 exportUndeliveredMessage
    0xf4: bytes.fromhex("7fb1b1b209") + bytes(28),                      # successfulMessages(bytes32)
    0x121: bytes.fromhex("73") + bytes.fromhex("42" + "00" * 18 + "23"),  # L2ToL2CrossDomainMessenger
    0x189: bytes.fromhex("7fccc3f3b0") + bytes(28),                     # MessageRelayed() selector
    0x1c8: bytes.fromhex("73") + bytes.fromhex("42" + "00" * 18 + "07"),  # L2CrossDomainMessenger
    0x1de: bytes.fromhex("633dbb202b"),                                 # sendMessage selector
    0x23b: bytes.fromhex("7f372293c3") + bytes(28),                     # relayUndeliveredMessage
    0x2f2: bytes.fromhex("7f1f8c424adc6dfc9721173830dfcfcc32cfa4495584f4e8eda281baddc12bfc6d"),  # event topic
}
ok = all(rt[pc:pc + len(b)] == b for pc, b in checks.items())
print("operand layout:", "ok" if ok else "CHANGED")
sys.exit(0 if ok else 1)
PY
mkdir -p "$HERE/bytecode"
cp "$OUT/$NAME.runtime.hex" "$HERE/bytecode/"
rm -rf "$OUT"

cd "$HERE"
python3 scripts/gen_bytecode.py "bytecode/$NAME.runtime.hex" ExporterEvm/Bytecode.lean exporterRuntime
rm -rf ExporterEvm/Blocks && mkdir -p ExporterEvm/Blocks
python3 .lake/packages/EquiVM/scripts/generate_rd_blocks.py "bytecode/$NAME.runtime.hex" \
  --name exporter --code-term ExporterEvm.exporterRuntime --bytecode-import ExporterEvm.Bytecode \
  --output ExporterEvm/Blocks/RuntimeBlocks.lean --shard-size 20 > /dev/null
perl -pi -e "s/native_decide/evm_kdecide/g" ExporterEvm/Blocks/RuntimeBlocks_*.lean  # kernel-checked
# One import point for all shards.
{ echo "-- Generated by scripts/regen.sh: imports every block-summary shard."
  for f in ExporterEvm/Blocks/RuntimeBlocks_*.lean; do m=${f%.lean}; echo "import ${m//\//.}"; done
} > ExporterEvm/AllBlocks.lean
echo "now run: lake build"
echo "If the pcs moved, update the block names in ExporterEvm/Trace*.lean."
