import '../justfiles/go.just'

BIN := "bin/op-golangci-lint"

# Build the custom linter
build:
    mkdir -p bin
    golangci-lint custom -v

# Run tests
test: (go_test "./...")

# Clean build artifacts
clean:
    rm -rf bin
