[package]
name = "op-integration-tests"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]

