package circleci

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
	"time"

	"github.com/ethereum-optimism/optimism/ops/shadow-ci/pkg/model"
)

// Renderer converts TestPlans into CircleCI continuation YAML.
type Renderer struct {
	runners map[string]string // abstract → CircleCI resource class
}

// NewRenderer creates a new CircleCI YAML renderer.
func NewRenderer(runners map[string]string) *Renderer {
	return &Renderer{runners: runners}
}

// Render produces CircleCI YAML from a TestPlan.
func (r *Renderer) Render(plan model.TestPlan) ([]byte, error) {
	data := templateData{
		Plan: plan,
		Jobs: make([]templateJob, 0, len(plan.Jobs)),
	}

	for _, job := range plan.Jobs {
		tj := templateJob{
			Name:        fmt.Sprintf("shadow-%s", job.Name),
			Runner:      r.mapRunner(job.Resources.Runner),
			Parallelism: job.Resources.Parallelism,
			Timeout:     formatTimeout(job.Resources.Timeout),
			Language:    job.Language,
			Targets:     targetIDs(job.Targets),
			Config:      job.Configurations[0].Name,
			Env:         mergeEnv(job.Configurations),
			Reason:      job.SelectionReason,
		}
		data.Jobs = append(data.Jobs, tj)
	}

	// Comparison job depends on all test jobs.
	data.ComparisonDeps = make([]string, len(data.Jobs))
	for i, j := range data.Jobs {
		data.ComparisonDeps[i] = j.Name
	}

	tmpl, err := template.New("workflow").Parse(workflowTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("executing template: %w", err)
	}

	return buf.Bytes(), nil
}

func (r *Renderer) mapRunner(abstract string) string {
	if mapped, ok := r.runners[abstract]; ok {
		return mapped
	}
	return "docker+large" // default fallback
}

type templateData struct {
	Plan           model.TestPlan
	Jobs           []templateJob
	ComparisonDeps []string
}

type templateJob struct {
	Name        string
	Runner      string
	Parallelism int
	Timeout     string
	Language    string
	Targets     string
	Config      string
	Env         map[string]string
	Reason      string
}

func targetIDs(targets []model.Target) string {
	ids := make([]string, len(targets))
	for i, t := range targets {
		ids[i] = t.ID
	}
	return strings.Join(ids, ",")
}

func mergeEnv(configs []model.Configuration) map[string]string {
	env := make(map[string]string)
	for _, c := range configs {
		for k, v := range c.Env {
			env[k] = v
		}
	}
	return env
}

func formatTimeout(d time.Duration) string {
	return fmt.Sprintf("%dm", int(d.Minutes()))
}

var workflowTemplate = `# Auto-generated by shadow-ci render. Do not edit.
# Plan: {{ .Plan.ID }}
# Created: {{ .Plan.CreatedAt.Format "2006-01-02T15:04:05Z" }}
# Trigger: {{ .Plan.Trigger.Type }} branch={{ .Plan.Trigger.Branch }}

version: 2.1

jobs:
{{- range .Jobs }}
  {{ .Name }}:
    machine:
      image: default
    resource_class: {{ .Runner }}
    parallelism: {{ .Parallelism }}
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run {{ .Language }} tests ({{ .Config }})
          no_output_timeout: {{ .Timeout }}
          command: |
            ops/shadow-ci/bin/runner \
              --language={{ .Language }} \
              --targets="{{ .Targets }}" \
              --config="{{ .Config }}" \
              --reason="{{ .Reason }}"
{{- range $k, $v := .Env }}
          environment:
            {{ $k }}: "{{ $v }}"
{{- end }}
      - store_artifacts:
          path: /tmp/shadow-ci-results
      - store_test_results:
          path: /tmp/shadow-ci-results
{{ end }}
  shadow-comparison:
    docker:
      - image: cimg/base:2026.03
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Compare shadow vs main CI
          command: |
            ops/shadow-ci/bin/compare \
              --pipeline-id="${CIRCLE_PIPELINE_ID}" \
              --plan-id="{{ .Plan.ID }}"
      - store_artifacts:
          path: /tmp/shadow-ci-comparison

workflows:
  shadow-ci:
    jobs:
{{- range .Jobs }}
      - {{ .Name }}
{{- end }}
      - shadow-comparison:
          requires:
{{- range .ComparisonDeps }}
            - {{ . }}
{{- end }}
`
