/* eslint-disable @typescript-eslint/no-var-requires, no-empty */
/*
  THIS FILE IS AUTOMATICALLY GENERATED.
  DO NOT EDIT.
  */

let ovm__iL1ChugSplashDeployer
try {
  ovm__iL1ChugSplashDeployer = require('../artifacts-ovm/contracts/chugsplash/interfaces/iL1ChugSplashDeployer.sol/iL1ChugSplashDeployer.json')
} catch {}

let ovm__L1ChugSplashProxy
try {
  ovm__L1ChugSplashProxy = require('../artifacts-ovm/contracts/chugsplash/L1ChugSplashProxy.sol/L1ChugSplashProxy.json')
} catch {}

let ovm__iOVM_CrossDomainMessenger
try {
  ovm__iOVM_CrossDomainMessenger = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/bridge/messaging/iOVM_CrossDomainMessenger.sol/iOVM_CrossDomainMessenger.json')
} catch {}

let ovm__iOVM_L1CrossDomainMessenger
try {
  ovm__iOVM_L1CrossDomainMessenger = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/bridge/messaging/iOVM_L1CrossDomainMessenger.sol/iOVM_L1CrossDomainMessenger.json')
} catch {}

let ovm__iOVM_L1MultiMessageRelayer
try {
  ovm__iOVM_L1MultiMessageRelayer = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/bridge/messaging/iOVM_L1MultiMessageRelayer.sol/iOVM_L1MultiMessageRelayer.json')
} catch {}

let ovm__iOVM_L2CrossDomainMessenger
try {
  ovm__iOVM_L2CrossDomainMessenger = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/bridge/messaging/iOVM_L2CrossDomainMessenger.sol/iOVM_L2CrossDomainMessenger.json')
} catch {}

let ovm__iOVM_L1ERC20Bridge
try {
  ovm__iOVM_L1ERC20Bridge = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/bridge/tokens/iOVM_L1ERC20Bridge.sol/iOVM_L1ERC20Bridge.json')
} catch {}

let ovm__iOVM_L1StandardBridge
try {
  ovm__iOVM_L1StandardBridge = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/bridge/tokens/iOVM_L1StandardBridge.sol/iOVM_L1StandardBridge.json')
} catch {}

let ovm__iOVM_L2ERC20Bridge
try {
  ovm__iOVM_L2ERC20Bridge = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/bridge/tokens/iOVM_L2ERC20Bridge.sol/iOVM_L2ERC20Bridge.json')
} catch {}

let ovm__iOVM_CanonicalTransactionChain
try {
  ovm__iOVM_CanonicalTransactionChain = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/chain/iOVM_CanonicalTransactionChain.sol/iOVM_CanonicalTransactionChain.json')
} catch {}

let ovm__iOVM_ChainStorageContainer
try {
  ovm__iOVM_ChainStorageContainer = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/chain/iOVM_ChainStorageContainer.sol/iOVM_ChainStorageContainer.json')
} catch {}

let ovm__iOVM_StateCommitmentChain
try {
  ovm__iOVM_StateCommitmentChain = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/chain/iOVM_StateCommitmentChain.sol/iOVM_StateCommitmentChain.json')
} catch {}

let ovm__iOVM_ExecutionManager
try {
  ovm__iOVM_ExecutionManager = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/execution/iOVM_ExecutionManager.sol/iOVM_ExecutionManager.json')
} catch {}

let ovm__iOVM_SafetyChecker
try {
  ovm__iOVM_SafetyChecker = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/execution/iOVM_SafetyChecker.sol/iOVM_SafetyChecker.json')
} catch {}

let ovm__iOVM_StateManager
try {
  ovm__iOVM_StateManager = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/execution/iOVM_StateManager.sol/iOVM_StateManager.json')
} catch {}

let ovm__iOVM_StateManagerFactory
try {
  ovm__iOVM_StateManagerFactory = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/execution/iOVM_StateManagerFactory.sol/iOVM_StateManagerFactory.json')
} catch {}

let ovm__iOVM_DeployerWhitelist
try {
  ovm__iOVM_DeployerWhitelist = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/predeploys/iOVM_DeployerWhitelist.sol/iOVM_DeployerWhitelist.json')
} catch {}

let ovm__iOVM_ECDSAContractAccount
try {
  ovm__iOVM_ECDSAContractAccount = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/predeploys/iOVM_ECDSAContractAccount.sol/iOVM_ECDSAContractAccount.json')
} catch {}

let ovm__iOVM_L1MessageSender
try {
  ovm__iOVM_L1MessageSender = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/predeploys/iOVM_L1MessageSender.sol/iOVM_L1MessageSender.json')
} catch {}

let ovm__iOVM_L2ToL1MessagePasser
try {
  ovm__iOVM_L2ToL1MessagePasser = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/predeploys/iOVM_L2ToL1MessagePasser.sol/iOVM_L2ToL1MessagePasser.json')
} catch {}

let ovm__ERC20
try {
  ovm__ERC20 = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/verification/iOVM_BondManager.sol/ERC20.json')
} catch {}

let ovm__Errors
try {
  ovm__Errors = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/verification/iOVM_BondManager.sol/Errors.json')
} catch {}

let ovm__iOVM_BondManager
try {
  ovm__iOVM_BondManager = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/verification/iOVM_BondManager.sol/iOVM_BondManager.json')
} catch {}

let ovm__iOVM_FraudVerifier
try {
  ovm__iOVM_FraudVerifier = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/verification/iOVM_FraudVerifier.sol/iOVM_FraudVerifier.json')
} catch {}

let ovm__iOVM_StateTransitioner
try {
  ovm__iOVM_StateTransitioner = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/verification/iOVM_StateTransitioner.sol/iOVM_StateTransitioner.json')
} catch {}

let ovm__iOVM_StateTransitionerFactory
try {
  ovm__iOVM_StateTransitionerFactory = require('../artifacts-ovm/contracts/optimistic-ethereum/iOVM/verification/iOVM_StateTransitionerFactory.sol/iOVM_StateTransitionerFactory.json')
} catch {}

let ovm__Lib_CrossDomainUtils
try {
  ovm__Lib_CrossDomainUtils = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/bridge/Lib_CrossDomainUtils.sol/Lib_CrossDomainUtils.json')
} catch {}

let ovm__OVM_CrossDomainEnabled
try {
  ovm__OVM_CrossDomainEnabled = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/bridge/OVM_CrossDomainEnabled.sol/OVM_CrossDomainEnabled.json')
} catch {}

let ovm__Lib_EIP155Tx
try {
  ovm__Lib_EIP155Tx = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/codec/Lib_EIP155Tx.sol/Lib_EIP155Tx.json')
} catch {}

let ovm__Lib_OVMCodec
try {
  ovm__Lib_OVMCodec = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/codec/Lib_OVMCodec.sol/Lib_OVMCodec.json')
} catch {}

let ovm__Lib_PredeployAddresses
try {
  ovm__Lib_PredeployAddresses = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/constants/Lib_PredeployAddresses.sol/Lib_PredeployAddresses.json')
} catch {}

let ovm__Lib_AddressManager
try {
  ovm__Lib_AddressManager = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/resolver/Lib_AddressManager.sol/Lib_AddressManager.json')
} catch {}

let ovm__Lib_AddressResolver
try {
  ovm__Lib_AddressResolver = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/resolver/Lib_AddressResolver.sol/Lib_AddressResolver.json')
} catch {}

let ovm__Lib_ResolvedDelegateProxy
try {
  ovm__Lib_ResolvedDelegateProxy = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/resolver/Lib_ResolvedDelegateProxy.sol/Lib_ResolvedDelegateProxy.json')
} catch {}

let ovm__Lib_RLPReader
try {
  ovm__Lib_RLPReader = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/rlp/Lib_RLPReader.sol/Lib_RLPReader.json')
} catch {}

let ovm__Lib_RLPWriter
try {
  ovm__Lib_RLPWriter = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/rlp/Lib_RLPWriter.sol/Lib_RLPWriter.json')
} catch {}

let ovm__IL2StandardERC20
try {
  ovm__IL2StandardERC20 = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/standards/IL2StandardERC20.sol/IL2StandardERC20.json')
} catch {}

let ovm__IWETH9
try {
  ovm__IWETH9 = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/standards/IWETH9.sol/IWETH9.json')
} catch {}

let ovm__L2StandardERC20
try {
  ovm__L2StandardERC20 = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/standards/L2StandardERC20.sol/L2StandardERC20.json')
} catch {}

let ovm__Lib_MerkleTrie
try {
  ovm__Lib_MerkleTrie = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/trie/Lib_MerkleTrie.sol/Lib_MerkleTrie.json')
} catch {}

let ovm__Lib_SecureMerkleTrie
try {
  ovm__Lib_SecureMerkleTrie = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/trie/Lib_SecureMerkleTrie.sol/Lib_SecureMerkleTrie.json')
} catch {}

let ovm__Lib_Buffer
try {
  ovm__Lib_Buffer = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/utils/Lib_Buffer.sol/Lib_Buffer.json')
} catch {}

let ovm__Lib_Bytes32Utils
try {
  ovm__Lib_Bytes32Utils = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/utils/Lib_Bytes32Utils.sol/Lib_Bytes32Utils.json')
} catch {}

let ovm__Lib_BytesUtils
try {
  ovm__Lib_BytesUtils = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/utils/Lib_BytesUtils.sol/Lib_BytesUtils.json')
} catch {}

let ovm__Lib_ErrorUtils
try {
  ovm__Lib_ErrorUtils = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/utils/Lib_ErrorUtils.sol/Lib_ErrorUtils.json')
} catch {}

let ovm__Lib_MerkleTree
try {
  ovm__Lib_MerkleTree = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/utils/Lib_MerkleTree.sol/Lib_MerkleTree.json')
} catch {}

let ovm__Lib_ExecutionManagerWrapper
try {
  ovm__Lib_ExecutionManagerWrapper = require('../artifacts-ovm/contracts/optimistic-ethereum/libraries/wrappers/Lib_ExecutionManagerWrapper.sol/Lib_ExecutionManagerWrapper.json')
} catch {}

let ovm__mockOVM_BondManager
try {
  ovm__mockOVM_BondManager = require('../artifacts-ovm/contracts/optimistic-ethereum/mockOVM/verification/mockOVM_BondManager.sol/mockOVM_BondManager.json')
} catch {}

let ovm__OVM_L1CrossDomainMessenger
try {
  ovm__OVM_L1CrossDomainMessenger = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/bridge/messaging/OVM_L1CrossDomainMessenger.sol/OVM_L1CrossDomainMessenger.json')
} catch {}

let ovm__OVM_L2CrossDomainMessenger
try {
  ovm__OVM_L2CrossDomainMessenger = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/bridge/messaging/OVM_L2CrossDomainMessenger.sol/OVM_L2CrossDomainMessenger.json')
} catch {}

let ovm__OVM_L2StandardBridge
try {
  ovm__OVM_L2StandardBridge = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L2StandardBridge.sol/OVM_L2StandardBridge.json')
} catch {}

let ovm__OVM_L2StandardTokenFactory
try {
  ovm__OVM_L2StandardTokenFactory = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L2StandardTokenFactory.sol/OVM_L2StandardTokenFactory.json')
} catch {}

let ovm__OVM_ChainStorageContainer
try {
  ovm__OVM_ChainStorageContainer = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/chain/OVM_ChainStorageContainer.sol/OVM_ChainStorageContainer.json')
} catch {}

let ovm__OVM_StateCommitmentChain
try {
  ovm__OVM_StateCommitmentChain = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/chain/OVM_StateCommitmentChain.sol/OVM_StateCommitmentChain.json')
} catch {}

let ovm__OVM_SafetyChecker
try {
  ovm__OVM_SafetyChecker = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/execution/OVM_SafetyChecker.sol/OVM_SafetyChecker.json')
} catch {}

let ovm__OVM_StateManager
try {
  ovm__OVM_StateManager = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/execution/OVM_StateManager.sol/OVM_StateManager.json')
} catch {}

let ovm__OVM_StateManagerFactory
try {
  ovm__OVM_StateManagerFactory = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/execution/OVM_StateManagerFactory.sol/OVM_StateManagerFactory.json')
} catch {}

let ovm__ERC1820ImplementerInterface
try {
  ovm__ERC1820ImplementerInterface = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/predeploys/ERC1820Registry.sol/ERC1820ImplementerInterface.json')
} catch {}

let ovm__ERC1820Registry
try {
  ovm__ERC1820Registry = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/predeploys/ERC1820Registry.sol/ERC1820Registry.json')
} catch {}

let ovm__OVM_DeployerWhitelist
try {
  ovm__OVM_DeployerWhitelist = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/predeploys/OVM_DeployerWhitelist.sol/OVM_DeployerWhitelist.json')
} catch {}

let ovm__OVM_ECDSAContractAccount
try {
  ovm__OVM_ECDSAContractAccount = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/predeploys/OVM_ECDSAContractAccount.sol/OVM_ECDSAContractAccount.json')
} catch {}

let ovm__OVM_ETH
try {
  ovm__OVM_ETH = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/predeploys/OVM_ETH.sol/OVM_ETH.json')
} catch {}

let ovm__OVM_ExecutionManagerWrapper
try {
  ovm__OVM_ExecutionManagerWrapper = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/predeploys/OVM_ExecutionManagerWrapper.sol/OVM_ExecutionManagerWrapper.json')
} catch {}

let ovm__OVM_GasPriceOracle
try {
  ovm__OVM_GasPriceOracle = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/predeploys/OVM_GasPriceOracle.sol/OVM_GasPriceOracle.json')
} catch {}

let ovm__OVM_L1MessageSender
try {
  ovm__OVM_L1MessageSender = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/predeploys/OVM_L1MessageSender.sol/OVM_L1MessageSender.json')
} catch {}

let ovm__OVM_L2ToL1MessagePasser
try {
  ovm__OVM_L2ToL1MessagePasser = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/predeploys/OVM_L2ToL1MessagePasser.sol/OVM_L2ToL1MessagePasser.json')
} catch {}

let ovm__OVM_ProxyEOA
try {
  ovm__OVM_ProxyEOA = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/predeploys/OVM_ProxyEOA.sol/OVM_ProxyEOA.json')
} catch {}

let ovm__OVM_SequencerEntrypoint
try {
  ovm__OVM_SequencerEntrypoint = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/predeploys/OVM_SequencerEntrypoint.sol/OVM_SequencerEntrypoint.json')
} catch {}

let ovm__OVM_SequencerFeeVault
try {
  ovm__OVM_SequencerFeeVault = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/predeploys/OVM_SequencerFeeVault.sol/OVM_SequencerFeeVault.json')
} catch {}

let ovm__Abs_FraudContributor
try {
  ovm__Abs_FraudContributor = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/verification/Abs_FraudContributor.sol/Abs_FraudContributor.json')
} catch {}

let ovm__OVM_BondManager
try {
  ovm__OVM_BondManager = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/verification/OVM_BondManager.sol/OVM_BondManager.json')
} catch {}

let ovm__OVM_FraudVerifier
try {
  ovm__OVM_FraudVerifier = require('../artifacts-ovm/contracts/optimistic-ethereum/OVM/verification/OVM_FraudVerifier.sol/OVM_FraudVerifier.json')
} catch {}

let ovm__Helper_GasMeasurer
try {
  ovm__Helper_GasMeasurer = require('../artifacts-ovm/contracts/test-helpers/Helper_GasMeasurer.sol/Helper_GasMeasurer.json')
} catch {}

let ovm__Helper_ModifiableStorage
try {
  ovm__Helper_ModifiableStorage = require('../artifacts-ovm/contracts/test-helpers/Helper_ModifiableStorage.sol/Helper_ModifiableStorage.json')
} catch {}

let ovm__Helper_PredeployCaller
try {
  ovm__Helper_PredeployCaller = require('../artifacts-ovm/contracts/test-helpers/Helper_PrecompileCaller.sol/Helper_PredeployCaller.json')
} catch {}

let ovm__Helper_SimpleProxy
try {
  ovm__Helper_SimpleProxy = require('../artifacts-ovm/contracts/test-helpers/Helper_SimpleProxy.sol/Helper_SimpleProxy.json')
} catch {}

let ovm__Helper_TestRunner_CREATE
try {
  ovm__Helper_TestRunner_CREATE = require('../artifacts-ovm/contracts/test-helpers/Helper_TestRunner.sol/Helper_TestRunner_CREATE.json')
} catch {}

let ovm__Helper_TestRunner
try {
  ovm__Helper_TestRunner = require('../artifacts-ovm/contracts/test-helpers/Helper_TestRunner.sol/Helper_TestRunner.json')
} catch {}

let ovm__Mock_FraudVerifier
try {
  ovm__Mock_FraudVerifier = require('../artifacts-ovm/contracts/test-helpers/Mock_FraudVerifier.sol/Mock_FraudVerifier.json')
} catch {}

let ovm__SafeMath
try {
  ovm__SafeMath = require('../artifacts-ovm/contracts/test-helpers/TestERC20.sol/SafeMath.json')
} catch {}

let ovm__TestERC20
try {
  ovm__TestERC20 = require('../artifacts-ovm/contracts/test-helpers/TestERC20.sol/TestERC20.json')
} catch {}

let ovm__TestLib_EIP155Tx
try {
  ovm__TestLib_EIP155Tx = require('../artifacts-ovm/contracts/test-libraries/codec/TestLib_EIP155Tx.sol/TestLib_EIP155Tx.json')
} catch {}

let ovm__TestLib_OVMCodec
try {
  ovm__TestLib_OVMCodec = require('../artifacts-ovm/contracts/test-libraries/codec/TestLib_OVMCodec.sol/TestLib_OVMCodec.json')
} catch {}

let ovm__TestLib_RLPReader
try {
  ovm__TestLib_RLPReader = require('../artifacts-ovm/contracts/test-libraries/rlp/TestLib_RLPReader.sol/TestLib_RLPReader.json')
} catch {}

let ovm__TestLib_RLPWriter
try {
  ovm__TestLib_RLPWriter = require('../artifacts-ovm/contracts/test-libraries/rlp/TestLib_RLPWriter.sol/TestLib_RLPWriter.json')
} catch {}

let ovm__TestLib_MerkleTrie
try {
  ovm__TestLib_MerkleTrie = require('../artifacts-ovm/contracts/test-libraries/trie/TestLib_MerkleTrie.sol/TestLib_MerkleTrie.json')
} catch {}

let ovm__TestLib_SecureMerkleTrie
try {
  ovm__TestLib_SecureMerkleTrie = require('../artifacts-ovm/contracts/test-libraries/trie/TestLib_SecureMerkleTrie.sol/TestLib_SecureMerkleTrie.json')
} catch {}

let ovm__TestLib_Buffer
try {
  ovm__TestLib_Buffer = require('../artifacts-ovm/contracts/test-libraries/utils/TestLib_Buffer.sol/TestLib_Buffer.json')
} catch {}

let ovm__TestLib_Bytes32Utils
try {
  ovm__TestLib_Bytes32Utils = require('../artifacts-ovm/contracts/test-libraries/utils/TestLib_Bytes32Utils.sol/TestLib_Bytes32Utils.json')
} catch {}

let ovm__TestLib_BytesUtils
try {
  ovm__TestLib_BytesUtils = require('../artifacts-ovm/contracts/test-libraries/utils/TestLib_BytesUtils.sol/TestLib_BytesUtils.json')
} catch {}

let ovm__TestLib_MerkleTree
try {
  ovm__TestLib_MerkleTree = require('../artifacts-ovm/contracts/test-libraries/utils/TestLib_MerkleTree.sol/TestLib_MerkleTree.json')
} catch {}

let iL1ChugSplashDeployer
try {
  iL1ChugSplashDeployer = require('../artifacts/contracts/chugsplash/interfaces/iL1ChugSplashDeployer.sol/iL1ChugSplashDeployer.json')
} catch {}

let L1ChugSplashProxy
try {
  L1ChugSplashProxy = require('../artifacts/contracts/chugsplash/L1ChugSplashProxy.sol/L1ChugSplashProxy.json')
} catch {}

let iOVM_CrossDomainMessenger
try {
  iOVM_CrossDomainMessenger = require('../artifacts/contracts/optimistic-ethereum/iOVM/bridge/messaging/iOVM_CrossDomainMessenger.sol/iOVM_CrossDomainMessenger.json')
} catch {}

let iOVM_L1CrossDomainMessenger
try {
  iOVM_L1CrossDomainMessenger = require('../artifacts/contracts/optimistic-ethereum/iOVM/bridge/messaging/iOVM_L1CrossDomainMessenger.sol/iOVM_L1CrossDomainMessenger.json')
} catch {}

let iOVM_L1MultiMessageRelayer
try {
  iOVM_L1MultiMessageRelayer = require('../artifacts/contracts/optimistic-ethereum/iOVM/bridge/messaging/iOVM_L1MultiMessageRelayer.sol/iOVM_L1MultiMessageRelayer.json')
} catch {}

let iOVM_L2CrossDomainMessenger
try {
  iOVM_L2CrossDomainMessenger = require('../artifacts/contracts/optimistic-ethereum/iOVM/bridge/messaging/iOVM_L2CrossDomainMessenger.sol/iOVM_L2CrossDomainMessenger.json')
} catch {}

let iOVM_L1ERC20Bridge
try {
  iOVM_L1ERC20Bridge = require('../artifacts/contracts/optimistic-ethereum/iOVM/bridge/tokens/iOVM_L1ERC20Bridge.sol/iOVM_L1ERC20Bridge.json')
} catch {}

let iOVM_L1StandardBridge
try {
  iOVM_L1StandardBridge = require('../artifacts/contracts/optimistic-ethereum/iOVM/bridge/tokens/iOVM_L1StandardBridge.sol/iOVM_L1StandardBridge.json')
} catch {}

let iOVM_L2ERC20Bridge
try {
  iOVM_L2ERC20Bridge = require('../artifacts/contracts/optimistic-ethereum/iOVM/bridge/tokens/iOVM_L2ERC20Bridge.sol/iOVM_L2ERC20Bridge.json')
} catch {}

let iOVM_CanonicalTransactionChain
try {
  iOVM_CanonicalTransactionChain = require('../artifacts/contracts/optimistic-ethereum/iOVM/chain/iOVM_CanonicalTransactionChain.sol/iOVM_CanonicalTransactionChain.json')
} catch {}

let iOVM_ChainStorageContainer
try {
  iOVM_ChainStorageContainer = require('../artifacts/contracts/optimistic-ethereum/iOVM/chain/iOVM_ChainStorageContainer.sol/iOVM_ChainStorageContainer.json')
} catch {}

let iOVM_StateCommitmentChain
try {
  iOVM_StateCommitmentChain = require('../artifacts/contracts/optimistic-ethereum/iOVM/chain/iOVM_StateCommitmentChain.sol/iOVM_StateCommitmentChain.json')
} catch {}

let iOVM_ExecutionManager
try {
  iOVM_ExecutionManager = require('../artifacts/contracts/optimistic-ethereum/iOVM/execution/iOVM_ExecutionManager.sol/iOVM_ExecutionManager.json')
} catch {}

let iOVM_SafetyChecker
try {
  iOVM_SafetyChecker = require('../artifacts/contracts/optimistic-ethereum/iOVM/execution/iOVM_SafetyChecker.sol/iOVM_SafetyChecker.json')
} catch {}

let iOVM_StateManager
try {
  iOVM_StateManager = require('../artifacts/contracts/optimistic-ethereum/iOVM/execution/iOVM_StateManager.sol/iOVM_StateManager.json')
} catch {}

let iOVM_StateManagerFactory
try {
  iOVM_StateManagerFactory = require('../artifacts/contracts/optimistic-ethereum/iOVM/execution/iOVM_StateManagerFactory.sol/iOVM_StateManagerFactory.json')
} catch {}

let iOVM_DeployerWhitelist
try {
  iOVM_DeployerWhitelist = require('../artifacts/contracts/optimistic-ethereum/iOVM/predeploys/iOVM_DeployerWhitelist.sol/iOVM_DeployerWhitelist.json')
} catch {}

let iOVM_ECDSAContractAccount
try {
  iOVM_ECDSAContractAccount = require('../artifacts/contracts/optimistic-ethereum/iOVM/predeploys/iOVM_ECDSAContractAccount.sol/iOVM_ECDSAContractAccount.json')
} catch {}

let iOVM_L1MessageSender
try {
  iOVM_L1MessageSender = require('../artifacts/contracts/optimistic-ethereum/iOVM/predeploys/iOVM_L1MessageSender.sol/iOVM_L1MessageSender.json')
} catch {}

let iOVM_L2ToL1MessagePasser
try {
  iOVM_L2ToL1MessagePasser = require('../artifacts/contracts/optimistic-ethereum/iOVM/predeploys/iOVM_L2ToL1MessagePasser.sol/iOVM_L2ToL1MessagePasser.json')
} catch {}

let ERC20
try {
  ERC20 = require('../artifacts/contracts/optimistic-ethereum/iOVM/verification/iOVM_BondManager.sol/ERC20.json')
} catch {}

let Errors
try {
  Errors = require('../artifacts/contracts/optimistic-ethereum/iOVM/verification/iOVM_BondManager.sol/Errors.json')
} catch {}

let iOVM_BondManager
try {
  iOVM_BondManager = require('../artifacts/contracts/optimistic-ethereum/iOVM/verification/iOVM_BondManager.sol/iOVM_BondManager.json')
} catch {}

let iOVM_FraudVerifier
try {
  iOVM_FraudVerifier = require('../artifacts/contracts/optimistic-ethereum/iOVM/verification/iOVM_FraudVerifier.sol/iOVM_FraudVerifier.json')
} catch {}

let iOVM_StateTransitioner
try {
  iOVM_StateTransitioner = require('../artifacts/contracts/optimistic-ethereum/iOVM/verification/iOVM_StateTransitioner.sol/iOVM_StateTransitioner.json')
} catch {}

let iOVM_StateTransitionerFactory
try {
  iOVM_StateTransitionerFactory = require('../artifacts/contracts/optimistic-ethereum/iOVM/verification/iOVM_StateTransitionerFactory.sol/iOVM_StateTransitionerFactory.json')
} catch {}

let Lib_CrossDomainUtils
try {
  Lib_CrossDomainUtils = require('../artifacts/contracts/optimistic-ethereum/libraries/bridge/Lib_CrossDomainUtils.sol/Lib_CrossDomainUtils.json')
} catch {}

let OVM_CrossDomainEnabled
try {
  OVM_CrossDomainEnabled = require('../artifacts/contracts/optimistic-ethereum/libraries/bridge/OVM_CrossDomainEnabled.sol/OVM_CrossDomainEnabled.json')
} catch {}

let Lib_EIP155Tx
try {
  Lib_EIP155Tx = require('../artifacts/contracts/optimistic-ethereum/libraries/codec/Lib_EIP155Tx.sol/Lib_EIP155Tx.json')
} catch {}

let Lib_OVMCodec
try {
  Lib_OVMCodec = require('../artifacts/contracts/optimistic-ethereum/libraries/codec/Lib_OVMCodec.sol/Lib_OVMCodec.json')
} catch {}

let Lib_PredeployAddresses
try {
  Lib_PredeployAddresses = require('../artifacts/contracts/optimistic-ethereum/libraries/constants/Lib_PredeployAddresses.sol/Lib_PredeployAddresses.json')
} catch {}

let Lib_AddressManager
try {
  Lib_AddressManager = require('../artifacts/contracts/optimistic-ethereum/libraries/resolver/Lib_AddressManager.sol/Lib_AddressManager.json')
} catch {}

let Lib_AddressResolver
try {
  Lib_AddressResolver = require('../artifacts/contracts/optimistic-ethereum/libraries/resolver/Lib_AddressResolver.sol/Lib_AddressResolver.json')
} catch {}

let Lib_ResolvedDelegateProxy
try {
  Lib_ResolvedDelegateProxy = require('../artifacts/contracts/optimistic-ethereum/libraries/resolver/Lib_ResolvedDelegateProxy.sol/Lib_ResolvedDelegateProxy.json')
} catch {}

let Lib_RLPReader
try {
  Lib_RLPReader = require('../artifacts/contracts/optimistic-ethereum/libraries/rlp/Lib_RLPReader.sol/Lib_RLPReader.json')
} catch {}

let Lib_RLPWriter
try {
  Lib_RLPWriter = require('../artifacts/contracts/optimistic-ethereum/libraries/rlp/Lib_RLPWriter.sol/Lib_RLPWriter.json')
} catch {}

let IL2StandardERC20
try {
  IL2StandardERC20 = require('../artifacts/contracts/optimistic-ethereum/libraries/standards/IL2StandardERC20.sol/IL2StandardERC20.json')
} catch {}

let IWETH9
try {
  IWETH9 = require('../artifacts/contracts/optimistic-ethereum/libraries/standards/IWETH9.sol/IWETH9.json')
} catch {}

let L2StandardERC20
try {
  L2StandardERC20 = require('../artifacts/contracts/optimistic-ethereum/libraries/standards/L2StandardERC20.sol/L2StandardERC20.json')
} catch {}

let Lib_MerkleTrie
try {
  Lib_MerkleTrie = require('../artifacts/contracts/optimistic-ethereum/libraries/trie/Lib_MerkleTrie.sol/Lib_MerkleTrie.json')
} catch {}

let Lib_SecureMerkleTrie
try {
  Lib_SecureMerkleTrie = require('../artifacts/contracts/optimistic-ethereum/libraries/trie/Lib_SecureMerkleTrie.sol/Lib_SecureMerkleTrie.json')
} catch {}

let Lib_Buffer
try {
  Lib_Buffer = require('../artifacts/contracts/optimistic-ethereum/libraries/utils/Lib_Buffer.sol/Lib_Buffer.json')
} catch {}

let Lib_Bytes32Utils
try {
  Lib_Bytes32Utils = require('../artifacts/contracts/optimistic-ethereum/libraries/utils/Lib_Bytes32Utils.sol/Lib_Bytes32Utils.json')
} catch {}

let Lib_BytesUtils
try {
  Lib_BytesUtils = require('../artifacts/contracts/optimistic-ethereum/libraries/utils/Lib_BytesUtils.sol/Lib_BytesUtils.json')
} catch {}

let Lib_ErrorUtils
try {
  Lib_ErrorUtils = require('../artifacts/contracts/optimistic-ethereum/libraries/utils/Lib_ErrorUtils.sol/Lib_ErrorUtils.json')
} catch {}

let Lib_EthUtils
try {
  Lib_EthUtils = require('../artifacts/contracts/optimistic-ethereum/libraries/utils/Lib_EthUtils.sol/Lib_EthUtils.json')
} catch {}

let Lib_MerkleTree
try {
  Lib_MerkleTree = require('../artifacts/contracts/optimistic-ethereum/libraries/utils/Lib_MerkleTree.sol/Lib_MerkleTree.json')
} catch {}

let Lib_ExecutionManagerWrapper
try {
  Lib_ExecutionManagerWrapper = require('../artifacts/contracts/optimistic-ethereum/libraries/wrappers/Lib_ExecutionManagerWrapper.sol/Lib_ExecutionManagerWrapper.json')
} catch {}

let mockOVM_BondManager
try {
  mockOVM_BondManager = require('../artifacts/contracts/optimistic-ethereum/mockOVM/verification/mockOVM_BondManager.sol/mockOVM_BondManager.json')
} catch {}

let OVM_L1CrossDomainMessenger
try {
  OVM_L1CrossDomainMessenger = require('../artifacts/contracts/optimistic-ethereum/OVM/bridge/messaging/OVM_L1CrossDomainMessenger.sol/OVM_L1CrossDomainMessenger.json')
} catch {}

let OVM_L1MultiMessageRelayer
try {
  OVM_L1MultiMessageRelayer = require('../artifacts/contracts/optimistic-ethereum/OVM/bridge/messaging/OVM_L1MultiMessageRelayer.sol/OVM_L1MultiMessageRelayer.json')
} catch {}

let OVM_L2CrossDomainMessenger
try {
  OVM_L2CrossDomainMessenger = require('../artifacts/contracts/optimistic-ethereum/OVM/bridge/messaging/OVM_L2CrossDomainMessenger.sol/OVM_L2CrossDomainMessenger.json')
} catch {}

let OVM_L1StandardBridge
try {
  OVM_L1StandardBridge = require('../artifacts/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L1StandardBridge.sol/OVM_L1StandardBridge.json')
} catch {}

let OVM_L2StandardBridge
try {
  OVM_L2StandardBridge = require('../artifacts/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L2StandardBridge.sol/OVM_L2StandardBridge.json')
} catch {}

let OVM_L2StandardTokenFactory
try {
  OVM_L2StandardTokenFactory = require('../artifacts/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L2StandardTokenFactory.sol/OVM_L2StandardTokenFactory.json')
} catch {}

let OVM_CanonicalTransactionChain
try {
  OVM_CanonicalTransactionChain = require('../artifacts/contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol/OVM_CanonicalTransactionChain.json')
} catch {}

let OVM_ChainStorageContainer
try {
  OVM_ChainStorageContainer = require('../artifacts/contracts/optimistic-ethereum/OVM/chain/OVM_ChainStorageContainer.sol/OVM_ChainStorageContainer.json')
} catch {}

let OVM_StateCommitmentChain
try {
  OVM_StateCommitmentChain = require('../artifacts/contracts/optimistic-ethereum/OVM/chain/OVM_StateCommitmentChain.sol/OVM_StateCommitmentChain.json')
} catch {}

let OVM_ExecutionManager
try {
  OVM_ExecutionManager = require('../artifacts/contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol/OVM_ExecutionManager.json')
} catch {}

let OVM_SafetyChecker
try {
  OVM_SafetyChecker = require('../artifacts/contracts/optimistic-ethereum/OVM/execution/OVM_SafetyChecker.sol/OVM_SafetyChecker.json')
} catch {}

let OVM_StateManager
try {
  OVM_StateManager = require('../artifacts/contracts/optimistic-ethereum/OVM/execution/OVM_StateManager.sol/OVM_StateManager.json')
} catch {}

let OVM_StateManagerFactory
try {
  OVM_StateManagerFactory = require('../artifacts/contracts/optimistic-ethereum/OVM/execution/OVM_StateManagerFactory.sol/OVM_StateManagerFactory.json')
} catch {}

let ERC1820ImplementerInterface
try {
  ERC1820ImplementerInterface = require('../artifacts/contracts/optimistic-ethereum/OVM/predeploys/ERC1820Registry.sol/ERC1820ImplementerInterface.json')
} catch {}

let ERC1820Registry
try {
  ERC1820Registry = require('../artifacts/contracts/optimistic-ethereum/OVM/predeploys/ERC1820Registry.sol/ERC1820Registry.json')
} catch {}

let OVM_DeployerWhitelist
try {
  OVM_DeployerWhitelist = require('../artifacts/contracts/optimistic-ethereum/OVM/predeploys/OVM_DeployerWhitelist.sol/OVM_DeployerWhitelist.json')
} catch {}

let OVM_ECDSAContractAccount
try {
  OVM_ECDSAContractAccount = require('../artifacts/contracts/optimistic-ethereum/OVM/predeploys/OVM_ECDSAContractAccount.sol/OVM_ECDSAContractAccount.json')
} catch {}

let OVM_ETH
try {
  OVM_ETH = require('../artifacts/contracts/optimistic-ethereum/OVM/predeploys/OVM_ETH.sol/OVM_ETH.json')
} catch {}

let OVM_GasPriceOracle
try {
  OVM_GasPriceOracle = require('../artifacts/contracts/optimistic-ethereum/OVM/predeploys/OVM_GasPriceOracle.sol/OVM_GasPriceOracle.json')
} catch {}

let OVM_L1MessageSender
try {
  OVM_L1MessageSender = require('../artifacts/contracts/optimistic-ethereum/OVM/predeploys/OVM_L1MessageSender.sol/OVM_L1MessageSender.json')
} catch {}

let OVM_L2ToL1MessagePasser
try {
  OVM_L2ToL1MessagePasser = require('../artifacts/contracts/optimistic-ethereum/OVM/predeploys/OVM_L2ToL1MessagePasser.sol/OVM_L2ToL1MessagePasser.json')
} catch {}

let OVM_ProxyEOA
try {
  OVM_ProxyEOA = require('../artifacts/contracts/optimistic-ethereum/OVM/predeploys/OVM_ProxyEOA.sol/OVM_ProxyEOA.json')
} catch {}

let OVM_SequencerEntrypoint
try {
  OVM_SequencerEntrypoint = require('../artifacts/contracts/optimistic-ethereum/OVM/predeploys/OVM_SequencerEntrypoint.sol/OVM_SequencerEntrypoint.json')
} catch {}

let OVM_SequencerFeeVault
try {
  OVM_SequencerFeeVault = require('../artifacts/contracts/optimistic-ethereum/OVM/predeploys/OVM_SequencerFeeVault.sol/OVM_SequencerFeeVault.json')
} catch {}

let Abs_FraudContributor
try {
  Abs_FraudContributor = require('../artifacts/contracts/optimistic-ethereum/OVM/verification/Abs_FraudContributor.sol/Abs_FraudContributor.json')
} catch {}

let OVM_BondManager
try {
  OVM_BondManager = require('../artifacts/contracts/optimistic-ethereum/OVM/verification/OVM_BondManager.sol/OVM_BondManager.json')
} catch {}

let OVM_FraudVerifier
try {
  OVM_FraudVerifier = require('../artifacts/contracts/optimistic-ethereum/OVM/verification/OVM_FraudVerifier.sol/OVM_FraudVerifier.json')
} catch {}

let OVM_StateTransitioner
try {
  OVM_StateTransitioner = require('../artifacts/contracts/optimistic-ethereum/OVM/verification/OVM_StateTransitioner.sol/OVM_StateTransitioner.json')
} catch {}

let OVM_StateTransitionerFactory
try {
  OVM_StateTransitionerFactory = require('../artifacts/contracts/optimistic-ethereum/OVM/verification/OVM_StateTransitionerFactory.sol/OVM_StateTransitionerFactory.json')
} catch {}

let Helper_GasMeasurer
try {
  Helper_GasMeasurer = require('../artifacts/contracts/test-helpers/Helper_GasMeasurer.sol/Helper_GasMeasurer.json')
} catch {}

let Helper_ModifiableStorage
try {
  Helper_ModifiableStorage = require('../artifacts/contracts/test-helpers/Helper_ModifiableStorage.sol/Helper_ModifiableStorage.json')
} catch {}

let Helper_PredeployCaller
try {
  Helper_PredeployCaller = require('../artifacts/contracts/test-helpers/Helper_PrecompileCaller.sol/Helper_PredeployCaller.json')
} catch {}

let Helper_SimpleProxy
try {
  Helper_SimpleProxy = require('../artifacts/contracts/test-helpers/Helper_SimpleProxy.sol/Helper_SimpleProxy.json')
} catch {}

let Helper_TestRunner_CREATE
try {
  Helper_TestRunner_CREATE = require('../artifacts/contracts/test-helpers/Helper_TestRunner.sol/Helper_TestRunner_CREATE.json')
} catch {}

let Helper_TestRunner
try {
  Helper_TestRunner = require('../artifacts/contracts/test-helpers/Helper_TestRunner.sol/Helper_TestRunner.json')
} catch {}

let Mock_FraudVerifier
try {
  Mock_FraudVerifier = require('../artifacts/contracts/test-helpers/Mock_FraudVerifier.sol/Mock_FraudVerifier.json')
} catch {}

let SafeMath
try {
  SafeMath = require('../artifacts/contracts/test-helpers/TestERC20.sol/SafeMath.json')
} catch {}

let TestERC20
try {
  TestERC20 = require('../artifacts/contracts/test-helpers/TestERC20.sol/TestERC20.json')
} catch {}

let TestLib_EIP155Tx
try {
  TestLib_EIP155Tx = require('../artifacts/contracts/test-libraries/codec/TestLib_EIP155Tx.sol/TestLib_EIP155Tx.json')
} catch {}

let TestLib_OVMCodec
try {
  TestLib_OVMCodec = require('../artifacts/contracts/test-libraries/codec/TestLib_OVMCodec.sol/TestLib_OVMCodec.json')
} catch {}

let TestLib_RLPReader
try {
  TestLib_RLPReader = require('../artifacts/contracts/test-libraries/rlp/TestLib_RLPReader.sol/TestLib_RLPReader.json')
} catch {}

let TestLib_RLPWriter
try {
  TestLib_RLPWriter = require('../artifacts/contracts/test-libraries/rlp/TestLib_RLPWriter.sol/TestLib_RLPWriter.json')
} catch {}

let TestLib_MerkleTrie
try {
  TestLib_MerkleTrie = require('../artifacts/contracts/test-libraries/trie/TestLib_MerkleTrie.sol/TestLib_MerkleTrie.json')
} catch {}

let TestLib_SecureMerkleTrie
try {
  TestLib_SecureMerkleTrie = require('../artifacts/contracts/test-libraries/trie/TestLib_SecureMerkleTrie.sol/TestLib_SecureMerkleTrie.json')
} catch {}

let TestLib_Buffer
try {
  TestLib_Buffer = require('../artifacts/contracts/test-libraries/utils/TestLib_Buffer.sol/TestLib_Buffer.json')
} catch {}

let TestLib_Bytes32Utils
try {
  TestLib_Bytes32Utils = require('../artifacts/contracts/test-libraries/utils/TestLib_Bytes32Utils.sol/TestLib_Bytes32Utils.json')
} catch {}

let TestLib_BytesUtils
try {
  TestLib_BytesUtils = require('../artifacts/contracts/test-libraries/utils/TestLib_BytesUtils.sol/TestLib_BytesUtils.json')
} catch {}

let TestLib_EthUtils
try {
  TestLib_EthUtils = require('../artifacts/contracts/test-libraries/utils/TestLib_EthUtils.sol/TestLib_EthUtils.json')
} catch {}

let TestLib_MerkleTree
try {
  TestLib_MerkleTree = require('../artifacts/contracts/test-libraries/utils/TestLib_MerkleTree.sol/TestLib_MerkleTree.json')
} catch {}

export const getContractArtifact = (name: string, ovm: boolean): any => {
  if (ovm) {
    return {
      iL1ChugSplashDeployer: ovm__iL1ChugSplashDeployer,
      L1ChugSplashProxy: ovm__L1ChugSplashProxy,
      iOVM_CrossDomainMessenger: ovm__iOVM_CrossDomainMessenger,
      iOVM_L1CrossDomainMessenger: ovm__iOVM_L1CrossDomainMessenger,
      iOVM_L1MultiMessageRelayer: ovm__iOVM_L1MultiMessageRelayer,
      iOVM_L2CrossDomainMessenger: ovm__iOVM_L2CrossDomainMessenger,
      iOVM_L1ERC20Bridge: ovm__iOVM_L1ERC20Bridge,
      iOVM_L1StandardBridge: ovm__iOVM_L1StandardBridge,
      iOVM_L2ERC20Bridge: ovm__iOVM_L2ERC20Bridge,
      iOVM_CanonicalTransactionChain: ovm__iOVM_CanonicalTransactionChain,
      iOVM_ChainStorageContainer: ovm__iOVM_ChainStorageContainer,
      iOVM_StateCommitmentChain: ovm__iOVM_StateCommitmentChain,
      iOVM_ExecutionManager: ovm__iOVM_ExecutionManager,
      iOVM_SafetyChecker: ovm__iOVM_SafetyChecker,
      iOVM_StateManager: ovm__iOVM_StateManager,
      iOVM_StateManagerFactory: ovm__iOVM_StateManagerFactory,
      iOVM_DeployerWhitelist: ovm__iOVM_DeployerWhitelist,
      iOVM_ECDSAContractAccount: ovm__iOVM_ECDSAContractAccount,
      iOVM_L1MessageSender: ovm__iOVM_L1MessageSender,
      iOVM_L2ToL1MessagePasser: ovm__iOVM_L2ToL1MessagePasser,
      ERC20: ovm__ERC20,
      Errors: ovm__Errors,
      iOVM_BondManager: ovm__iOVM_BondManager,
      iOVM_FraudVerifier: ovm__iOVM_FraudVerifier,
      iOVM_StateTransitioner: ovm__iOVM_StateTransitioner,
      iOVM_StateTransitionerFactory: ovm__iOVM_StateTransitionerFactory,
      Lib_CrossDomainUtils: ovm__Lib_CrossDomainUtils,
      OVM_CrossDomainEnabled: ovm__OVM_CrossDomainEnabled,
      Lib_EIP155Tx: ovm__Lib_EIP155Tx,
      Lib_OVMCodec: ovm__Lib_OVMCodec,
      Lib_PredeployAddresses: ovm__Lib_PredeployAddresses,
      Lib_AddressManager: ovm__Lib_AddressManager,
      Lib_AddressResolver: ovm__Lib_AddressResolver,
      Lib_ResolvedDelegateProxy: ovm__Lib_ResolvedDelegateProxy,
      Lib_RLPReader: ovm__Lib_RLPReader,
      Lib_RLPWriter: ovm__Lib_RLPWriter,
      IL2StandardERC20: ovm__IL2StandardERC20,
      IWETH9: ovm__IWETH9,
      L2StandardERC20: ovm__L2StandardERC20,
      Lib_MerkleTrie: ovm__Lib_MerkleTrie,
      Lib_SecureMerkleTrie: ovm__Lib_SecureMerkleTrie,
      Lib_Buffer: ovm__Lib_Buffer,
      Lib_Bytes32Utils: ovm__Lib_Bytes32Utils,
      Lib_BytesUtils: ovm__Lib_BytesUtils,
      Lib_ErrorUtils: ovm__Lib_ErrorUtils,
      Lib_MerkleTree: ovm__Lib_MerkleTree,
      Lib_ExecutionManagerWrapper: ovm__Lib_ExecutionManagerWrapper,
      mockOVM_BondManager: ovm__mockOVM_BondManager,
      OVM_L1CrossDomainMessenger: ovm__OVM_L1CrossDomainMessenger,
      OVM_L2CrossDomainMessenger: ovm__OVM_L2CrossDomainMessenger,
      OVM_L2StandardBridge: ovm__OVM_L2StandardBridge,
      OVM_L2StandardTokenFactory: ovm__OVM_L2StandardTokenFactory,
      OVM_ChainStorageContainer: ovm__OVM_ChainStorageContainer,
      OVM_StateCommitmentChain: ovm__OVM_StateCommitmentChain,
      OVM_SafetyChecker: ovm__OVM_SafetyChecker,
      OVM_StateManager: ovm__OVM_StateManager,
      OVM_StateManagerFactory: ovm__OVM_StateManagerFactory,
      ERC1820ImplementerInterface: ovm__ERC1820ImplementerInterface,
      ERC1820Registry: ovm__ERC1820Registry,
      OVM_DeployerWhitelist: ovm__OVM_DeployerWhitelist,
      OVM_ECDSAContractAccount: ovm__OVM_ECDSAContractAccount,
      OVM_ETH: ovm__OVM_ETH,
      OVM_ExecutionManagerWrapper: ovm__OVM_ExecutionManagerWrapper,
      OVM_GasPriceOracle: ovm__OVM_GasPriceOracle,
      OVM_L1MessageSender: ovm__OVM_L1MessageSender,
      OVM_L2ToL1MessagePasser: ovm__OVM_L2ToL1MessagePasser,
      OVM_ProxyEOA: ovm__OVM_ProxyEOA,
      OVM_SequencerEntrypoint: ovm__OVM_SequencerEntrypoint,
      OVM_SequencerFeeVault: ovm__OVM_SequencerFeeVault,
      Abs_FraudContributor: ovm__Abs_FraudContributor,
      OVM_BondManager: ovm__OVM_BondManager,
      OVM_FraudVerifier: ovm__OVM_FraudVerifier,
      Helper_GasMeasurer: ovm__Helper_GasMeasurer,
      Helper_ModifiableStorage: ovm__Helper_ModifiableStorage,
      Helper_PredeployCaller: ovm__Helper_PredeployCaller,
      Helper_SimpleProxy: ovm__Helper_SimpleProxy,
      Helper_TestRunner_CREATE: ovm__Helper_TestRunner_CREATE,
      Helper_TestRunner: ovm__Helper_TestRunner,
      Mock_FraudVerifier: ovm__Mock_FraudVerifier,
      SafeMath: ovm__SafeMath,
      TestERC20: ovm__TestERC20,
      TestLib_EIP155Tx: ovm__TestLib_EIP155Tx,
      TestLib_OVMCodec: ovm__TestLib_OVMCodec,
      TestLib_RLPReader: ovm__TestLib_RLPReader,
      TestLib_RLPWriter: ovm__TestLib_RLPWriter,
      TestLib_MerkleTrie: ovm__TestLib_MerkleTrie,
      TestLib_SecureMerkleTrie: ovm__TestLib_SecureMerkleTrie,
      TestLib_Buffer: ovm__TestLib_Buffer,
      TestLib_Bytes32Utils: ovm__TestLib_Bytes32Utils,
      TestLib_BytesUtils: ovm__TestLib_BytesUtils,
      TestLib_MerkleTree: ovm__TestLib_MerkleTree,
    }[name]
  } else {
    return {
      iL1ChugSplashDeployer,
      L1ChugSplashProxy,
      iOVM_CrossDomainMessenger,
      iOVM_L1CrossDomainMessenger,
      iOVM_L1MultiMessageRelayer,
      iOVM_L2CrossDomainMessenger,
      iOVM_L1ERC20Bridge,
      iOVM_L1StandardBridge,
      iOVM_L2ERC20Bridge,
      iOVM_CanonicalTransactionChain,
      iOVM_ChainStorageContainer,
      iOVM_StateCommitmentChain,
      iOVM_ExecutionManager,
      iOVM_SafetyChecker,
      iOVM_StateManager,
      iOVM_StateManagerFactory,
      iOVM_DeployerWhitelist,
      iOVM_ECDSAContractAccount,
      iOVM_L1MessageSender,
      iOVM_L2ToL1MessagePasser,
      ERC20,
      Errors,
      iOVM_BondManager,
      iOVM_FraudVerifier,
      iOVM_StateTransitioner,
      iOVM_StateTransitionerFactory,
      Lib_CrossDomainUtils,
      OVM_CrossDomainEnabled,
      Lib_EIP155Tx,
      Lib_OVMCodec,
      Lib_PredeployAddresses,
      Lib_AddressManager,
      Lib_AddressResolver,
      Lib_ResolvedDelegateProxy,
      Lib_RLPReader,
      Lib_RLPWriter,
      IL2StandardERC20,
      IWETH9,
      L2StandardERC20,
      Lib_MerkleTrie,
      Lib_SecureMerkleTrie,
      Lib_Buffer,
      Lib_Bytes32Utils,
      Lib_BytesUtils,
      Lib_ErrorUtils,
      Lib_EthUtils,
      Lib_MerkleTree,
      Lib_ExecutionManagerWrapper,
      mockOVM_BondManager,
      OVM_L1CrossDomainMessenger,
      OVM_L1MultiMessageRelayer,
      OVM_L2CrossDomainMessenger,
      OVM_L1StandardBridge,
      OVM_L2StandardBridge,
      OVM_L2StandardTokenFactory,
      OVM_CanonicalTransactionChain,
      OVM_ChainStorageContainer,
      OVM_StateCommitmentChain,
      OVM_ExecutionManager,
      OVM_SafetyChecker,
      OVM_StateManager,
      OVM_StateManagerFactory,
      ERC1820ImplementerInterface,
      ERC1820Registry,
      OVM_DeployerWhitelist,
      OVM_ECDSAContractAccount,
      OVM_ETH,
      OVM_GasPriceOracle,
      OVM_L1MessageSender,
      OVM_L2ToL1MessagePasser,
      OVM_ProxyEOA,
      OVM_SequencerEntrypoint,
      OVM_SequencerFeeVault,
      Abs_FraudContributor,
      OVM_BondManager,
      OVM_FraudVerifier,
      OVM_StateTransitioner,
      OVM_StateTransitionerFactory,
      Helper_GasMeasurer,
      Helper_ModifiableStorage,
      Helper_PredeployCaller,
      Helper_SimpleProxy,
      Helper_TestRunner_CREATE,
      Helper_TestRunner,
      Mock_FraudVerifier,
      SafeMath,
      TestERC20,
      TestLib_EIP155Tx,
      TestLib_OVMCodec,
      TestLib_RLPReader,
      TestLib_RLPWriter,
      TestLib_MerkleTrie,
      TestLib_SecureMerkleTrie,
      TestLib_Buffer,
      TestLib_Bytes32Utils,
      TestLib_BytesUtils,
      TestLib_EthUtils,
      TestLib_MerkleTree,
    }[name]
  }
}
