[package]
name = "lokahi"
version = "0.1.0"
description = "Rust implementation of the OP Stack supernode: a multi-chain consensus-layer host"

edition.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
# workspace
op-version.workspace = true

# general
clap = { workspace = true, features = ["derive"] }
