export const CONFIG = {
  ETHEREUM_ENDPOINT: 'ETHEREUM_ENDPOINT',
  SYNC_SERVICE_OPTIONS: 'SYNC_SERVICE_OPTIONS',
  OPERATOR_OPTIONS: 'OPERATOR_OPTIONS',
  CONTRACT_OPTIONS: 'CONTRACT_OPTIONS',
  EVENT_WATCHER_OPTIONS: 'EVENT_WATCHER_OPTIONS',
}
