[server]
enable_request_log = true
log_level = "debug"
max_body_size_bytes = 10485760
max_upstream_batch_size = 100
rpc_host = "0.0.0.0"
rpc_port = 8080

[metrics]
enabled = true
host = "0.0.0.0"
port = 7300

[batch]
max_size = 1000

[cache]
enabled = false

[backend]
max_degraded_latency_threshold = "30ms"
max_retries = 0
out_of_service_seconds = 0
response_timeout_seconds = 5

[backends]
[backends.bne-l1-mainnet-el-archive-0]
rpc_url = "https://json-rpc.7lr7xdhajdvsnqrwbeh51ptwl.blockchainnodeengine.com?key=AIzaSyDQPMLjO2VkaTKbxVN6jGU91pEE8ctnCg4"
ws_url = "ws://dummy"

[backend_groups]
[backend_groups.replica]
backends = ["bne-l1-mainnet-el-archive-0"]

[rpc_method_mappings]
debug_dbGet = "replica"
debug_getRawReceipts = "replica"
debug_storageRangeAt = "replica"
debug_traceBlockByHash = "replica"
debug_traceBlockByNumber = "replica"
debug_traceTransaction = "replica"
eth_accounts = "replica"
eth_blockNumber = "replica"
eth_call = "replica"
eth_chainId = "replica"
eth_estimateGas = "replica"
eth_gasPrice = "replica"
eth_getBalance = "replica"
eth_getBlockByHash = "replica"
eth_getBlockByNumber = "replica"
eth_getBlockRange = "replica"
eth_getBlockTransactionCountByHash = "replica"
eth_getBlockTransactionCountByNumber = "replica"
eth_getCode = "replica"
eth_getLogs = "replica"
eth_getProof = "replica"
eth_getStorageAt = "replica"
eth_getTransactionByBlockHashAndIndex = "replica"
eth_getTransactionByHash = "replica"
eth_getTransactionCount = "replica"
eth_getTransactionReceipt = "replica"
eth_getUncleByBlockHashAndIndex = "replica"
eth_maxPriorityFeePerGas = "replica"
eth_sendRawTransaction = "replica"
eth_syncing = "replica"
net_version = "replica"
rollup_getInfo = "replica"
web3_clientVersion = "replica"

[rate_limit]
error_message = "Your IP has exceeded its requests per second capacity. To increase your rate limits, please chat with us on Discord."
rate_per_second = 500

