# default recipe to display help information
default:
  @just --list

# Run cargo tests
test *args='':
  cargo nextest run --workspace {{args}}

# Check no_std compatibility
check-no-std:
  rustup target add riscv32imac-unknown-none-elf
  cargo check -p alloy-op-evm --target riscv32imac-unknown-none-elf --no-default-features
