//! Build script for `kona-chainview`.
//!
//! Compiles `src/chainview.sql` with the pinned upstream Feldera `sql-to-dbsp` compiler
//! into `OUT_DIR` and post-processes the output so it can be included as a nested module
//! of this crate. Nothing generated is written outside `OUT_DIR`, and the compiler JAR is
//! never downloaded here: `just chainview-fetch-compiler` does that, with a sha256 check.
//!
//! The pinned compiler version must match the `dbsp` crate version pinned in the
//! workspace `Cargo.toml`; the script refuses to build when they disagree.

use std::{
    env, fs,
    path::{Path, PathBuf},
    process::Command,
};

use anyhow::{Context, Result, anyhow, bail};
use sha2::{Digest, Sha256};

/// The Feldera release whose `sql-to-dbsp` compiler emits code for the pinned `dbsp` crate.
const FELDERA_VERSION: &str = "0.342.0";
/// File name of the compiler JAR as published on the Feldera `GitHub` release.
const JAR_FILE: &str = "sql2dbsp-jar-with-dependencies-v0.342.0.jar";
/// sha256 of [`JAR_FILE`]; enforced for JARs found in the cache directory.
const JAR_SHA256: &str = "29a03dca0049e7b57e810d4dd045dc134dcdb6db4864505deb9b5501000f5dd0";
/// Environment variable naming an explicit JAR path (overrides the cache lookup).
const JAR_ENV: &str = "KONA_SQL2DBSP_JAR";
/// The SQL program, relative to the crate root.
const SQL_FILE: &str = "src/chainview.sql";
/// The UDF implementation file, relative to the crate root (may be empty).
const UDF_FILE: &str = "src/udf.rs";
/// The recipe that provisions the JAR.
const FETCH_RECIPE: &str = "just chainview-fetch-compiler";

fn main() {
    if let Err(e) = run() {
        panic!("{e:?}");
    }
}

fn run() -> Result<()> {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").context("CARGO_MANIFEST_DIR not set")?);
    let out_dir = PathBuf::from(env::var("OUT_DIR").context("OUT_DIR not set")?);
    let sql_path = manifest_dir.join(SQL_FILE);
    let udf_path = manifest_dir.join(UDF_FILE);

    // Rust-only edits must never invoke the compiler: only these inputs trigger a rerun.
    println!("cargo::rerun-if-changed={}", sql_path.display());
    println!("cargo::rerun-if-changed=build.rs");
    for var in [JAR_ENV, "JAVA_HOME", "XDG_CACHE_HOME", "HOME"] {
        println!("cargo::rerun-if-env-changed={var}");
    }

    check_workspace_pin(&manifest_dir)?;
    let jar = resolve_jar()?;
    println!("cargo::rerun-if-changed={}", jar.display());
    let java = resolve_java()?;

    let sql_out = out_dir.join("sql");
    fs::create_dir_all(&sql_out).with_context(|| format!("create {}", sql_out.display()))?;
    let errors_path = sql_out.join("errors.json");
    let schema_path = sql_out.join("schema.json");
    let lib_path = sql_out.join("lib.rs");
    // The compiler writes `stubs.rs` next to the `-o` file.
    let stubs_path = sql_out.join("stubs.rs");
    for stale in [&errors_path, &schema_path, &lib_path, &stubs_path] {
        let _ = fs::remove_file(stale);
    }

    let output = Command::new(&java)
        .arg("-jar")
        .arg(&jar)
        .arg(&sql_path)
        .args(["-i", "--handles", "--alltables", "--ignoreOrder", "--outputsAreSets", "-je"])
        .arg("--errors")
        .arg(&errors_path)
        .arg("-js")
        .arg(&schema_path)
        .arg("-o")
        .arg(&lib_path)
        .output()
        .with_context(|| format!("run {} -jar {}", java.display(), jar.display()))?;

    report_diagnostics(&errors_path, &sql_path)?;
    if !output.status.success() {
        bail!(
            "sql-to-dbsp failed with {}\nstdout:\n{}\nstderr:\n{}",
            output.status,
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }

    let generated = fs::read_to_string(&lib_path)
        .with_context(|| format!("read generated {}", lib_path.display()))?;
    let stubs = fs::read_to_string(&stubs_path)
        .with_context(|| format!("read generated {}", stubs_path.display()))?;
    let generated = postprocess_lib(&generated, &udf_path)?;
    let stubs = postprocess_stubs(&stubs)?;

    let final_lib = out_dir.join("lib.rs");
    let final_stubs = out_dir.join("stubs.rs");
    let final_schema = out_dir.join("schema.json");
    write_if_changed(&final_lib, &generated)?;
    write_if_changed(&final_stubs, &stubs)?;
    let schema = fs::read_to_string(&schema_path)
        .with_context(|| format!("read {}", schema_path.display()))?;
    write_if_changed(&final_schema, &schema)?;

    let wrapper = format!(
        "// Generated by build.rs; do not edit.\n\
         #[allow(warnings, unused, clippy::all, clippy::pedantic, clippy::nursery, rustdoc::all)]\n\
         #[doc(hidden)]\n\
         #[rustfmt::skip]\n\
         #[path = {lib:?}]\n\
         pub mod circuit;\n\
         /// The table/view schema of the compiled program, as emitted by `sql-to-dbsp -js`.\n\
         pub const PROGRAM_SCHEMA_JSON: &str = include_str!({schema:?});\n",
        lib = final_lib.display().to_string(),
        schema = final_schema.display().to_string(),
    );
    write_if_changed(&out_dir.join("generated.rs"), &wrapper)?;
    Ok(())
}

/// Refuses to build when the workspace pins a different `dbsp` version than the compiler.
fn check_workspace_pin(manifest_dir: &Path) -> Result<()> {
    let workspace = manifest_dir
        .ancestors()
        .skip(1)
        .map(|p| p.join("Cargo.toml"))
        .find(|p| fs::read_to_string(p).map(|s| s.contains("[workspace]")).unwrap_or(false))
        .ok_or_else(|| {
            anyhow!("could not find a workspace Cargo.toml above {}", manifest_dir.display())
        })?;
    let text =
        fs::read_to_string(&workspace).with_context(|| format!("read {}", workspace.display()))?;
    let wanted = format!("\"={FELDERA_VERSION}\"");
    let pinned = text.lines().any(|l| l.trim_start().starts_with("dbsp") && l.contains(&wanted));
    if !pinned {
        bail!(
            "{} does not pin `dbsp = {{ version = {wanted} }}`; bump FELDERA_VERSION/JAR_FILE/JAR_SHA256 \
             in kona/crates/node/chainview/build.rs and the Feldera pins in the workspace Cargo.toml together",
            workspace.display()
        );
    }
    Ok(())
}

/// Locates the compiler JAR: `$KONA_SQL2DBSP_JAR`, then the cache directory.
fn resolve_jar() -> Result<PathBuf> {
    if let Ok(explicit) = env::var(JAR_ENV) {
        let path = PathBuf::from(explicit);
        if !path.is_file() {
            bail!("{JAR_ENV}={} is not a file", path.display());
        }
        if let Err(e) = verify_sha256(&path) {
            println!(
                "cargo::warning=kona-chainview: {JAR_ENV} points at an unverified compiler: {e}"
            );
        }
        return Ok(path);
    }
    let cache_root = env::var_os("XDG_CACHE_HOME")
        .map(PathBuf::from)
        .or_else(|| env::var_os("HOME").map(|h| PathBuf::from(h).join(".cache")))
        .ok_or_else(|| anyhow!("neither XDG_CACHE_HOME nor HOME is set"))?;
    let path = cache_root.join("kona-chainview").join(JAR_FILE);
    if !path.is_file() {
        bail!(
            "sql-to-dbsp v{FELDERA_VERSION} compiler JAR not found at {} and {JAR_ENV} is unset; \
             run `{FETCH_RECIPE}` from rust/ or set {JAR_ENV}",
            path.display()
        );
    }
    verify_sha256(&path)?;
    Ok(path)
}

fn verify_sha256(path: &Path) -> Result<()> {
    let bytes = fs::read(path).with_context(|| format!("read {}", path.display()))?;
    let digest = Sha256::digest(&bytes);
    let actual = digest.iter().map(|b| format!("{b:02x}")).collect::<String>();
    if actual != JAR_SHA256 {
        bail!(
            "{} has sha256 {actual}, expected {JAR_SHA256} (v{FELDERA_VERSION}); re-run `{FETCH_RECIPE}`",
            path.display()
        );
    }
    Ok(())
}

/// Locates a JDK 19–21 `java` binary via `$JAVA_HOME/bin/java`, then `PATH`.
fn resolve_java() -> Result<PathBuf> {
    let java = env::var_os("JAVA_HOME")
        .map(|home| PathBuf::from(home).join("bin").join("java"))
        .filter(|p| p.is_file())
        .unwrap_or_else(|| PathBuf::from("java"));
    let output = Command::new(&java).arg("-version").output().with_context(|| {
        format!(
            "run `{} -version`; install a JDK 19-21 (e.g. openjdk-21-jdk-headless) or set JAVA_HOME",
            java.display()
        )
    })?;
    let banner = String::from_utf8_lossy(&output.stderr).to_string() +
        &String::from_utf8_lossy(&output.stdout);
    let major = parse_java_major(&banner)
        .ok_or_else(|| anyhow!("could not parse a Java version from:\n{banner}"))?;
    if major < 19 {
        bail!(
            "Java {major} found at {}; sql-to-dbsp needs Java 19-21 (set JAVA_HOME)",
            java.display()
        );
    }
    if major > 21 {
        println!(
            "cargo::warning=kona-chainview: Java {major} is newer than the tested 19-21 range"
        );
    }
    Ok(java)
}

/// Parses the major version out of `java -version` output such as
/// `openjdk version "21.0.12" 2026-07-21` or `java version "1.8.0_292"`.
fn parse_java_major(banner: &str) -> Option<u32> {
    let quoted = banner.split('"').nth(1)?;
    let mut parts = quoted.split('.');
    let first: u32 = parts.next()?.parse().ok()?;
    if first == 1 { parts.next()?.parse().ok() } else { Some(first) }
}

/// Fails the build on compiler errors and forwards warnings to cargo.
fn report_diagnostics(errors_path: &Path, sql_path: &Path) -> Result<()> {
    let Ok(text) = fs::read_to_string(errors_path) else {
        return Ok(());
    };
    if text.trim().is_empty() {
        return Ok(());
    }
    let entries: Vec<serde_json::Value> = serde_json::from_str(&text)
        .with_context(|| format!("parse compiler diagnostics {}", errors_path.display()))?;
    let mut errors = Vec::new();
    for entry in &entries {
        let warning = entry.get("warning").and_then(|v| v.as_bool()).unwrap_or(false);
        let kind = entry.get("error_type").and_then(|v| v.as_str()).unwrap_or("error");
        let message = entry.get("message").and_then(|v| v.as_str()).unwrap_or("");
        let line = entry.get("start_line_number").and_then(|v| v.as_u64()).unwrap_or(0);
        let column = entry.get("start_column").and_then(|v| v.as_u64()).unwrap_or(0);
        let rendered = format!(
            "{}:{line}:{column}: {kind}: {}",
            sql_path.display(),
            message.replace('\n', " ")
        );
        if warning {
            // Status tables deliberately carry columns only the host reads back; the
            // compiler flags them on every build, which would drown real warnings.
            if kind != "Unused column" {
                println!("cargo::warning=kona-chainview: {rendered}");
            }
        } else {
            errors.push(rendered);
        }
    }
    if !errors.is_empty() {
        bail!("sql-to-dbsp reported {} error(s):\n{}", errors.len(), errors.join("\n"));
    }
    Ok(())
}

/// Rewrites the generated crate root into something that compiles as a nested module.
fn postprocess_lib(generated: &str, udf_path: &Path) -> Result<String> {
    let lines: Vec<&str> = generated.lines().collect();
    let mut out: Vec<String> = Vec::with_capacity(lines.len());
    let mut i = 0;
    let mut stripped_allocator = false;
    while i < lines.len() {
        let line = lines[i].trim();
        // The compiler emits a jemalloc global allocator plus a `malloc_conf` export; both are
        // wrong for a library embedded in kona-node.
        if line == "#[cfg(not(target_env = \"msvc\"))]" &&
            lines.get(i + 1).map(|l| l.trim()) == Some("#[global_allocator]")
        {
            i += 3;
            stripped_allocator = true;
            continue;
        }
        if line == "#[allow(non_upper_case_globals)]" &&
            lines
                .get(i + 1)
                .is_some_and(|l| l.trim().starts_with("#[export_name = \"malloc_conf\"]"))
        {
            i += 3;
            continue;
        }
        // The crate root sets the recursion limit; a nested module may not.
        if line.starts_with("#![recursion_limit") {
            i += 1;
            continue;
        }
        if line == "pub mod udf;" {
            out.push(format!("#[path = {:?}]", udf_path.display().to_string()));
            out.push("pub mod udf;".to_string());
            i += 1;
            continue;
        }
        out.push(
            lines[i].replace("crate::udf", "self::udf").replace("crate::stubs", "self::stubs"),
        );
        i += 1;
    }
    let text = out.join("\n") + "\n";
    if !stripped_allocator {
        bail!(
            "generated code has no jemalloc allocator block to strip; the compiler output changed shape"
        );
    }
    if text.contains("tikv_jemallocator") || text.contains("malloc_conf") {
        bail!("allocator references survived post-processing");
    }
    if let Some(offender) = text.lines().find(|l| l.contains("crate::")) {
        bail!("generated code still refers to `crate::` after post-processing: {offender}");
    }
    Ok(text)
}

/// `stubs.rs` assumes it sits at the crate root; point it at the generated module instead.
fn postprocess_stubs(stubs: &str) -> Result<String> {
    let text = stubs.replace("use crate::*;", "use super::*;");
    if let Some(offender) = text.lines().find(|l| l.contains("crate::")) {
        bail!("stubs.rs still refers to `crate::` after post-processing: {offender}");
    }
    Ok(text)
}

fn write_if_changed(path: &Path, contents: &str) -> Result<()> {
    if fs::read_to_string(path).map(|old| old == contents).unwrap_or(false) {
        return Ok(());
    }
    fs::write(path, contents).with_context(|| format!("write {}", path.display()))
}
