//! Extracts per-chain config + zstd-compressed genesis bytes from the
//! committed `op-superchain` zip into `$OUT_DIR`, then writes a generated
//! `chain_specs.rs` containing the `create_superchain_specs!` macro
//! invocation. The `Superchain` enum + lookup helpers come from the macro
//! expansion against the chain list `supported_chains()` reports.

use std::{collections::BTreeMap, env, fs, path::PathBuf};

use serde_json::Value;

fn main() {
    if env::var("CARGO_FEATURE_SUPERCHAIN_CONFIGS").is_err() {
        // The feature is off; nothing to generate. Touch a stub so any
        // include! site that references the file fails with a clear error
        // rather than a path-not-found.
        return;
    }

    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set"));

    // Ship the dictionary once at the workspace level -- every per-chain
    // genesis uses it.
    let dictionary = op_superchain::read_dictionary().expect("read dictionary");
    fs::write(out_dir.join("dictionary"), &dictionary).expect("write dictionary");

    let chains = op_superchain::supported_chains().expect("read supported_chains");

    // Per-chain extraction: TOML → JSON for the config, raw zstd bytes for
    // the genesis. Both written to OUT_DIR under stable, predictable paths.
    fs::create_dir_all(out_dir.join("configs")).unwrap();
    fs::create_dir_all(out_dir.join("genesis")).unwrap();
    for (name, env) in &chains {
        let toml = op_superchain::read_chain_config_toml(name, env)
            .expect("read chain toml")
            .unwrap_or_else(|| panic!("no TOML for {name}/{env}"));
        let json = toml_string_to_json(&toml).expect("toml->json");
        let cfg_dir = out_dir.join("configs").join(env);
        fs::create_dir_all(&cfg_dir).unwrap();
        fs::write(cfg_dir.join(format!("{name}.json")), json).expect("write config json");

        let genesis = op_superchain::read_chain_genesis_compressed(name, env)
            .expect("read genesis")
            .unwrap_or_else(|| panic!("no genesis for {name}/{env}"));
        let gen_dir = out_dir.join("genesis").join(env);
        fs::create_dir_all(&gen_dir).unwrap();
        fs::write(gen_dir.join(format!("{name}.json.zst")), genesis).expect("write genesis zst");
    }

    // Generated chain_specs.rs: the macro invocation. Skip OP / Base /
    // OP Sepolia / Base Sepolia, which `reth-optimism-chainspec` defines
    // explicitly elsewhere.
    let mut specs = String::new();
    specs.push_str("// Generated by build.rs -- do not edit.\n");
    specs.push_str("use crate::create_superchain_specs;\n\n");
    specs.push_str("create_superchain_specs!(\n");
    for (name, env) in &chains {
        if is_explicitly_defined(name, env) {
            continue;
        }
        specs.push_str(&format!("    (\"{name}\", \"{env}\"),\n"));
    }
    specs.push_str(");\n");
    fs::write(out_dir.join("chain_specs.rs"), specs).expect("write chain_specs.rs");

    // Generated lookups.rs: `match`-based `config_str` and `genesis_bytes`.
    // Each arm `include_*!`s the per-chain file we just materialised in OUT_DIR.
    let mut lookups = String::new();
    lookups.push_str("// Generated by build.rs -- do not edit.\n\n");
    lookups.push_str(
        "pub(super) fn config_str(name: &str, environment: &str) -> Option<&'static str> {\n",
    );
    lookups.push_str("    match (name, environment) {\n");
    for (name, env) in &chains {
        lookups.push_str(&format!(
            "        (\"{name}\", \"{env}\") => Some(include_str!(concat!(env!(\"OUT_DIR\"), \"/configs/{env}/{name}.json\"))),\n"
        ));
    }
    lookups.push_str("        _ => None,\n    }\n}\n\n");

    lookups.push_str(
        "pub(super) fn genesis_bytes(name: &str, environment: &str) -> Option<&'static [u8]> {\n",
    );
    lookups.push_str("    match (name, environment) {\n");
    for (name, env) in &chains {
        lookups.push_str(&format!(
            "        (\"{name}\", \"{env}\") => Some(include_bytes!(concat!(env!(\"OUT_DIR\"), \"/genesis/{env}/{name}.json.zst\"))),\n"
        ));
    }
    lookups.push_str("        _ => None,\n    }\n}\n");

    fs::write(out_dir.join("lookups.rs"), lookups).expect("write lookups.rs");
}

fn is_explicitly_defined(name: &str, env: &str) -> bool {
    matches!((name, env), ("op" | "base", "mainnet" | "sepolia"))
}

fn toml_string_to_json(raw: &str) -> Result<String, Box<dyn std::error::Error>> {
    let v: toml::Value = toml::from_str(raw)?;
    let j = toml_to_json(v);
    Ok(serde_json::to_string(&j)?)
}

fn toml_to_json(v: toml::Value) -> Value {
    match v {
        toml::Value::String(s) => Value::String(s),
        toml::Value::Integer(i) => Value::from(i),
        toml::Value::Float(f) => {
            serde_json::Number::from_f64(f).map(Value::Number).unwrap_or(Value::Null)
        }
        toml::Value::Boolean(b) => Value::Bool(b),
        toml::Value::Datetime(d) => Value::String(d.to_string()),
        toml::Value::Array(a) => Value::Array(a.into_iter().map(toml_to_json).collect()),
        toml::Value::Table(t) => {
            let mut m: BTreeMap<String, Value> = BTreeMap::new();
            for (k, val) in t {
                m.insert(k, toml_to_json(val));
            }
            Value::Object(m.into_iter().collect())
        }
    }
}
