// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	common "github.com/ethereum/go-ethereum/common"

	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// KmsManager is an autogenerated mock type for the KmsManager type
type KmsManager struct {
	mock.Mock
}

// GetAddr provides a mock function with given fields:
func (_m *KmsManager) GetAddr() (common.Address, error) {
	ret := _m.Called()

	var r0 common.Address
	var r1 error
	if rf, ok := ret.Get(0).(func() (common.Address, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() common.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Address)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Sign provides a mock function with given fields: rawTx
func (_m *KmsManager) Sign(rawTx *types.DynamicFeeTx) (*types.Transaction, error) {
	ret := _m.Called(rawTx)

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*types.DynamicFeeTx) (*types.Transaction, error)); ok {
		return rf(rawTx)
	}
	if rf, ok := ret.Get(0).(func(*types.DynamicFeeTx) *types.Transaction); ok {
		r0 = rf(rawTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*types.DynamicFeeTx) error); ok {
		r1 = rf(rawTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewKmsManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewKmsManager creates a new instance of KmsManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewKmsManager(t mockConstructorTestingTNewKmsManager) *KmsManager {
	mock := &KmsManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
