fbals:
	#!/usr/bin/env bash
	if (($BASH_VERSINFO < 4)); then exit; fi
	RUST_JIT_BUILD=0 \
	RUST_BACKTRACE=full \
	RUST_BINARY_PATH_OP_RETH=$HOME/git/optimism/rust/target/debug/op-reth \
	RUST_BINARY_PATH_OP_RBUILDER=$HOME/git/op-rbuilder/target/debug/op-rbuilder \
	RUST_LOG=op_reth=trace,op_rbuilder=debug,rollup_boost=debug \
	RUST_LOG=trace \
	go test -v -count=1 -timeout 10m ./... |& tee out.log

stream:
	#!/usr/bin/env bash
	if (($BASH_VERSINFO < 4)); then exit; fi
	RUST_JIT_BUILD=0 \
	RUST_BACKTRACE=full \
	RUST_BINARY_PATH_OP_RETH=$HOME/git/optimism/rust/target/debug/op-reth \
	RUST_BINARY_PATH_OP_RBUILDER=$HOME/git/op-rbuilder/target/debug/op-rbuilder \
	RUST_LOG=op_reth=trace,op_rbuilder=debug,rollup_boost=debug \
	RUST_LOG=trace \
	go test -v -count=1 -timeout 10m ./utils.go ./flashblocks_stream_test.go |& tee out.log

transfer:
	#!/usr/bin/env bash
	if (($BASH_VERSINFO < 4)); then exit; fi
	RUST_JIT_BUILD=0 \
	RUST_BACKTRACE=full \
	RUST_BINARY_PATH_OP_RETH=$HOME/git/optimism/rust/target/debug/op-reth \
	RUST_BINARY_PATH_OP_RBUILDER=$HOME/git/op-rbuilder/target/debug/op-rbuilder \
	RUST_LOG=op_reth=trace,op_rbuilder=debug,rollup_boost=debug \
	RUST_LOG=trace \
	go test -v -count=1 -timeout 10m ./utils.go ./flashblocks_transfer_test.go |& tee out.log


# for custom rollup-boost add
# RUST_BINARY_PATH_ROLLUP_BOOST=$HOME/git/rollup-boost/target/debug/rollup-boost \
