fbals:
	#!/usr/bin/env bash
	RUST_BACKTRACE=full \
	RUST_BINARY_PATH_OP_RETH=$HOME/git/optimism/rust/target/debug/op-reth-prod \
	RUST_BINARY_PATH_OP_RBUILDER=$HOME/git/op-rbuilder/target/debug/op-rbuilder-prod \
	RUST_BINARY_PATH_ROLLUP_BOOST=$HOME/git/rollup-boost/target/debug/rollup-boost-prod \
	LOG_LEVEL=trace \
	RUST_LOG=op_reth=trace,op_rbuilder=debug,rollup_boost=debug \
	go test -v -count=1 -timeout 5m utils.go flashblocks_accesslist_test.go
