set positional-arguments

# default recipe to display help information
default:
  @just --list

# Generate file bindings
bind:
  KONA_BIND=true cargo build

# Update the `superchain-registry` git submodule source
source:
  cd "$(git rev-parse --show-toplevel)" && git submodule update --remote --init --recursive packages/contracts-bedrock/lib/superchain-registry
