{
 "title": "Indexer",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "etl_rate_interval", "query": "2m" }
  ]
 },
 "panels": [
  { "title": "ETL Processor (Blocks & Logs)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Indexed L1 Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_indexer_etl_l1_indexed_height",
     "legendFormat": "ETL"
    }
   ]
  },
  {
   "title": "Reported L1 Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_indexer_etl_l1_latest_height",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L1 Sync %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_indexer_etl_l1_indexed_height\n / op_indexer_etl_l1_latest_height\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG ETL Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(op_indexer_etl_l1_interval_seconds_sum[$etl_rate_interval])\n/\nrate(op_indexer_etl_l1_interval_seconds_count[$etl_rate_interval])",
     "legendFormat": "l1"
    },
    {
     "expr": "rate(op_indexer_etl_l2_interval_seconds_sum[$etl_rate_interval])\n/\nrate(op_indexer_etl_l2_interval_seconds_count[$etl_rate_interval])",
     "legendFormat": "l2"
    }
   ]
  },
  {
   "title": "Indexed L2 Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_indexer_etl_l2_indexed_height",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reported L2 Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_indexer_etl_l2_latest_height",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L2 Sync %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_indexer_etl_l2_indexed_height\n / op_indexer_etl_l2_latest_height",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexed L1 Logs / m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(contract) (rate(op_indexer_etl_l1_indexed_logs_total[$etl_rate_interval])) * 60",
     "legendFormat": "{{contract}}"
    }
   ]
  },
  {
   "title": "Indexed L2 Logs / m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(contract) (rate(op_indexer_etl_l2_indexed_logs_total[$etl_rate_interval])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Bridge Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Initiated Bridge L1 Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_indexer_bridge_height{chain=\"l1\", kind=\"initiated\"}",
     "legendFormat": "initiated"
    }
   ]
  },
  {
   "title": "Initiated L1 Sync %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_indexer_bridge_height{chain=\"l1\", kind=\"initiated\"} / on() op_indexer_etl_l1_indexed_height",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finalized L1 Bridge Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_indexer_bridge_height{chain=\"l1\", kind=\"finalized\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finalized L1 Sync %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_indexer_bridge_height{chain=\"l1\", kind=\"finalized\"} / on() op_indexer_etl_l1_indexed_height",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG Bridge Processing Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(chain) \n(rate(op_indexer_bridge_interval_seconds_sum[$etl_rate_interval])\n/\nrate(op_indexer_bridge_interval_seconds_count[$etl_rate_interval]))",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Initiated Bridge L2 Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_indexer_bridge_height{chain=\"l2\", kind=\"initiated\"}",
     "legendFormat": "initiated"
    }
   ]
  },
  {
   "title": "Initiated L2 Sync %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_indexer_bridge_height{chain=\"l2\", kind=\"initiated\"} / on() op_indexer_etl_l2_indexed_height",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finalized Bridge L2 Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_indexer_bridge_height{chain=\"l2\", kind=\"finalized\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finalized L2 Sync %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_indexer_bridge_height{chain=\"l2\", kind=\"finalized\"} / on() op_indexer_etl_l2_indexed_height",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L1 Bridge Transactions / m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(op_indexer_bridge_tx_deposits[$etl_rate_interval]) * 60",
     "legendFormat": "L1 Transaction Deposits"
    },
    {
     "expr": "rate(op_indexer_bridge_sent_messages{chain=\"l1\"}[$etl_rate_interval]) * 60",
     "legendFormat": "L1 Sent Messages"
    },
    {
     "expr": "rate(op_indexer_bridge_relayed_messages{chain=\"l1\"}[$etl_rate_interval]) * 60",
     "legendFormat": "L1 Relayed Messages"
    },
    {
     "expr": "rate(op_indexer_bridge_initiated_token_transfers{chain=\"l1\"}[$etl_rate_interval]) * 60",
     "legendFormat": "L1 Initiated Bridge Transfers"
    },
    {
     "expr": "rate(op_indexer_bridge_finalized_token_transfers{chain=\"l1\"}[$etl_rate_interval]) * 60",
     "legendFormat": "L1 Finalized Bridge Transfers"
    },
    {
     "expr": "rate(op_indexer_bridge_skipped_ovm1_withdrawals{chain=\"l1\"}[$etl_rate_interval]) * 60 ",
     "legendFormat": "Skipped OVM1 Withdrawals"
    }
   ]
  },
  {
   "title": "Transferred ETH / m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(op_indexer_bridge_tx_minted_eth[$etl_rate_interval]) * 60",
     "legendFormat": "Minted ETH"
    },
    {
     "expr": "rate(op_indexer_bridge_tx_withdrawn_eth[$etl_rate_interval]) * 60",
     "legendFormat": "Withdrawn ETH"
    }
   ]
  },
  {
   "title": "L2 Bridge Transactions / m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(op_indexer_bridge_tx_withdrawals[$etl_rate_interval]) * 60",
     "legendFormat": "L2 Transaction Withdrawals"
    },
    {
     "expr": "rate(op_indexer_bridge_sent_messages{chain=\"l2\"}[$etl_rate_interval]) * 60",
     "legendFormat": "L2 Sent Messages"
    },
    {
     "expr": "rate(op_indexer_bridge_relayed_messages{chain=\"l2\"}[$etl_rate_interval]) * 60",
     "legendFormat": "L2 Relayed Messages"
    },
    {
     "expr": "rate(op_indexer_bridge_initiated_token_transfers{chain=\"l2\"}[$etl_rate_interval]) * 60",
     "legendFormat": "L2 Initiated Bridge Transfers"
    },
    {
     "expr": "rate(op_indexer_bridge_finalized_token_transfers{chain=\"l2\"}[$etl_rate_interval]) * 60",
     "legendFormat": "L2 Finalized Bridge Transfers"
    }
   ]
  },
  {
   "title": "Transferred ERC20 / m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(token_address) (rate(op_indexer_bridge_initiated_token_transfers{token_address!=\"0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000\"}[$etl_rate_interval])) * 60",
     "legendFormat": "{{token_address}}"
    }
   ]
  },
  { "title": "RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "L1 RPC / m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(op_indexer_rpc_l1_requests_total[$etl_rate_interval])) * 60",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "sum by(method,error) (rate(op_indexer_rpc_l1_responses_total{error!=\"<nil>\"}[$etl_rate_interval])) * 60",
     "legendFormat": "{{method}} (error: {{error}})"
    }
   ]
  },
  {
   "title": "AVG L1 RPC Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(op_indexer_rpc_l1_request_duration_seconds_sum[$etl_rate_interval])\n/\nrate(op_indexer_rpc_l1_request_duration_seconds_count[$etl_rate_interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "L2 RPC / m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(op_indexer_rpc_l2_requests_total[$etl_rate_interval])) * 60",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "AVG L2 RPC Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(op_indexer_rpc_l2_request_duration_seconds_sum[$etl_rate_interval])\n/\nrate(op_indexer_rpc_l2_request_duration_seconds_count[$etl_rate_interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}