import '../justfiles/go.just'

# Run tests
test: (go_test "./...")

# Generate mocks
generate-mocks: (go_generate "./...")

[private]
service_fuzz_task FUZZ TIME='60s': (go_fuzz FUZZ TIME "./eth")

# Run fuzzing tests
fuzz:
    go test ./eth/... -list=Fuzz -vet=off \
    | grep 'Fuzz' \
    | parallel -j {{PARALLEL_JOBS}} {{just_executable()}} service_fuzz_task {}
