#!/usr/bin/env python3
"""Write L1cdmEvm/Bytecode.lean from bytecode/L1CrossDomainMessenger.runtime.hex.

The Lean file holds the exact deployed runtime bytes (metadata trailer included) as ONE flat
ByteArray literal, plus the JUMPDEST table, which the Lean kernel checks against EVMLean's `D_J`
(no `native_decide`). Rerun after recompiling the contract:

    python3 scripts/gen_bytecode.py bytecode/L1CrossDomainMessenger.runtime.hex \
        L1cdmEvm/Bytecode.lean [defName]

`defName` (default `l1cdmRuntime`) names the ByteArray and its JUMPDEST theorem
`<defName without "Runtime">ValidJumps`, so several contracts can share the namespace.

The literal is deliberately not split into appended chunks: the kernel would have to evaluate
`ByteArray.append` (quadratic in the code size) in every decode proof.
"""
import sys
from pathlib import Path


def wrap(items, width=96):
    lines, cur = [], ""
    for p in items:
        if cur and len(cur) + len(p) + 2 > width:
            lines.append(cur)
            cur = p
        else:
            cur = p if not cur else cur + ", " + p
    lines.append(cur)
    return lines


def main() -> None:
    src, dst = Path(sys.argv[1]), Path(sys.argv[2])
    name = sys.argv[3] if len(sys.argv) > 3 else "l1cdmRuntime"
    hexstr = src.read_text().strip()
    if hexstr.startswith("0x"):
        hexstr = hexstr[2:]
    code = bytes.fromhex(hexstr)
    out = []
    out.append("import Ethereum.Semantics\nimport Reasoning.JumpDest\nimport L1cdmEvm.KernelDecide\n")
    out.append("/-!\n# L1CrossDomainMessenger deployed runtime bytecode (generated)\n")
    out.append("Generated by `scripts/gen_bytecode.py` from")
    out.append(f"`{src.as_posix()}`; do not edit by hand.\n")
    out.append(f"Size: {len(code)} bytes. See README.md for the compiler invocation and hashes.\n-/\n")
    out.append("namespace L1cdmEvm\n")
    out.append("set_option maxRecDepth 50000000\n")
    body = ",\n    ".join(wrap([f"0x{b:02x}" for b in code]))
    out.append("/-- The deployed runtime code of L1CrossDomainMessenger at the pinned commit. -/")
    out.append(f"def {name} : ByteArray :=\n  ⟨#[{body}]⟩\n")
    # JUMPDEST analysis (positions of 0x5b outside PUSH immediates), as EVM D_J computes it.
    dests, i = [], 0
    while i < len(code):
        op = code[i]
        if op == 0x5B:
            dests.append(i)
        i += 1 + (op - 0x5F if 0x60 <= op <= 0x7F else 0)
    lst = ", ".join(f"⟨{d}⟩" for d in dests)
    out.append(f"/-- The JUMPDEST set of `{name}`, computed by this script and checked by the Lean")
    out.append("    kernel against EVMLean's `D_J` (through the proved `D_J_eq_jumpdestScan`). -/")
    out.append(f"@[valid_jumps] theorem {name.replace('Runtime', '')}ValidJumps :")
    out.append(f"    Ethereum.EVM.D_J {name} 0 = #[" + lst + "] := by")
    out.append("  rw [Ethereum.EVM.KernelDecide.D_J_eq_jumpdestScan]")
    out.append("  decide +kernel\n")
    out.append("end L1cdmEvm\n")
    dst.write_text("\n".join(out))


if __name__ == "__main__":
    main()
