{
 "title": "L2 Builder",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "L1 Head Block Number",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "op_node_default_refs_number{layer=\"l1\", type=\"l1_head\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L2 Unsafe Block Number",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "op_node_default_refs_number{layer=\"l2\", type=\"l2_unsafe\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P Peers",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "targets": [
    { "expr": "op_node_default_p2p_peer_count", "legendFormat": "__auto" }
   ]
  },
  { "title": "Builder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Builder Request Duration (Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(op_node_default_sequencer_builder_request_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(op_node_default_sequencer_builder_request_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(op_node_default_sequencer_builder_request_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(op_node_default_sequencer_builder_request_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(op_node_default_sequencer_builder_request_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Building Diff Duration (Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(op_node_default_sequencer_building_diff_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(op_node_default_sequencer_building_diff_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(op_node_default_sequencer_building_diff_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(op_node_default_sequencer_building_diff_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(op_node_default_sequencer_building_diff_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Payload Gas",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "op_node_default_sequencer_payload_gas",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Sequenced Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(op_node_default_transactions_sequenced_source_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Builder Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(op_node_default_sequencer_builder_request_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Builder Request Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(op_node_default_sequencer_builder_request_errors[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Builder Request Timeout Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(op_node_default_sequencer_builder_request_timeout[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Payloads Inserted Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(op_node_default_sequencer_payload_inserted[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "All RPC Client Request Duration (Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(op_node_default_rpc_client_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(op_node_default_rpc_client_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(op_node_default_rpc_client_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(op_node_default_rpc_client_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(op_node_default_rpc_client_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L1 RPC Request Duration (Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(op_node_default_l1_request_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(op_node_default_l1_request_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(op_node_default_l1_request_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(op_node_default_l1_request_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(op_node_default_l1_request_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Engine RPC Request Duration (99th Percentiles)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(op_node_default_rpc_client_request_duration_seconds_bucket{method=\"engine_forkchoiceUpdatedV3\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(op_node_default_rpc_client_request_duration_seconds_bucket{method=\"engine_getPayloadV2\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(op_node_default_rpc_client_request_duration_seconds_bucket{method=\"engine_newPayloadV2\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OP RPC Request Duration (99th Percentiles)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(op_node_default_rpc_server_request_duration_seconds_bucket{method=\"optimism_outputAtBlock\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(op_node_default_rpc_server_request_duration_seconds_bucket{method=\"optimism_rollupConfig\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(op_node_default_rpc_server_request_duration_seconds_bucket{method=\"optimism_safeHeadAtL1Block\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(op_node_default_rpc_server_request_duration_seconds_bucket{method=\"optimism_syncStatus\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All RPC Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(__name__) (rate(op_node_default_rpc_client_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L1 RPC Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(op_node_default_l1_request_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Engine RPC Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(op_node_default_rpc_client_requests_total{method=\"engine_forkchoiceUpdatedV3\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(op_node_default_rpc_client_requests_total{method=\"engine_getPayloadV2\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(op_node_default_rpc_client_requests_total{method=\"engine_newPayloadV2\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OP RPC Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(op_node_default_rpc_server_request_duration_seconds_count{method=\"optimism_outputAtBlock\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(op_node_default_rpc_server_request_duration_seconds_count{method=\"optimism_rollupConfig\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(op_node_default_rpc_server_request_duration_seconds_count{method=\"optimism_safeHeadAtL1Block\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(op_node_default_rpc_server_request_duration_seconds_count{method=\"optimism_syncStatus\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "P2P", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "P2P Request Duration (Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(op_node_default_p2p_req_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(op_node_default_p2p_req_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(op_node_default_p2p_req_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(op_node_default_p2p_req_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(op_node_default_p2p_req_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(op_node_default_p2p_req_duration_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}