[package]
name = "kona-sp1-super-aggregation"
version = "0.0.1"
publish = false
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
bincode.workspace = true
kona-sp1-client-utils.workspace = true
sha2.workspace = true
sp1-lib.workspace = true
sp1-zkvm.workspace = true

[dev-dependencies]
kona-sp1-client-utils = { workspace = true, features = ["aggregation-test-utils"] }

[lints]
workspace = true
