// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RollupBoostControl is an autogenerated mock type for the RollupBoostControl type
type RollupBoostControl struct {
	mock.Mock
}

// GetExecutionMode provides a mock function with given fields: ctx
func (_m *RollupBoostControl) GetExecutionMode(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExecutionMode")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetExecutionMode provides a mock function with given fields: ctx, enabled
func (_m *RollupBoostControl) SetExecutionMode(ctx context.Context, enabled bool) error {
	ret := _m.Called(ctx, enabled)

	if len(ret) == 0 {
		panic("no return value specified for SetExecutionMode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) error); ok {
		r0 = rf(ctx, enabled)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRollupBoostControl creates a new instance of RollupBoostControl. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRollupBoostControl(t interface {
	mock.TestingT
	Cleanup(func())
}) *RollupBoostControl {
	mock := &RollupBoostControl{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
