#!/bin/bash
set -euo pipefail

SUMMARY_DIR=test/kontrol/proofs/utils

for summary in DeploymentSummary DeploymentSummaryFaultProofs; do
    echo "Generate ${SUMMARY_DIR}/${summary}.sol"
    cat <<EOF > "${SUMMARY_DIR}/${summary}.sol"
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.13;

import { Vm } from "forge-std/Vm.sol";

import { ${summary}Code } from "./${summary}Code.sol";

contract ${summary} is ${summary}Code {
    // Cheat code address, 0x7109709ECfa91a80626fF3989D68f67F5b1DD12D
    address private constant VM_ADDRESS = address(uint160(uint256(keccak256("hevm cheat code"))));
    Vm private constant vm = Vm(VM_ADDRESS);

    // Addresses required for compilation to work.
    address l1CrossDomainMessengerProxyAddress;
    address superchainConfigProxyAddress;
    address l1ERC721BridgeProxyAddress;
    address l1StandardBridgeProxyAddress;
    address optimismPortalProxyAddress;

    function recreateDeployment() public {
        // Will be generated by Kontrol
        revert("DeploymentSummary: must generate with Kontrol");
    }
}
EOF

echo "Generate ${SUMMARY_DIR}/${summary}Code.sol"
cat <<EOF > "${SUMMARY_DIR}/${summary}Code.sol"
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.13;

contract ${summary}Code {
    // Will be generated by Kontrol
}
EOF

done
