#!/usr/bin/env python3
"""Side-by-side comparison of three brotli decoders on the same truncated
brotli stream:

  - Rust `brotli` crate (high-level Reader API)
  - Go `andybalholm/brotli`
  - Go `github.com/google/brotli/go/cbrotli` (cgo to reference C)

The compressed bytes come from one source (cbrotli) so all three see identical input.
"""

import argparse
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))


def run_capture(cmd, **kwargs):
    p = subprocess.run(cmd, capture_output=True, text=True, check=False, **kwargs)
    if p.returncode != 0:
        print(f"command failed: {cmd}\n--stderr--\n{p.stderr}\n--stdout--\n{p.stdout}", file=sys.stderr)
        sys.exit(1)
    return p.stdout


def parse_lines(out):
    rows = {}
    for line in out.splitlines():
        parts = line.split()
        if len(parts) < 3:
            continue
        try:
            trunc = int(parts[0])
        except ValueError:
            continue
        status = parts[1]
        try:
            out_bytes = int(parts[2])
        except ValueError:
            continue
        rows[trunc] = (status, out_bytes)
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--hex", help="hex-encoded compressed brotli bytes; if omitted, generated by cbrotli")
    args = ap.parse_args()

    hex_str = args.hex
    if hex_str is None:
        # Use cbrotli to generate a stream that the C reference can certainly decode.
        out = run_capture(["go", "run", os.path.join(ROOT, "spec_check_google")])
        for line in out.splitlines():
            if line.startswith("compressed:"):
                hex_str = line.split("(")[1].rstrip(")")
                break
        if hex_str is None:
            print("could not extract compressed hex from cbrotli probe")
            sys.exit(1)
    print(f"using {len(hex_str)//2}-byte compressed stream")

    rust_out = run_capture(
        [os.path.join(ROOT, "spec_check_rust", "target", "release", "spec-check-rust"), hex_str]
    )
    andy_out = run_capture(["go", "run", os.path.join(ROOT, "spec_check"), hex_str])
    google_out = run_capture(["go", "run", os.path.join(ROOT, "spec_check_google"), hex_str])

    rust_rows = parse_lines(rust_out)
    andy_rows = parse_lines(andy_out)
    google_rows = parse_lines(google_out)

    truncs = sorted(set(rust_rows) | set(andy_rows) | set(google_rows), reverse=True)

    print(f"\n{'trunc':<6} | {'rust crate':<22} | {'andybalholm':<22} | {'google/brotli (cgo)':<22}")
    print("-" * 90)
    rust_accept = andy_accept = google_accept = 0
    for t in truncs:
        rust = rust_rows.get(t, ("--", 0))
        andy = andy_rows.get(t, ("--", 0))
        goog = google_rows.get(t, ("--", 0))
        if rust[0] == "Ok":
            rust_accept += 1
        if andy[0] == "Ok":
            andy_accept += 1
        if goog[0] == "Ok":
            google_accept += 1
        print(
            f"{t:<6} | {rust[0]:<10} ({rust[1]:>4}b)    | "
            f"{andy[0]:<10} ({andy[1]:>4}b)    | "
            f"{goog[0]:<10} ({goog[1]:>4}b)"
        )
    print("-" * 90)
    print(f"truncations accepted as clean EOF: rust={rust_accept}  andybalholm={andy_accept}  google_cbrotli={google_accept}")


if __name__ == "__main__":
    main()
