# syntax = docker/dockerfile:1.2
FROM docker.io/library/golang:1.20-alpine3.17 AS builder

RUN apk --no-cache add build-base linux-headers git bash ca-certificates libstdc++

ADD . /app
RUN cd /app/op-chain-ops && go build -o ./bin/inject-state ./cmd/inject-state/main.go

FROM alpine:3.13

RUN apk add --no-cache ca-certificates jq curl libgcc libstdc++
COPY --from=builder /app/op-chain-ops/bin /usr/local/bin/
