[package]
name = "kona-node-service-v3"
description = "Experimental core service architecture for the Kona consensus node"
version = "0.1.0"
publish = false
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace
kona-engine.workspace = true
kona-genesis.workspace = true

# Alloy
alloy-rpc-types-engine.workspace = true
alloy-transport.workspace = true
op-alloy-rpc-types-engine.workspace = true

# General
thiserror.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "sync"] }
