//! Shared pattern for implementing [`crate::Hardfork`] from a NUT bundle constructor.

/// Implements [`crate::Hardfork`] for a fork type backed by a NUT bundle constructor
/// generated by `build.rs`.
///
/// Given a type and a `fn() -> NutBundle` returning the bundle, this generates
/// `txs` and `upgrade_gas` — EIP-2718 encoding each deposit transaction and
/// summing per-tx gas.
///
/// Usage at a fork site:
///
/// ```ignore
/// include!(concat!(env!("OUT_DIR"), "/karst_nut_bundle.rs"));
/// pub struct Karst;
/// impl_hardfork_from_bundle!(Karst, karst_nut_bundle);
/// ```
macro_rules! impl_hardfork_from_bundle {
    ($ty:ident, $bundle_fn:ident) => {
        impl $crate::Hardfork for $ty {
            fn txs(&self) -> impl ::core::iter::Iterator<Item = ::alloy_primitives::Bytes> + '_ {
                use ::alloy_eips::eip2718::Encodable2718;
                let bundle = $bundle_fn();
                let deposits = bundle.to_deposit_transactions().unwrap_or_else(|e| {
                    panic!("{} NUT bundle is invalid: {:?}", ::core::stringify!($ty), e)
                });
                deposits.into_iter().map(|tx| {
                    let mut encoded = ::alloc::vec::Vec::new();
                    tx.encode_2718(&mut encoded);
                    ::alloy_primitives::Bytes::from(encoded)
                })
            }

            fn upgrade_gas(&self) -> u64 {
                $bundle_fn().total_gas()
            }
        }
    };
}
