{
 "title": "op-interop-mon",
 "description": "add version",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values({service=\"interop-mon\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_interop_mon_default_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VALID Executing / Initiating Messages by ChainID",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum by(chain_id) (op_interop_mon_default_executing_messages{status=\"valid\"})",
     "legendFormat": "{{chain_id}}-exec"
    },
    {
     "expr": "sum by(chain_id) (op_interop_mon_default_initiating_messages{status=\"valid\"})",
     "legendFormat": "{{chain_id}}-init"
    }
   ]
  },
  {
   "title": "INVALID Executing / Initiating Messages by ChainID",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(chain_id) (op_interop_mon_default_executing_messages{instance=\"$instance\", status=\"invalid\"})",
     "legendFormat": "{{chain_id}}-exec"
    },
    {
     "expr": "sum by(chain_id) (op_interop_mon_default_initiating_messages{instance=\"$instance\", status=\"invalid\"})",
     "legendFormat": "{{chain_id}}-init"
    }
   ]
  }
 ]
}