#!/usr/bin/env bash
# Recompile SuperchainETHBridge with the repository's DEFAULT foundry profile, validate the
# artifact (compiler version, settings, init-code hash vs snapshots/semver-lock.json) BEFORE
# replacing anything, then record it and regenerate the Lean bytecode (BridgeEvm/Bytecode.lean),
# the EquiVM block summaries (BridgeEvm/Blocks/) and their import point (BridgeEvm/AllBlocks.lean).
# Adapted from ../evm-lean/scripts/regen.sh. Needs forge, jq, cast, python3, and `lake build`
# (or `lake update`) done once so that .lake/packages/EquiVM exists. Then run `lake build`.
set -euo pipefail
HERE=$(cd "$(dirname "$0")/.." && pwd)
CB=$(cd "$HERE/../../../.." && pwd)            # packages/contracts-bedrock
NAME=SuperchainETHBridge
EXPECT_SOLC="0.8.15+commit.e14f2714"
# All compiler settings except remappings/target, keys sorted (solc 0.8.15 caps evmVersion at
# london, which the default profile's `cancun` resolves to for this file).
EXPECT_SETTINGS='{"evmVersion":"london","libraries":{},"metadata":{"bytecodeHash":"none"},"optimizer":{"enabled":true,"runs":999999}}'

# Use the default profile only; drop any environment overrides of compiler settings.
for v in $(env | grep -o '^FOUNDRY_[A-Z_]*' || true); do unset "$v"; done
export FOUNDRY_PROFILE=default
echo "forge: $(forge --version | head -1)"
echo "commit: $(git -C "$CB" rev-parse HEAD)"

OUT=$(mktemp -d)
(cd "$CB" && forge build "src/L2/$NAME.sol" --out "$OUT" > /dev/null)
A="$OUT/$NAME.sol/$NAME.json"
S="$OUT/SafeSend.sol/SafeSend.json"
SOLC=$(jq -r .metadata.compiler.version "$A")
SETTINGS=$(jq -cS '.metadata.settings | del(.remappings, .compilationTarget)' "$A")
INIT=$(cast keccak "$(jq -r .bytecode.object "$A")")
LOCK=$(jq -r ".\"src/L2/$NAME.sol:$NAME\".initCodeHash" "$CB/snapshots/semver-lock.json")
echo "solc:             $SOLC"
echo "settings:         $SETTINGS"
echo "keccak(initcode): $INIT"
echo "semver-lock:      $LOCK"
[ "$SOLC" = "$EXPECT_SOLC" ] || { echo "unexpected solc $SOLC"; exit 1; }
[ "$SETTINGS" = "$EXPECT_SETTINGS" ] || { echo "unexpected settings $SETTINGS"; exit 1; }
[ "$INIT" = "$LOCK" ] || { echo "init-code hash differs from semver-lock.json"; exit 1; }

mkdir -p "$HERE/bytecode"
jq -r .deployedBytecode.object "$A" > "$HERE/bytecode/$NAME.runtime.hex"
jq -r .bytecode.object "$S" > "$HERE/bytecode/SafeSend.creation.hex"
echo "keccak(runtime):  $(cast keccak "$(cat "$HERE/bytecode/$NAME.runtime.hex")")"
echo "keccak(SafeSend initcode): $(cast keccak "$(cat "$HERE/bytecode/SafeSend.creation.hex")")"
rm -rf "$OUT"
# SafeSend's creation code must be embedded in the bridge runtime at offset 3030 (the CODECOPY
# source of `new SafeSend`, used by BridgeEvm/TraceCreate.lean and `safeSendInitcode`).
python3 - "$HERE/bytecode/$NAME.runtime.hex" "$HERE/bytecode/SafeSend.creation.hex" <<'PY'
import sys
rt = bytes.fromhex(open(sys.argv[1]).read().strip()[2:])
ss = bytes.fromhex(open(sys.argv[2]).read().strip()[2:])
i = rt.find(ss)
print(f"runtime: {len(rt)} bytes; SafeSend initcode ({len(ss)} bytes) at offset {i}")
sys.exit(0 if i == 3030 else 1)
PY

cd "$HERE"
python3 scripts/gen_bytecode.py "bytecode/$NAME.runtime.hex" BridgeEvm/Bytecode.lean ethbridgeRuntime
rm -rf BridgeEvm/Blocks && mkdir -p BridgeEvm/Blocks
python3 .lake/packages/EquiVM/scripts/generate_rd_blocks.py "bytecode/$NAME.runtime.hex" \
  --name ethbridge --code-term BridgeEvm.ethbridgeRuntime --bytecode-import BridgeEvm.Bytecode \
  --output BridgeEvm/Blocks/RuntimeBlocks.lean --shard-size 20 > /dev/null
perl -pi -e "s/native_decide/evm_kdecide/g" BridgeEvm/Blocks/RuntimeBlocks_*.lean  # kernel-checked facts
# One import point for all shards.
{ echo "-- Generated by scripts/regen.sh: imports every block-summary shard."
  for f in BridgeEvm/Blocks/RuntimeBlocks_*.lean; do m=${f%.lean}; echo "import ${m//\//.}"; done
} > BridgeEvm/AllBlocks.lean
echo "now run: lake build"
echo "If the pcs moved, re-trace with scripts/trace_paths.py and update the block names in BridgeEvm/Trace*.lean."
