import '../justfiles/go.just'

# Build ldflags string
_LDFLAGSSTRING := "'" + trim(
    "-X main.GitCommit=" + GITCOMMIT + " " + \
    "-X main.GitDate=" + GITDATE + " " + \
    "-X main.Version=" + VERSION + " " + \
    "") + "'"

BINARY := justfile_directory() + "/bin/op-wheel"
PACKAGE := justfile_directory() + "/cmd"

# Build op-wheel binary
op-wheel: (go_build BINARY PACKAGE "-ldflags" _LDFLAGSSTRING)