//! Per-chain genesis + metadata reader, backed by build.rs-generated `OUT_DIR`
//! artifacts extracted from the `op-superchain` zip.

use crate::superchain::chain_metadata::{ChainMetadata, to_genesis_chain_config};
use alloc::{format, string::String, vec::Vec};
use alloy_genesis::Genesis;

/// Genesis JSON sanity ceiling — matches the previous on-disk limit.
const MAX_GENESIS_SIZE: usize = 100 * 1024 * 1024;

/// The zstd dictionary used to compress every per-chain genesis in the
/// embedded zip. Same dictionary the Go side and op-superchain ship.
const DICTIONARY: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/dictionary"));

#[derive(Debug, thiserror::Error)]
pub(crate) enum SuperchainConfigError {
    /// JSON deserialization failed.
    #[error("Error deserializing JSON: {0}")]
    JsonError(#[from] serde_json::Error),
    /// No genesis bytes are bundled for the requested chain.
    #[error("No genesis bytes registered for `{0}-{1}`")]
    NoGenesis(String, String),
    /// No config JSON is bundled for the requested chain.
    #[error("No config JSON registered for `{0}-{1}`")]
    NoConfig(String, String),
    /// Decompression of the zstd genesis failed.
    #[error("Error decompressing genesis: {0}")]
    DecompressError(String),
}

/// Reads the [`Genesis`] for the given `(name, environment)` pair.
pub(crate) fn read_superchain_genesis(
    name: &str,
    environment: &str,
) -> Result<Genesis, SuperchainConfigError> {
    let compressed = generated::genesis_bytes(name, environment)
        .ok_or_else(|| SuperchainConfigError::NoGenesis(name.into(), environment.into()))?;
    let genesis_bytes = decompress_zstd(compressed)?;
    if genesis_bytes.len() > MAX_GENESIS_SIZE {
        return Err(SuperchainConfigError::DecompressError(format!(
            "genesis exceeds {MAX_GENESIS_SIZE}-byte limit"
        )));
    }
    // The "config" field in the source SR genesis is not consistently
    // populated (see https://github.com/ethereum-optimism/superchain-registry/issues/901),
    // so we drop it before deserialising and reconstruct from chain metadata
    // afterwards.
    let mut value: serde_json::Value = serde_json::from_slice(&genesis_bytes)?;
    if let Some(obj) = value.as_object_mut() {
        obj.remove("config");
    }
    let mut genesis: Genesis = serde_json::from_value(value)?;
    genesis.config = to_genesis_chain_config(&read_superchain_metadata(name, environment)?);

    Ok(genesis)
}

/// Reads the narrow [`ChainMetadata`] for the given chain.
fn read_superchain_metadata(
    name: &str,
    environment: &str,
) -> Result<ChainMetadata, SuperchainConfigError> {
    let json = generated::config_str(name, environment)
        .ok_or_else(|| SuperchainConfigError::NoConfig(name.into(), environment.into()))?;
    Ok(serde_json::from_str(json)?)
}

fn decompress_zstd(compressed: &[u8]) -> Result<Vec<u8>, SuperchainConfigError> {
    use std::io::Read;
    let mut decoder = zstd::stream::Decoder::with_dictionary(compressed, DICTIONARY)
        .map_err(|e| SuperchainConfigError::DecompressError(format!("init: {e}")))?;
    let mut out = Vec::new();
    decoder
        .read_to_end(&mut out)
        .map_err(|e| SuperchainConfigError::DecompressError(format!("read: {e}")))?;
    Ok(out)
}

/// Lookup tables generated by build.rs from `op_superchain::supported_chains()`.
mod generated {
    include!(concat!(env!("OUT_DIR"), "/lookups.rs"));
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{SUPPORTED_CHAINS, generated_chain_value_parser, superchain::Superchain};
    use alloy_chains::NamedChain;
    use alloy_op_hardforks::{
        BASE_MAINNET_CANYON_TIMESTAMP, BASE_MAINNET_ECOTONE_TIMESTAMP,
        BASE_MAINNET_ISTHMUS_TIMESTAMP, BASE_MAINNET_JOVIAN_TIMESTAMP,
        BASE_SEPOLIA_CANYON_TIMESTAMP, BASE_SEPOLIA_ECOTONE_TIMESTAMP,
        BASE_SEPOLIA_ISTHMUS_TIMESTAMP, BASE_SEPOLIA_JOVIAN_TIMESTAMP, OP_MAINNET_CANYON_TIMESTAMP,
        OP_MAINNET_ECOTONE_TIMESTAMP, OP_MAINNET_ISTHMUS_TIMESTAMP, OP_MAINNET_JOVIAN_TIMESTAMP,
        OP_SEPOLIA_CANYON_TIMESTAMP, OP_SEPOLIA_ECOTONE_TIMESTAMP, OP_SEPOLIA_ISTHMUS_TIMESTAMP,
        OP_SEPOLIA_JOVIAN_TIMESTAMP, OpHardfork,
    };
    use reth_optimism_primitives::L2_TO_L1_MESSAGE_PASSER_ADDRESS;

    #[test]
    fn test_read_superchain_genesis() {
        let genesis = read_superchain_genesis("unichain", "mainnet").unwrap();
        assert_eq!(genesis.config.chain_id, 130);
        assert_eq!(genesis.timestamp, 1730748359);
        assert!(genesis.alloc.contains_key(&L2_TO_L1_MESSAGE_PASSER_ADDRESS));
    }

    #[test]
    fn test_read_superchain_genesis_with_workaround() {
        let genesis = read_superchain_genesis("funki", "mainnet").unwrap();
        assert_eq!(genesis.config.chain_id, 33979);
        assert_eq!(genesis.timestamp, 1721211095);
        assert!(genesis.alloc.contains_key(&L2_TO_L1_MESSAGE_PASSER_ADDRESS));
    }

    #[test]
    fn test_read_superchain_metadata() {
        let chain_config = read_superchain_metadata("funki", "mainnet").unwrap();
        assert_eq!(chain_config.chain_id, 33979);
    }

    #[test]
    fn test_genesis_exists_for_all_available_chains() {
        for &chain in Superchain::ALL {
            let genesis = read_superchain_genesis(chain.name(), chain.environment());
            assert!(
                genesis.is_ok(),
                "Genesis not found for chain: {}-{}",
                chain.name(),
                chain.environment()
            );
        }
    }

    #[test]
    fn test_hardfork_timestamps() {
        for &chain in SUPPORTED_CHAINS {
            let metadata = generated_chain_value_parser(chain).unwrap();

            match metadata.chain().named() {
                Some(NamedChain::Optimism) => {
                    assert_eq!(
                        metadata.hardforks.get(OpHardfork::Jovian).unwrap().as_timestamp().unwrap(),
                        OP_MAINNET_JOVIAN_TIMESTAMP
                    );
                    assert_eq!(
                        metadata
                            .hardforks
                            .get(OpHardfork::Isthmus)
                            .unwrap()
                            .as_timestamp()
                            .unwrap(),
                        OP_MAINNET_ISTHMUS_TIMESTAMP
                    );
                    assert_eq!(
                        metadata.hardforks.get(OpHardfork::Canyon).unwrap().as_timestamp().unwrap(),
                        OP_MAINNET_CANYON_TIMESTAMP
                    );
                    assert_eq!(
                        metadata
                            .hardforks
                            .get(OpHardfork::Ecotone)
                            .unwrap()
                            .as_timestamp()
                            .unwrap(),
                        OP_MAINNET_ECOTONE_TIMESTAMP
                    );
                }
                Some(NamedChain::OptimismSepolia) => {
                    assert_eq!(
                        metadata.hardforks.get(OpHardfork::Jovian).unwrap().as_timestamp().unwrap(),
                        OP_SEPOLIA_JOVIAN_TIMESTAMP
                    );
                    assert_eq!(
                        metadata
                            .hardforks
                            .get(OpHardfork::Isthmus)
                            .unwrap()
                            .as_timestamp()
                            .unwrap(),
                        OP_SEPOLIA_ISTHMUS_TIMESTAMP
                    );
                    assert_eq!(
                        metadata.hardforks.get(OpHardfork::Canyon).unwrap().as_timestamp().unwrap(),
                        OP_SEPOLIA_CANYON_TIMESTAMP
                    );
                    assert_eq!(
                        metadata
                            .hardforks
                            .get(OpHardfork::Ecotone)
                            .unwrap()
                            .as_timestamp()
                            .unwrap(),
                        OP_SEPOLIA_ECOTONE_TIMESTAMP
                    );
                }
                Some(NamedChain::Base) => {
                    assert_eq!(
                        metadata.hardforks.get(OpHardfork::Jovian).unwrap().as_timestamp().unwrap(),
                        BASE_MAINNET_JOVIAN_TIMESTAMP
                    );
                    assert_eq!(
                        metadata
                            .hardforks
                            .get(OpHardfork::Isthmus)
                            .unwrap()
                            .as_timestamp()
                            .unwrap(),
                        BASE_MAINNET_ISTHMUS_TIMESTAMP
                    );
                    assert_eq!(
                        metadata.hardforks.get(OpHardfork::Canyon).unwrap().as_timestamp().unwrap(),
                        BASE_MAINNET_CANYON_TIMESTAMP
                    );
                    assert_eq!(
                        metadata
                            .hardforks
                            .get(OpHardfork::Ecotone)
                            .unwrap()
                            .as_timestamp()
                            .unwrap(),
                        BASE_MAINNET_ECOTONE_TIMESTAMP
                    );
                }
                Some(NamedChain::BaseSepolia) => {
                    assert_eq!(
                        metadata.hardforks.get(OpHardfork::Jovian).unwrap().as_timestamp().unwrap(),
                        BASE_SEPOLIA_JOVIAN_TIMESTAMP
                    );
                    assert_eq!(
                        metadata
                            .hardforks
                            .get(OpHardfork::Isthmus)
                            .unwrap()
                            .as_timestamp()
                            .unwrap(),
                        BASE_SEPOLIA_ISTHMUS_TIMESTAMP
                    );
                    assert_eq!(
                        metadata.hardforks.get(OpHardfork::Canyon).unwrap().as_timestamp().unwrap(),
                        BASE_SEPOLIA_CANYON_TIMESTAMP
                    );
                    assert_eq!(
                        metadata
                            .hardforks
                            .get(OpHardfork::Ecotone)
                            .unwrap()
                            .as_timestamp()
                            .unwrap(),
                        BASE_SEPOLIA_ECOTONE_TIMESTAMP
                    );
                }
                _ => {}
            }
        }
    }
}
