[package]
name = "op-revm"
description = "Optimism variant of Revm"
version = "15.0.0"
authors = ["Dragan Rakita <dragan0rakita@gmail.com>"]
edition = "2021"
keywords = ["revm", "evm", "ethereum", "blockchain", "no_std"]
license = "MIT"
repository = "https://github.com/bluealloy/revm"
readme = "README.md"
rust-version = "1.88.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints.rust]
missing_debug_implementations = "warn"
missing_docs = "warn"
rust_2018_idioms = { level = "deny", priority = -1 }
unreachable_pub = "warn"
unused_must_use = "deny"

[lints.rustdoc]
all = "warn"

[dependencies]
# revm
revm = { version = "34.0.0", default-features = false }
auto_impl = "1.3.0"

# Optional
serde = { version = "1.0", default-features = false, features = ["derive", "rc"], optional = true }

[dev-dependencies]
rstest = "0.26.0"
alloy-sol-types = { version = "1.5.2", default-features = false }
sha2 = { version = "0.10.9", default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc", "preserve_order"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
alloy-primitives = { version = "1.5.2", default-features = false }
revm = { version = "34.0.0", features = ["serde"] }
op-revm = { path = ".", features = ["serde"] }

[features]
default = ["std", "c-kzg", "secp256k1", "portable", "blst"]
std = [
	"serde?/std",
	"revm/std",
	"alloy-sol-types/std",
	"sha2/std",
	"serde_json/std",
	"alloy-primitives/std",
]
hashbrown = ["revm/hashbrown"]
serde = [
	"dep:serde",
	"revm/serde",
	"alloy-primitives/serde",
	"op-revm/serde"
]
portable = ["revm/portable"]

dev = [
	"memory_limit",
	"optional_balance_check",
	"optional_block_gas_limit",
	"optional_eip3541",
	"optional_eip3607",
	"optional_no_base_fee",
]
memory_limit = ["revm/memory_limit"]
optional_balance_check = ["revm/optional_balance_check"]
optional_block_gas_limit = ["revm/optional_block_gas_limit"]
optional_eip3541 = ["revm/optional_eip3541"]
optional_eip3607 = ["revm/optional_eip3607"]
optional_no_base_fee = ["revm/optional_no_base_fee"]
optional_fee_charge = ["revm/optional_fee_charge"]

# See comments in `revm-precompile`
secp256k1 = ["revm/secp256k1"]
c-kzg = ["revm/c-kzg"]
blst = ["revm/blst"]
bn = ["revm/bn"]
