[package]
name = "kona-sp1-proof-utils"
version = "0.0.1"
publish = false
license.workspace = true
edition.workspace = true

[dependencies]

# local
kona-sp1-elfs.workspace = true
kona-sp1-ethereum-host-utils.workspace = true
kona-sp1-host-utils.workspace = true

# general
tracing.workspace = true

[lints]
workspace = true
