export const CORE_CONFIG_KEYS = {
  ETHEREUM_ENDPOINT: 'ETHEREUM_ENDPOINT',
  BASE_DB_PATH: 'BASE_DB_PATH',
  DB_BACKEND: 'DB_BACKEND',
  RPC_SERVER_PORT: 'RPC_SERVER_PORT',
  RPC_SERVER_HOSTNAME: 'RPC_SERVER_HOSTNAME',
}
