#!/usr/bin/env bash
# Recompile L2ToL2CrossDomainMessenger with the repository's DEFAULT foundry profile, validate the
# artifact (compiler version, settings, init-code hash vs snapshots/semver-lock.json) BEFORE
# replacing anything, then record it and regenerate the Lean bytecode (ExpiryEvm/Bytecode.lean),
# the EquiVM block summaries (ExpiryEvm/Blocks/) and their import point (ExpiryEvm/AllBlocks.lean).
# Needs forge, jq, cast, python3, and `lake build` (or `lake update`) done once so that
# .lake/packages/EquiVM exists; then run `lake build`.
set -euo pipefail
HERE=$(cd "$(dirname "$0")/.." && pwd)
CB=$(cd "$HERE/../../../.." && pwd)            # packages/contracts-bedrock
NAME=L2ToL2CrossDomainMessenger
EXPECT_SOLC="0.8.25+commit.b61c2a91"
# All compiler settings except remappings/target, keys sorted: any extra setting (viaIR,
# optimizer details, libraries, …) fails the check.
EXPECT_SETTINGS='{"evmVersion":"cancun","libraries":{},"metadata":{"bytecodeHash":"none"},"optimizer":{"enabled":true,"runs":999999}}'

# Use the default profile only; drop any environment overrides of compiler settings.
for v in $(env | grep -o '^FOUNDRY_[A-Z_]*' || true); do unset "$v"; done
export FOUNDRY_PROFILE=default
echo "forge: $(forge --version | head -1)"

OUT=$(mktemp -d)
(cd "$CB" && forge build "src/L2/$NAME.sol" --out "$OUT" > /dev/null)
A="$OUT/$NAME.sol/$NAME.json"
SOLC=$(jq -r .metadata.compiler.version "$A")
SETTINGS=$(jq -cS '.metadata.settings | del(.remappings, .compilationTarget)' "$A")
INIT=$(cast keccak "$(jq -r .bytecode.object "$A")")
LOCK=$(jq -r ".\"src/L2/$NAME.sol:$NAME\".initCodeHash" "$CB/snapshots/semver-lock.json")
echo "solc:             $SOLC"
echo "settings:         $SETTINGS"
echo "keccak(initcode): $INIT"
echo "semver-lock:      $LOCK"
[ "$SOLC" = "$EXPECT_SOLC" ] || { echo "unexpected solc $SOLC"; exit 1; }
[ "$SETTINGS" = "$EXPECT_SETTINGS" ] || { echo "unexpected settings $SETTINGS"; exit 1; }
[ "$INIT" = "$LOCK" ] || { echo "init-code hash differs from semver-lock.json"; exit 1; }

# The messenger has no immutables (the expiry period is in storage, set by initialize), so the
# artifact's deployed bytecode is the code every deployment runs.
[ "$(jq -c '.deployedBytecode.immutableReferences // {}' "$A")" = "{}" ] \
  || { echo "unexpected immutables"; exit 1; }
mkdir -p "$HERE/bytecode"
jq -r .deployedBytecode.object "$A" > "$HERE/bytecode/$NAME.runtime.hex"
jq -r .bytecode.object "$A" > "$HERE/bytecode/$NAME.creation.hex"
echo "keccak(runtime):  $(cast keccak "$(cat "$HERE/bytecode/$NAME.runtime.hex")")"
cd "$HERE"
python3 scripts/gen_bytecode.py "bytecode/$NAME.runtime.hex" ExpiryEvm/Bytecode.lean
rm -rf ExpiryEvm/Blocks && mkdir -p ExpiryEvm/Blocks
python3 .lake/packages/EquiVM/scripts/generate_rd_blocks.py "bytecode/$NAME.runtime.hex" \
  --name l2tol2 --code-term ExpiryEvm.l2tol2Runtime --bytecode-import ExpiryEvm.Bytecode \
  --output ExpiryEvm/Blocks/RuntimeBlocks.lean --shard-size 20 > /dev/null
perl -pi -e "s/native_decide/evm_kdecide/g" ExpiryEvm/Blocks/RuntimeBlocks_*.lean  # kernel-checked facts (evm-lean-kernel)
# One import point for all shards (shard boundaries move when the bytecode changes).
{ echo "-- Generated by scripts/regen.sh: imports every block-summary shard."
  for f in ExpiryEvm/Blocks/RuntimeBlocks_*.lean; do m=${f%.lean}; echo "import ${m//\//.}"; done
} > ExpiryEvm/AllBlocks.lean
echo "now run: lake build"
echo "If the pcs moved, re-trace with scripts/trace_paths.py and update the block names in ExpiryEvm/Trace*.lean."
rm -rf "$OUT"
