#!/usr/bin/env bash
# Recompile L2ToL2CrossDomainMessenger with the repository's DEFAULT foundry profile, validate the
# artifact (compiler version, settings, init-code hash vs snapshots/semver-lock.json) BEFORE
# replacing anything, then record it and regenerate the Lean bytecode (ExpiryEvm/Bytecode.lean),
# the EquiVM block summaries (ExpiryEvm/Blocks/) and their import point (ExpiryEvm/AllBlocks.lean).
# Needs forge, jq, cast, python3, and `lake build` (or `lake update`) done once so that
# .lake/packages/EquiVM exists. Afterwards set P_contract in ExpiryEvm/Spec.lean to the printed
# EXPIRY_PERIOD operand and run `lake build`.
set -euo pipefail
HERE=$(cd "$(dirname "$0")/.." && pwd)
CB=$(cd "$HERE/../../../.." && pwd)            # packages/contracts-bedrock
NAME=L2ToL2CrossDomainMessenger
EXPECT_SOLC="0.8.25+commit.b61c2a91"
EXPECT_SETTINGS='{"optimizer":{"enabled":true,"runs":999999},"evmVersion":"cancun","metadata":{"bytecodeHash":"none"}}'

# Use the default profile only; drop any environment overrides of compiler settings.
for v in $(env | grep -o '^FOUNDRY_[A-Z_]*' || true); do unset "$v"; done
export FOUNDRY_PROFILE=default
echo "forge: $(forge --version | head -1)"

OUT=$(mktemp -d)
(cd "$CB" && forge build "src/L2/$NAME.sol" --out "$OUT" > /dev/null)
A="$OUT/$NAME.sol/$NAME.json"
SOLC=$(jq -r .metadata.compiler.version "$A")
SETTINGS=$(jq -c '.metadata.settings | {optimizer, evmVersion, metadata}' "$A")
INIT=$(cast keccak "$(jq -r .bytecode.object "$A")")
LOCK=$(jq -r ".\"src/L2/$NAME.sol:$NAME\".initCodeHash" "$CB/snapshots/semver-lock.json")
echo "solc:             $SOLC"
echo "settings:         $SETTINGS"
echo "keccak(initcode): $INIT"
echo "semver-lock:      $LOCK"
[ "$SOLC" = "$EXPECT_SOLC" ] || { echo "unexpected solc $SOLC"; exit 1; }
[ "$SETTINGS" = "$EXPECT_SETTINGS" ] || { echo "unexpected settings $SETTINGS"; exit 1; }
[ "$INIT" = "$LOCK" ] || { echo "init-code hash differs from semver-lock.json"; exit 1; }

jq -r .deployedBytecode.object "$A" > "$HERE/artifacts/$NAME.runtime.hex"
jq -r .bytecode.object "$A" > "$HERE/artifacts/$NAME.creation.hex"
echo "keccak(runtime):  $(cast keccak "$(cat "$HERE/artifacts/$NAME.runtime.hex")")"
rm -rf "$OUT"

cd "$HERE"
python3 scripts/gen_bytecode.py "artifacts/$NAME.runtime.hex" ExpiryEvm/Bytecode.lean
rm -rf ExpiryEvm/Blocks && mkdir -p ExpiryEvm/Blocks
python3 .lake/packages/EquiVM/scripts/generate_rd_blocks.py "artifacts/$NAME.runtime.hex" \
  --name l2tol2 --code-term ExpiryEvm.l2tol2Runtime --bytecode-import ExpiryEvm.Bytecode \
  --output ExpiryEvm/Blocks/RuntimeBlocks.lean --shard-size 20 > /dev/null
# One import point for all shards (shard boundaries move when the bytecode changes).
{ echo "-- Generated by scripts/regen.sh: imports every block-summary shard."
  for f in ExpiryEvm/Blocks/RuntimeBlocks_*.lean; do m=${f%.lean}; echo "import ${m//\//.}"; done
} > ExpiryEvm/AllBlocks.lean
echo "EXPIRY_PERIOD operands (PUSH3 in the runtime; set P_contract in ExpiryEvm/Spec.lean):"
cast disassemble "$(cat "artifacts/$NAME.runtime.hex")" | grep "PUSH3 " || true
echo "If the pcs moved, re-trace with scripts/trace_paths.py and update the block names in ExpiryEvm/Trace*.lean."
