[package]
name = "flashblocks-websocket-proxy"
version = "0.1.0"
edition.workspace = true
description = "Flashblocks Websocket Proxy is a service that subscribes to new Flashblocks broadcasts them to downstream RPC nodes"
rust-version.workspace = true
license.workspace = true
readme = "README.md"

[dependencies]
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "json", "fmt", "std"] }
clap = { workspace = true, features = ["derive", "env"] }
futures.workspace = true
thiserror.workspace = true
serde_json = { workspace = true, features = ["std"] }
metrics.workspace = true
metrics-derive.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-tungstenite = { workspace = true, features = ["native-tls"] }
metrics-exporter-prometheus = { workspace = true, features = [
    "http-listener",
] }
http.workspace = true
axum = { workspace = true, features = ["ws"] }
dotenvy.workspace = true
backoff.workspace = true
reqwest = { workspace = true, features = ["native-tls"] }

hostname.workspace = true
redis.workspace = true
uuid.workspace = true
tokio-util.workspace = true
brotli = { workspace = true, features = ["std"] }

[lib]
name = "websocket_proxy"

[dev-dependencies]
testcontainers.workspace = true
testcontainers-modules.workspace = true
redis-test.workspace = true

[features]
integration = []
