package cihistory

import (
	"fmt"
	"os"
	"time"

	"github.com/ethereum-optimism/optimism/ops/checks/freshness"
	"github.com/ethereum-optimism/optimism/ops/checks/graph"
	"gopkg.in/yaml.v3"
)

// WriteEdges adds EdgeObservedCorrelation edges to the graph, one per
// Correlation in the analysis. Edge source/target resolution uses the
// same sol:/go: prefix convention as the coverage ingestor.
//
// Each edge carries:
//   - Strength   = precision
//   - Confidence = scaled sample sufficiency (asymptotic to 1 as
//                  observations grow past MinObservationsForPrior)
//   - Properties: observations, failures, precision, window bounds,
//     generated_at, source_sha (if the file exists on disk at rootDir)
//
// rootDir may be empty — in that case source_sha is not stamped and
// freshness falls back to time-based decay.
func WriteEdges(g *graph.Graph, a *Analysis, rootDir string) (int, error) {
	generatedAt := time.Now().UTC().Format(time.RFC3339)
	windowStart := a.WindowStart.Format(time.RFC3339)
	windowEnd := a.WindowEnd.Format(time.RFC3339)

	added := 0
	for _, c := range a.Correlations {
		fromID := sourceFileToNodeID(c.File)
		toID := "check:" + c.CheckID
		if g.GetNode(fromID) == nil || g.GetNode(toID) == nil {
			continue
		}

		props := map[string]any{
			"observations": c.Observations,
			"failures":     c.Failures,
			"precision":    c.Precision,
			"generated_at": generatedAt,
		}
		if !a.WindowStart.IsZero() {
			props["window_start"] = windowStart
		}
		if !a.WindowEnd.IsZero() {
			props["window_end"] = windowEnd
		}
		if rootDir != "" {
			if rel := freshness.NodeIDToPath(fromID); rel != "" {
				if sha, err := freshness.HashFile(rootDir + "/" + rel); err == nil {
					props["source_sha"] = sha
				}
			}
		}

		if err := g.AddEdge(&graph.Edge{
			From:       fromID,
			To:         toID,
			Kind:       graph.EdgeObservedCorrelation,
			Source:     graph.SourceCIHistory,
			Confidence: sampleConfidence(c.Observations),
			Strength:   c.Precision,
			Properties: props,
		}); err == nil {
			added++
		}
	}
	return added, nil
}

// sampleConfidence scales a correlation's confidence by sample size.
// Maps MinObservationsForPrior (~20) to 1.0 and fewer observations to
// proportionally lower confidence. Keeps noisy edges from dominating
// well-sampled ones.
func sampleConfidence(obs int) float64 {
	const sufficientSample = 20.0
	c := float64(obs) / sufficientSample
	if c > 1.0 {
		return 1.0
	}
	return c
}

// LearnedPolicy is the minimal YAML shape the policy loader deep-merges.
// We deliberately emit only the priors — other fields stay at baseline
// unless the operator commits an override file.
type LearnedPolicy struct {
	PriorsByKind  map[string]float64 `yaml:"priors_by_kind,omitempty"`
	PriorsByCheck map[string]float64 `yaml:"priors_by_check,omitempty"`
}

// WriteLearnedPolicy writes the per-kind and per-check priors to a YAML
// file suitable for policy.Load() to layer on top of baseline.yaml.
//
// The file is written atomically: a sibling tempfile is created and
// renamed, so a reader never sees a half-written file.
func WriteLearnedPolicy(path string, a *Analysis) error {
	lp := LearnedPolicy{
		PriorsByKind:  a.PriorsByKind,
		PriorsByCheck: a.PriorsByCheck,
	}
	data, err := yaml.Marshal(&lp)
	if err != nil {
		return fmt.Errorf("marshal learned policy: %w", err)
	}

	header := fmt.Sprintf(`# learned.yaml — auto-generated by ` + "`" + `checks ingest ci-history` + "`" + `.
# Do not edit by hand; re-run ingestion to regenerate.
# Generated: %s
# Window:    %s → %s

`,
		time.Now().UTC().Format(time.RFC3339),
		a.WindowStart.Format(time.RFC3339),
		a.WindowEnd.Format(time.RFC3339),
	)

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, append([]byte(header), data...), 0o644); err != nil {
		return fmt.Errorf("writing learned policy: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("renaming learned policy: %w", err)
	}
	return nil
}

// sourceFileToNodeID maps a repo-relative path to a graph node ID,
// mirroring how adapters name source nodes.
func sourceFileToNodeID(path string) string {
	// Solidity: paths under packages/contracts-bedrock/ get stripped.
	const solPrefix = "packages/contracts-bedrock/"
	if len(path) > len(solPrefix) && path[:len(solPrefix)] == solPrefix {
		return "sol:" + path[len(solPrefix):]
	}
	// Go: best-effort — the graph's Go node IDs are import paths
	// (go:github.com/…). We can't derive those from a filesystem path
	// without parsing go.mod, so for Go source files we fall back to a
	// directory-level synthetic ID; the builder may not have such a
	// node, in which case WriteEdges drops the correlation silently.
	return "go:" + path
}
