FROM golang:1.18.0-alpine3.15 as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git jq bash

COPY go.mod /app/go.mod
COPY go.sum /app/go.sum

WORKDIR /app
RUN go mod download -x

COPY ./opnode /app/opnode

RUN go build -o ./bin/stateviz ./opnode/cmd/stateviz

FROM alpine:3.15

COPY --from=builder /app/bin/stateviz /usr/local/bin

CMD ["stateviz"]
