# TODO: Prefix all env vars with service name
# TODO: Allow specifing the image tag to use
version: "3"

services:
  # base service builder
  builder:
    image: ethereumoptimism/builder
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.monorepo
  
  deployer:
    image: ethereumoptimism/deployer
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.deployer
    entrypoint: ./deployer.sh
    environment:
        FRAUD_PROOF_WINDOW_SECONDS: 0
        L1_NODE_WEB3_URL: https://ropsten.infura.io/v3/dce7370de2f0471fb88b6c74339ae8c1
        # these keys are hardhat's first 2 accounts, DO NOT use in production
        DEPLOYER_PRIVATE_KEY: "0x754fde3f5e60ef2c7649061e06957c29017fe21032a8017132c0078e37f6193c"
        SEQUENCER_PRIVATE_KEY: "0x754fde3f5e60ef2c7649061e06957c29017fe21032a8017132c0078e37f6193c"
        # skip compilation when run in docker-compose, since the contracts
        # were already compiled in the builder step
        NO_COMPILE: 1
    ports:
        # expose the service to the host for getting the contract addrs
      - ${DEPLOYER_PORT:-8080}:8081

  dtl:
    depends_on:
      - deployer
      - l2geth
    image: ethereumoptimism/data-transport-layer
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.data-transport-layer
    # override with the dtl script and the env vars required for it
    entrypoint: ./dtl.sh
    env_file:
      -  ./envs/dtl.env
    # set the rest of the env vars for the network whcih do not
    # depend on the docker-compose setup
    environment:
        # used for setting the address manager address
        URL: https://metis-us-east-2-json.s3.us-east-2.amazonaws.com/addresses.json
        # connect to the 2 layers
        DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: https://ropsten.infura.io/v3/dce7370de2f0471fb88b6c74339ae8c1
        DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT: http://metis_l2_geth_mt_1.metisdao.sd.0:8545
        DATA_TRANSPORT_LAYER__L2_CHAIN_ID: 420
    ports:
      - ${DTL_PORT:-7878}:7878

  l2geth:
    depends_on:
      - deployer
    image: ethereumoptimism/l2geth
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.geth
    # override with the geth script and the env vars required for it
    entrypoint: sh ./geth.sh
    env_file:
      - ./envs/geth.env
    environment:
        ETH1_HTTP: https://ropsten.infura.io/v3/dce7370de2f0471fb88b6c74339ae8c1
        ROLLUP_STATE_DUMP_PATH: https://metis-us-east-2-json.s3.us-east-2.amazonaws.com/state-dump.latest.json
        # used for getting the addresses
        URL: https://metis-us-east-2-json.s3.us-east-2.amazonaws.com/addresses.json
        # connecting to the DTL
        # ROLLUP_CLIENT_HTTP: http://dtl:7878
        ROLLUP_CLIENT_HTTP: http://data_transport_layer_mt_4.metisdao.sd.0:7878
        ETH1_CTC_DEPLOYMENT_HEIGHT: 8
        RETRIES: 60
        ROLLUP_POLL_INTERVAL_FLAG: 30000ms
    ports:
      - ${L2GETH_HTTP_PORT:-8545}:8545
      - ${L2GETH_WS_PORT:-8546}:8546

  relayer:
    depends_on:
      - deployer
      - l2geth
    image: ethereumoptimism/message-relayer
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.message-relayer
    entrypoint: ./relayer.sh
    environment:
        L1_NODE_WEB3_URL: https://ropsten.infura.io/v3/dce7370de2f0471fb88b6c74339ae8c1
        L2_NODE_WEB3_URL: http://127.0.0.1:8545
        URL: https://metis-us-east-2-json.s3.us-east-2.amazonaws.com/addresses.json
        # a funded hardhat account
        L1_WALLET_KEY: "0x754fde3f5e60ef2c7649061e06957c29017fe21032a8017132c0078e37f6193c"
        RETRIES: 60
        POLLING_INTERVAL: 500
        GET_LOGS_INTERVAL: 500

  batch_submitter:
    depends_on:
      - deployer
      - l2geth
    image: ethereumoptimism/batch-submitter
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.batch-submitter
    entrypoint: ./batches.sh
    env_file:
      - ./envs/batches.env
    environment:
        L1_NODE_WEB3_URL: https://ropsten.infura.io/v3/dce7370de2f0471fb88b6c74339ae8c1
        L2_NODE_WEB3_URL: http://127.0.0.1:8545
        URL: https://metis-us-east-2-json.s3.us-east-2.amazonaws.com/addresses.json
        SEQUENCER_PRIVATE_KEY: "0x754fde3f5e60ef2c7649061e06957c29017fe21032a8017132c0078e37f6193c"