#!/usr/bin/env bash
# Regenerates L2ToL2Bytecodes.sol: the runtime bytecode of L2ToL2CrossDomainMessenger as compiled with the
# repo's own foundry.toml (default profile: solc 0.8.25, optimizer 999999 runs, evm cancun, bytecode_hash none)
# at two checkouts:
#   DEVELOP  the develop baseline (origin/develop c2fe2a991b by default), a separate git worktree
#   CURRENT  this checkout
# Usage: gen-bytecodes.sh <develop-contracts-bedrock-dir> [--check]
#   --check  regenerate into a temp file and fail if it differs from the committed L2ToL2Bytecodes.sol
# Create the develop checkout with:
#   git worktree add --detach ../develop c2fe2a991b && ln -s "$PWD/packages/contracts-bedrock/lib" \
#     ../develop/packages/contracts-bedrock/lib   # (or init its submodules)
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CURRENT="$(cd "$HERE/../../../.." && pwd)"
DEVELOP="${1:?usage: gen-bytecodes.sh <develop contracts-bedrock dir> [--check]}"
DEVELOP="$(cd "$DEVELOP" && pwd)"
MODE="${2:-}"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

build() { # $1 = contracts-bedrock dir, $2 = out name
  (cd "$1" && forge build src/L2/L2ToL2CrossDomainMessenger.sol --out "$TMP/$2" --cache-path "$TMP/cache-$2" >/dev/null)
  python3 - "$TMP/$2/L2ToL2CrossDomainMessenger.sol/L2ToL2CrossDomainMessenger.json" <<'PY'
import json, sys
j = json.load(open(sys.argv[1]))
m = j["metadata"]; m = json.loads(m) if isinstance(m, str) else m
s = m["settings"]
assert s["optimizer"] == {"enabled": True, "runs": 999999}, s["optimizer"]
assert s["evmVersion"] == "cancun", s["evmVersion"]
assert m["compiler"]["version"].startswith("0.8.25"), m["compiler"]["version"]
assert not j["deployedBytecode"].get("immutableReferences"), "unexpected immutables"
b = j["deployedBytecode"]["object"]
print(b[2:] if b.startswith("0x") else b)
PY
}

DEV_HEX="$(build "$DEVELOP" develop)"
CUR_HEX="$(build "$CURRENT" current)"
DEV_REV="$(git -C "$DEVELOP" rev-parse --short=10 HEAD)"
CUR_REV="$(git -C "$CURRENT" rev-parse --short=10 HEAD)$(git -C "$CURRENT" diff --quiet -- src || echo '+dirty')"
DEV_SHA="$(printf %s "$DEV_HEX" | sha256sum | cut -d' ' -f1)"
CUR_SHA="$(printf %s "$CUR_HEX" | sha256sum | cut -d' ' -f1)"

OUT="$TMP/L2ToL2Bytecodes.sol"
cat >"$OUT" <<EOF
// SPDX-License-Identifier: MIT
pragma solidity 0.8.25;

// GENERATED by gen-bytecodes.sh; do not edit. Runtime bytecode of L2ToL2CrossDomainMessenger built with
// the repo foundry.toml default profile (solc 0.8.25, optimizer 999999 runs, evm cancun, bytecode_hash none).
// The contract has no immutables, so this is exactly the code a deployment runs.
library L2ToL2Bytecodes {
    // develop baseline $DEV_REV, sha256(hex) =
    // $DEV_SHA
    bytes internal constant DEVELOP =
        hex"$DEV_HEX";

    // current checkout (sources at $CUR_REV), sha256(hex) =
    // $CUR_SHA
    bytes internal constant CURRENT =
        hex"$CUR_HEX";
}
EOF
printf %s "$DEV_HEX" >"$TMP/develop.runtime.hex"
printf %s "$CUR_HEX" >"$TMP/current.runtime.hex"

if [ "$MODE" = "--check" ]; then
  # Compare only the bytecode lines, so a different checkout revision label does not fail the check.
  if diff <(grep -E '^ +hex"' "$OUT") <(grep -E '^ +hex"' "$HERE/L2ToL2Bytecodes.sol") >/dev/null; then
    echo "L2ToL2Bytecodes.sol is up to date (develop $DEV_SHA, current $CUR_SHA)"
  else
    echo "L2ToL2Bytecodes.sol is STALE: rerun gen-bytecodes.sh" >&2
    exit 1
  fi
else
  cp "$OUT" "$HERE/L2ToL2Bytecodes.sol"
  cp "$TMP/develop.runtime.hex" "$TMP/current.runtime.hex" "$HERE/"
  echo "wrote L2ToL2Bytecodes.sol, develop.runtime.hex, current.runtime.hex (develop $DEV_SHA, current $CUR_SHA)"
fi
