#!/usr/bin/env bash
# Regenerates L2ToL2Bytecodes.sol: the runtime bytecode of L2ToL2CrossDomainMessenger as compiled with the
# repo's own foundry.toml (default profile: solc 0.8.25, optimizer 999999 runs, evm cancun, bytecode_hash none)
# at two checkouts. Neither messenger has immutables (asserted): the current one keeps its expiry period in
# storage, set by initialize, so the deployed bytecode is exactly the code a production deployment runs.
#   DEVELOP  the develop baseline (c9b441bac5 by default), a separate git worktree
#   CURRENT  this checkout
# It also generates mapRenamedError (E6 in L2ToL2Equivalence.t.sol), from both sources.
# Usage: gen-bytecodes.sh <develop-contracts-bedrock-dir> [--check]
#   --check  regenerate into a temp file and fail if it differs from the committed L2ToL2Bytecodes.sol
# Create the develop checkout with:
#   git worktree add --detach ../develop c9b441bac5 && ln -s "$PWD/packages/contracts-bedrock/lib" \
#     ../develop/packages/contracts-bedrock/lib   # (or init its submodules)
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CURRENT="$(cd "$HERE/../../../.." && pwd)"
DEVELOP="${1:?usage: gen-bytecodes.sh <develop contracts-bedrock dir> [--check]}"
DEVELOP="$(cd "$DEVELOP" && pwd)"
MODE="${2:-}"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

build() { # $1 = contracts-bedrock dir, $2 = out name
  (cd "$1" && forge build src/L2/L2ToL2CrossDomainMessenger.sol --out "$TMP/$2" --cache-path "$TMP/cache-$2" >/dev/null)
  python3 - "$TMP/$2/L2ToL2CrossDomainMessenger.sol/L2ToL2CrossDomainMessenger.json" <<'PY'
import json, sys
j = json.load(open(sys.argv[1]))
m = j["metadata"]; m = json.loads(m) if isinstance(m, str) else m
s = m["settings"]
assert s["optimizer"] == {"enabled": True, "runs": 999999}, s["optimizer"]
assert s["evmVersion"] == "cancun", s["evmVersion"]
assert m["compiler"]["version"].startswith("0.8.25"), m["compiler"]["version"]
refs = j["deployedBytecode"].get("immutableReferences") or {}
b = j["deployedBytecode"]["object"]
assert not refs, "unexpected immutables"
print(b[2:] if b.startswith("0x") else b)
PY
}

DEV_HEX="$(build "$DEVELOP" develop)"
CUR_HEX="$(build "$CURRENT" current)"
DEV_REV="$(git -C "$DEVELOP" rev-parse --short=10 HEAD)"
CUR_REV="$(git -C "$CURRENT" rev-parse --short=10 HEAD)$(git -C "$CURRENT" diff --quiet -- src || echo '+dirty')"
DEV_SHA="$(printf %s "$DEV_HEX" | sha256sum | cut -d' ' -f1)"
CUR_SHA="$(printf %s "$CUR_HEX" | sha256sum | cut -d' ' -f1)"

# E6: errors the current messenger renamed with its contract-name prefix. For each one whose
# unprefixed name (same parameter types) exists in develop's messenger, map the current selector to
# develop's, so revert data can be compared modulo the rename.
MAP_LINES=""
while read -r cur_sig dev_sig; do
  [ -n "$cur_sig" ] || continue
  cur_sel="$(cast sig "$cur_sig")"
  dev_sel="$(cast sig "$dev_sig")"
  MAP_LINES+="        if (_selector == ${cur_sel}) selector_ = ${dev_sel}; // ${cur_sig} -> ${dev_sig}"$'\n'
done < <(python3 - "$DEVELOP/src/L2/L2ToL2CrossDomainMessenger.sol" "$CURRENT/src/L2/L2ToL2CrossDomainMessenger.sol" <<'PY2'
import re, sys

def errors(path):
    out = {}
    for name, params in re.findall(r"error\s+(\w+)\s*\(([^)]*)\)\s*;", open(path).read()):
        out[name] = ",".join(p.split()[0] for p in params.split(",") if p.strip())
    return out

dev, cur = errors(sys.argv[1]), errors(sys.argv[2])
prefix = "L2ToL2CrossDomainMessenger_"
for name, types in sorted(cur.items()):
    base = name[len(prefix):]
    if name.startswith(prefix) and dev.get(base) == types:
        print(f"{name}({types}) {base}({types})")
PY2
)

OUT="$TMP/L2ToL2Bytecodes.sol"
cat >"$OUT" <<EOF
// SPDX-License-Identifier: MIT
pragma solidity 0.8.25;

// GENERATED by gen-bytecodes.sh; do not edit. Runtime bytecode of L2ToL2CrossDomainMessenger built with
// the repo foundry.toml default profile (solc 0.8.25, optimizer 999999 runs, evm cancun, bytecode_hash none).
// Neither messenger has immutables, so both are exactly the code a production deployment runs. The
// current one keeps its expiry period in storage (slot 5), which the harness sets for NEW.
library L2ToL2Bytecodes {
    // develop baseline $DEV_REV, sha256(hex) =
    // $DEV_SHA
    bytes internal constant DEVELOP =
        hex"$DEV_HEX";

    // current checkout (sources at $CUR_REV), sha256(hex) =
    // $CUR_SHA
    bytes internal constant CURRENT =
        hex"$CUR_HEX";

    /// @notice Maps a selector of an error the current messenger renamed with its contract-name
    ///         prefix to develop's selector for the same error; other selectors are unchanged.
    function mapRenamedError(bytes4 _selector) internal pure returns (bytes4 selector_) {
        selector_ = _selector;
${MAP_LINES}    }
}
EOF
printf %s "$DEV_HEX" >"$TMP/develop.runtime.hex"
printf %s "$CUR_HEX" >"$TMP/current.runtime.hex"

if [ "$MODE" = "--check" ]; then
  # Compare the bytecode lines of the .sol (so a different checkout revision label does not fail
  # the check) and both standalone .runtime.hex files (the bytecode-level hevm checks read those).
  stale=0
  diff <(grep -E '^ +hex"|_selector ==' "$OUT") <(grep -E '^ +hex"|_selector ==' "$HERE/L2ToL2Bytecodes.sol") \
    >/dev/null || stale=1
  cmp -s "$TMP/develop.runtime.hex" "$HERE/develop.runtime.hex" || stale=1
  cmp -s "$TMP/current.runtime.hex" "$HERE/current.runtime.hex" || stale=1
  if [ "$stale" = 0 ]; then
    echo "L2ToL2Bytecodes.sol and *.runtime.hex are up to date (develop $DEV_SHA, current $CUR_SHA)"
  else
    echo "L2ToL2Bytecodes.sol or *.runtime.hex is STALE: rerun gen-bytecodes.sh" >&2
    exit 1
  fi
else
  cp "$OUT" "$HERE/L2ToL2Bytecodes.sol"
  cp "$TMP/develop.runtime.hex" "$TMP/current.runtime.hex" "$HERE/"
  echo "wrote L2ToL2Bytecodes.sol, develop.runtime.hex, current.runtime.hex (develop $DEV_SHA, current $CUR_SHA)"
fi
