// SPDX-License-Identifier: MIT
pragma solidity 0.8.25;

// Equivalence harness: develop's L2ToL2CrossDomainMessenger (c2fe2a991b) vs the current one, on the shared surface
// (sendMessage, relayMessage; the shared getters are checked at bytecode level with `hevm equivalence`, see run.sh).
//
// WHAT IS RUN. Both runtime bytecodes, compiled with the repo foundry.toml default profile (L2ToL2Bytecodes.sol,
// generated by gen-bytecodes.sh), are etched at two different addresses, OLD and NEW. Each proof calls both with the
// same symbolic inputs, from the same symbolic pre-state, and asserts:
//   (O) same success/revert, and byte-identical return data or revert data;
//   (X) relay only: same external effects: same calls to the CrossL2Inbox (count + exact arguments), same calls to the
//       target (count + exact calldata), same ETH moved to the target, same ETH left in the messenger; same
//       cross-domain context seen by the target during the call (it calls crossDomainMessageContext() back and
//       returns what it read), same outcome of a reentrant relayMessage attempt from the target, and same context
//       getter result after the call;
//   (S) same storage: for a symbolic key q, the shared state is equal (msgNonce slot 1, successfulMessages[q],
//       sentMessages[q]); the new-only mappings are pinned exactly in NEW (sentMessageTimestamps[q],
//       expiredMessages[q]) and are still zero in OLD. With hevm also (S*): equal at EVERY raw slot s outside the
//       pinned new-only slots.
// Two engines run it: L2ToL2Equivalence_Hevm (prove_*, hevm test) and L2ToL2Equivalence_Halmos (check_*, halmos).
// hevm 0.58 cannot reason about develop's sendMessage once the message is non-empty ("CopySlice with a symbolically
// sized region not currently implemented" inside develop's code; the current code is fine), and its relayMessage run
// exceeds 40 GB of memory even with an empty message, so hevm proves sendMessage with the empty message (with S*),
// and Halmos proves sendMessage and relayMessage for every listed message length.
//
// NOT COMPARED: emitted events. Neither engine can assert on logs (hevm has no recordLogs cheatcode and
// `hevm equivalence` ignores logs, see run.sh's log-blindness witness; halmos 0.3.3 does not implement recordLogs or
// expectEmit). Events are covered by the concrete differential fuzz in L2ToL2EquivalenceLogs.t.sol (forge test).
//
// EXCLUDED (intentional differences, by design of PR #23259):
//   E1  target in {L2CrossDomainMessenger 0x..07, L2ToL1MessagePasser 0x..16}: the new contract reverts on send and
//       relay (MessageTargetUnsafe). Precondition `target not in {0x..07, 0x..16}` in every equivalence proof.
//   E2  sentMessageTimestamps[H]: written by the new sendMessage only. Pinned: NEW holds block.timestamp there after a
//       successful send.
//   E3  The new-only mappings (slot 3 sentMessageTimestamps, slot 4 expiredMessages): the pre-state gives NEW one
//       arbitrary entry in each (sentMessageTimestamps[y] = uy, expiredMessages[z] = uz) to show send/relay do not
//       read them. They are pinned (unchanged, except E2), not compared with OLD (OLD has no such state).
//   E4  Selectors outside the shared surface are not called: resendMessage (removed), expireMessage,
//       sentMessageTimestamps, expiredMessages, EXPIRY_PERIOD (added), version (changed).
//   E5  relayMessage targets are the TargetMock (arbitrary return/revert data, context read-back, reentry attempt)
//       and a codeless address (EOA); other target code is not modelled. In particular a relay whose target is the
//       messenger itself (0x..23) is not modelled (nothing runs at 0x..23 here). There the two DO differ: the
//       self-call dispatches into E4 selectors (e.g. develop's resendMessage succeeds, the new code reverts). Such a
//       relay needs a SentMessage log from 0x..23 with target 0x..23, which neither version emits: sendMessage
//       rejects target 0x..23 in both, and develop's resendMessage only re-emits a stored hash, which commits to the
//       target (keccak collision resistance). So E5's self-target case is unreachable through a valid identifier.
//
// PRE-STATE (identical for OLD and NEW unless stated): all storage zero, then symbolic: slot 1 (the whole msgNonce
// word, all 256 bits free), sentMessages[n0] (n0 = the nonce the send will use), successfulMessages[q0] for a free
// key q0, and for relay successfulMessages[H] (H = the hash the relay computes; any word, so "already relayed" is
// explored with every encoding of true). hevm's proofs instead seed slot 1 and one arbitrary raw slot k := v
// (k free, so it can be any of those mapping entries or any other slot). NEW additionally gets E3. Transient storage
// starts zero (start of a transaction). The CrossL2Inbox mock reverts (with a free 32-byte reason) iff a free flag is
// set: this abstracts validateMessage as an arbitrary predicate of its arguments, which is
// sound because both messengers are shown to call it with identical arguments. The TargetMock returns or reverts
// (free flag) with data built from free words, the context it read back and the result of its reentrant call.
//
// CALLERS: sendMessage is called by a symbolic msg.sender (vm.prank). relayMessage is called by one fixed funded
// account, CALLER: hevm cannot vm.deal a symbolic address, and msg.value needs funds. Neither version of
// relayMessage reads msg.sender (source of both; those lines are unchanged by the PR), so this fixes no behaviour.
//
// BOUNDS: `bytes` message lengths are concrete per proof (one function per length; contents fully symbolic, built
// from four free words, max 128 bytes); everything else is a full 256-bit symbolic value (msg.value < 2^120;
// block.chainid is the engine's concrete default (31337 in halmos); destination and id.chainId are symbolic).
// The code under test has no loops. Solvers: hevm with z3 4.13.3, halmos 0.3.3 with its default (yices).

import { Test } from "forge-std/Test.sol";
import { L2ToL2Bytecodes } from "./L2ToL2Bytecodes.sol";

struct HevmIdentifier {
    address origin;
    uint256 blockNumber;
    uint256 logIndex;
    uint256 timestamp;
    uint256 chainId;
}

interface IHevmMessenger {
    function sendMessage(uint256 _destination, address _target, bytes calldata _message) external returns (bytes32);
    function relayMessage(
        HevmIdentifier calldata _id,
        bytes calldata _sentMessage
    )
        external
        payable
        returns (bytes memory);
    function crossDomainMessageContext() external view returns (address sender_, uint256 source_);
}

/// @notice CrossL2Inbox stand-in. Only validateMessage is callable. Configured with vm.store by the harness:
///         slot 0 = revert flag (nonzero: revert), slot 1 = revert reason word.
///         Records per caller: slot 2 mapping = number of successful calls, slot 3 mapping = hash of the arguments.
contract HevmInboxMock {
    uint256 internal revertFlag;
    bytes32 internal revertWord;
    mapping(address => uint256) internal calls;
    mapping(address => bytes32) internal argsHash;

    function validateMessage(HevmIdentifier calldata _id, bytes32 _msgHash) external {
        if (revertFlag != 0) {
            bytes32 w = revertWord;
            assembly {
                mstore(0, w)
                revert(0, 32)
            }
        }
        calls[msg.sender] += 1;
        argsHash[msg.sender] = keccak256(abi.encode(_id, _msgHash));
    }
}

/// @notice Relay target stand-in. Fallback only (no other selector, so no message can reconfigure it between the
///         two runs). Configured with vm.store: slot 0 = revert flag, slot 1/2 = free return words, slot 3 = reentry
///         flag. Records per caller: slot 4 mapping = number of calls, slot 5 mapping = hash of the calldata.
contract HevmTargetMock {
    uint256 internal revertFlag;
    bytes32 internal w0;
    bytes32 internal w1;
    uint256 internal reenterFlag;
    mapping(address => uint256) internal calls;
    mapping(address => bytes32) internal dataHash;

    fallback(bytes calldata _data) external payable returns (bytes memory) {
        calls[msg.sender] += 1;
        dataHash[msg.sender] = keccak256(_data);

        // Read the cross-domain context back from the calling messenger.
        (bool ctxOk, bytes memory ctxRet) =
            msg.sender.staticcall(abi.encodeCall(IHevmMessenger.crossDomainMessageContext, ()));

        // Optionally try to reenter relayMessage (the reentrancy guard is checked before anything else).
        bool reOk;
        bytes memory reRet;
        if (reenterFlag != 0) {
            HevmIdentifier memory id;
            (reOk, reRet) = msg.sender.call(abi.encodeCall(IHevmMessenger.relayMessage, (id, bytes(""))));
        }

        bytes memory out = abi.encode(w0, w1, ctxOk, ctxRet, reOk, reRet);
        if (revertFlag != 0) {
            assembly {
                revert(add(out, 32), mload(out))
            }
        }
        return out;
    }
}

/// @notice Setup, inputs and checks shared by both engines.
abstract contract L2ToL2EquivalenceBase is Test {
    address internal constant OLD = address(0x0000000000000000000000000000000000010000);
    address internal constant NEW = address(0x0000000000000000000000000000000000020000);
    address internal constant TARGET = address(0x0000000000000000000000000000000000030000);
    address internal constant EOA = address(0x0000000000000000000000000000000000040000);
    address internal constant CALLER = address(uint160(0xCA11E));
    address internal constant L2CDM = 0x4200000000000000000000000000000000000007;
    address internal constant PASSER = 0x4200000000000000000000000000000000000016;
    address internal constant INBOX = 0x4200000000000000000000000000000000000022;
    bytes32 internal constant SENT_MESSAGE_SELECTOR =
        0x382409ac69001e11931a28435afef442cbfd20d9891907e8fa373ba7d351f320;

    function setUp() public {
        vm.etch(OLD, L2ToL2Bytecodes.DEVELOP);
        vm.etch(NEW, L2ToL2Bytecodes.CURRENT);
        vm.etch(INBOX, address(new HevmInboxMock()).code);
        vm.etch(TARGET, address(new HevmTargetMock()).code);
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Inputs
    // ---------------------------------------------------------------------------------------------------------------

    struct SendIn {
        uint256 dest;
        address target;
        address sender;
        uint256 ts;
        bytes32 m0;
        bytes32 m1;
        bytes32 m2;
        bytes32 m3;
    }

    struct RelayIn {
        HevmIdentifier id;
        bytes32 selWord; // free: the wrong-selector revert is explored too
        uint256 dest;
        bytes32 targetWord; // free upper 96 bits (dirty-address revert explored); low 160 bits: TARGET or EOA
        uint256 nonce;
        bytes32 senderWord; // free 256 bits (dirty-address revert explored)
        bytes32 m0;
        bytes32 m1;
        bytes32 m2;
        bytes32 m3;
        uint256 value;
    }

    struct Env {
        uint256 inboxRevert;
        bytes32 inboxRevertWord;
        uint256 targetRevert;
        bytes32 w0;
        bytes32 w1;
        uint256 reenter;
        bytes32 successfulWord; // pre-state successfulMessages[H], both
    }

    struct Pre {
        bytes32 nonceWord; // slot 1 (msgNonce), all 256 bits free
        bytes32 preSent; // sentMessages[n0], n0 = the nonce the send uses
        bytes32 q0; // successfulMessages[q0] = s0
        bytes32 s0;
        bytes32 y; // NEW only: sentMessageTimestamps[y] = uy
        bytes32 uy;
        bytes32 z; // NEW only: expiredMessages[z] = uz
        bytes32 uz;
        bytes32 k; // hevm only: one arbitrary raw slot k := v
        bytes32 v;
    }

    struct Bal {
        uint256 t0;
        uint256 t1;
        uint256 t2;
        uint256 e0;
        uint256 e1;
        uint256 e2;
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Helpers
    // ---------------------------------------------------------------------------------------------------------------

    function _safe(address _target) internal pure returns (bool) {
        return _target != L2CDM && _target != PASSER;
    }

    /// @notice Message of concrete length `_len` (<= 128) with fully symbolic contents.
    function _msg(uint256 _len, bytes32 _a, bytes32 _b, bytes32 _c, bytes32 _d)
        internal
        pure
        returns (bytes memory m_)
    {
        m_ = abi.encodePacked(_a, _b, _c, _d);
        assembly {
            mstore(m_, _len)
        }
    }

    function _mapSlot(bytes32 _key, uint256 _slot) internal pure returns (bytes32) {
        return keccak256(abi.encode(_key, _slot));
    }

    /// @notice The nonce key sendMessage uses: messageNonce() = msgNonce (low 240 bits of slot 1), version 0.
    function _n0(Pre memory _p) internal pure returns (bytes32) {
        return bytes32(uint256(_p.nonceWord) & type(uint240).max);
    }

    function _seed(Pre memory _p) internal {
        vm.store(OLD, bytes32(uint256(1)), _p.nonceWord);
        vm.store(NEW, bytes32(uint256(1)), _p.nonceWord);
        vm.store(OLD, _mapSlot(_n0(_p), 2), _p.preSent);
        vm.store(NEW, _mapSlot(_n0(_p), 2), _p.preSent);
        vm.store(OLD, _mapSlot(_p.q0, 0), _p.s0);
        vm.store(NEW, _mapSlot(_p.q0, 0), _p.s0);
        vm.store(NEW, _mapSlot(_p.y, 3), _p.uy);
        vm.store(NEW, _mapSlot(_p.z, 4), _p.uz);
    }

    /// @notice hevm only (halmos' storage model needs mapping-shaped slots): one arbitrary raw slot, both.
    function _seedRaw(Pre memory _p) internal {
        vm.store(OLD, _p.k, _p.v);
        vm.store(NEW, _p.k, _p.v);
        // Keep E3's NEW-only entries on top, as in a real NEW state.
        vm.store(NEW, _mapSlot(_p.y, 3), _p.uy);
        vm.store(NEW, _mapSlot(_p.z, 4), _p.uz);
    }

    function _configure(Env memory _e) internal {
        vm.store(INBOX, bytes32(uint256(0)), bytes32(_e.inboxRevert));
        vm.store(INBOX, bytes32(uint256(1)), _e.inboxRevertWord);
        vm.store(TARGET, bytes32(uint256(0)), bytes32(_e.targetRevert));
        vm.store(TARGET, bytes32(uint256(1)), _e.w0);
        vm.store(TARGET, bytes32(uint256(2)), _e.w1);
        vm.store(TARGET, bytes32(uint256(3)), bytes32(_e.reenter));
    }

    function _perCaller(address _who, address _caller, uint256 _mappingSlot) internal view returns (bytes32) {
        return vm.load(_who, keccak256(abi.encode(_caller, _mappingSlot)));
    }

    function _targetOk(bytes32 _targetWord) internal pure returns (bool) {
        address t = address(uint160(uint256(_targetWord)));
        return t == TARGET || t == EOA;
    }

    // ---------------------------------------------------------------------------------------------------------------
    // sendMessage
    // ---------------------------------------------------------------------------------------------------------------

    /// @notice Runs sendMessage on both from the seeded state; checks (O) and returns the outcome and the hash.
    function _send(uint256 _len, SendIn memory _in) internal returns (bool ok_, bytes32 h_) {
        vm.warp(_in.ts);
        bytes memory cd = abi.encodeCall(
            IHevmMessenger.sendMessage, (_in.dest, _in.target, _msg(_len, _in.m0, _in.m1, _in.m2, _in.m3))
        );

        vm.prank(_in.sender);
        (bool okO, bytes memory rO) = OLD.call(cd);
        vm.prank(_in.sender);
        (bool okN, bytes memory rN) = NEW.call(cd);

        // (O) Same outcome, same return data / revert data.
        assert(okO == okN);
        assert(keccak256(rO) == keccak256(rN));

        ok_ = okN;
        if (okN) h_ = abi.decode(rN, (bytes32));
    }

    /// @notice (S) after a send, for the symbolic key `_q`.
    function _checkSendMappings(SendIn memory _in, Pre memory _p, bool _ok, bytes32 _h, bytes32 _q) internal view {
        // Shared state equal.
        assert(vm.load(OLD, bytes32(uint256(1))) == vm.load(NEW, bytes32(uint256(1))));
        assert(vm.load(OLD, _mapSlot(_q, 0)) == vm.load(NEW, _mapSlot(_q, 0)));
        assert(vm.load(OLD, _mapSlot(_q, 2)) == vm.load(NEW, _mapSlot(_q, 2)));
        // E2/E3 pinned in NEW; OLD never has state there.
        bytes32 ts = _ok && _q == _h ? bytes32(_in.ts) : (_q == _p.y ? _p.uy : bytes32(0));
        assert(vm.load(NEW, _mapSlot(_q, 3)) == ts);
        assert(vm.load(NEW, _mapSlot(_q, 4)) == (_q == _p.z ? _p.uz : bytes32(0)));
        assert(vm.load(OLD, _mapSlot(_q, 3)) == bytes32(0));
        assert(vm.load(OLD, _mapSlot(_q, 4)) == bytes32(0));
    }

    // ---------------------------------------------------------------------------------------------------------------
    // relayMessage
    // ---------------------------------------------------------------------------------------------------------------

    function _relayCalldata(uint256 _len, RelayIn memory _in, Env memory _e) internal returns (bytes memory) {
        bytes memory m = _msg(_len, _in.m0, _in.m1, _in.m2, _in.m3);
        // Pre-state successfulMessages[H] (H as the relay computes it when decoding succeeds).
        bytes32 h = keccak256(
            abi.encode(
                _in.dest,
                _in.id.chainId,
                _in.nonce,
                address(uint160(uint256(_in.senderWord))),
                address(uint160(uint256(_in.targetWord))),
                m
            )
        );
        vm.store(OLD, _mapSlot(h, 0), _e.successfulWord);
        vm.store(NEW, _mapSlot(h, 0), _e.successfulWord);

        bytes memory payload = abi.encodePacked(
            abi.encode(_in.selWord, _in.dest, _in.targetWord, _in.nonce), abi.encode(_in.senderWord, m)
        );
        return abi.encodeCall(IHevmMessenger.relayMessage, (_in.id, payload));
    }

    /// @notice Runs relayMessage on both from the seeded state; checks (O) and (X).
    function _relay(uint256 _len, RelayIn memory _in, Env memory _e) internal {
        vm.assume(_in.value <= type(uint120).max);
        _configure(_e);
        bytes memory cd = _relayCalldata(_len, _in, _e);

        vm.deal(CALLER, uint256(type(uint120).max) * 2); // halmos caps balances at 2^128
        Bal memory b;
        b.t0 = TARGET.balance;
        b.e0 = EOA.balance;
        vm.prank(CALLER);
        (bool okO, bytes memory rO) = OLD.call{ value: _in.value }(cd);
        b.t1 = TARGET.balance;
        b.e1 = EOA.balance;
        vm.prank(CALLER);
        (bool okN, bytes memory rN) = NEW.call{ value: _in.value }(cd);
        b.t2 = TARGET.balance;
        b.e2 = EOA.balance;

        // (O) Same outcome, same return data / revert data.
        assert(okO == okN);
        assert(keccak256(rO) == keccak256(rN));

        _checkRelayEffects(b);
    }

    /// @notice (X)
    function _checkRelayEffects(Bal memory _b) internal view {
        // Same ETH movements.
        assert(OLD.balance == NEW.balance);
        assert(_b.t1 - _b.t0 == _b.t2 - _b.t1);
        assert(_b.e1 - _b.e0 == _b.e2 - _b.e1);

        // Same calls to the inbox and to the target (count and exact data). The target mock also folded the context
        // it read and its reentry result into its return data, compared under (O).
        assert(_perCaller(INBOX, OLD, 2) == _perCaller(INBOX, NEW, 2));
        assert(_perCaller(INBOX, OLD, 3) == _perCaller(INBOX, NEW, 3));
        assert(_perCaller(TARGET, OLD, 4) == _perCaller(TARGET, NEW, 4));
        assert(_perCaller(TARGET, OLD, 5) == _perCaller(TARGET, NEW, 5));

        // Same transient context after the call (both should be back to "not entered").
        (bool cO, bytes memory xO) = OLD.staticcall(abi.encodeCall(IHevmMessenger.crossDomainMessageContext, ()));
        (bool cN, bytes memory xN) = NEW.staticcall(abi.encodeCall(IHevmMessenger.crossDomainMessageContext, ()));
        assert(cO == cN);
        assert(keccak256(xO) == keccak256(xN));
    }

    /// @notice (S) after a relay, for the symbolic key `_q`: no E2 write at all.
    function _checkRelayMappings(Pre memory _p, bytes32 _q) internal view {
        assert(vm.load(OLD, bytes32(uint256(1))) == vm.load(NEW, bytes32(uint256(1))));
        assert(vm.load(OLD, _mapSlot(_q, 0)) == vm.load(NEW, _mapSlot(_q, 0)));
        assert(vm.load(OLD, _mapSlot(_q, 2)) == vm.load(NEW, _mapSlot(_q, 2)));
        assert(vm.load(NEW, _mapSlot(_q, 3)) == (_q == _p.y ? _p.uy : bytes32(0)));
        assert(vm.load(NEW, _mapSlot(_q, 4)) == (_q == _p.z ? _p.uz : bytes32(0)));
        assert(vm.load(OLD, _mapSlot(_q, 3)) == bytes32(0));
        assert(vm.load(OLD, _mapSlot(_q, 4)) == bytes32(0));
    }

    /// @notice Relay that must reach TargetMock and succeed; returns whether it did and saw the right context.
    function _relaySeesContext(uint256 _len, RelayIn memory _in, Env memory _e) internal returns (bool) {
        _configure(_e);
        bytes memory cd = _relayCalldata(_len, _in, _e);
        (bool ok, bytes memory ret) = NEW.call(cd);
        if (!ok) return false;
        bytes memory inner = abi.decode(ret, (bytes));
        (,, bool ctxOk, bytes memory ctxRet,,) = abi.decode(inner, (bytes32, bytes32, bool, bytes, bool, bytes));
        if (!ctxOk) return false;
        (address s, uint256 src) = abi.decode(ctxRet, (address, uint256));
        return s == address(uint160(uint256(_in.senderWord))) && src == _in.id.chainId;
    }
}

/// @notice hevm engine (hevm test, prove_*). sendMessage with the empty message only (see header); adds (S*).
contract L2ToL2Equivalence_Hevm is L2ToL2EquivalenceBase {
    /// @notice (S*) every raw slot `_s` is equal, except the pinned new-only slots.
    function _checkAllSlots(Pre memory _p, bool _ok, bytes32 _h, bytes32 _s) internal pure returns (bool) {
        return !(_s == _mapSlot(_p.y, 3) || _s == _mapSlot(_p.z, 4) || (_ok && _s == _mapSlot(_h, 3)));
    }

    /// @notice hevm's pre-state: the msgNonce word and one arbitrary raw slot (both), plus E3 in NEW. (hevm runs out
    ///         of memory with the mapping-shaped seeds of _seed on top.)
    function _seedHevm(Pre memory _p) internal {
        vm.store(OLD, bytes32(uint256(1)), _p.nonceWord);
        vm.store(NEW, bytes32(uint256(1)), _p.nonceWord);
        _seedRaw(_p);
    }

    /// @notice (O) and (S*) from _seedHevm's pre-state (k is free, so it covers any one mapping entry being set).
    function prove_sendMessage_len0(SendIn memory _in, Pre memory _p, bytes32 _s) public {
        vm.assume(_safe(_in.target));
        _seedHevm(_p);
        (bool ok, bytes32 h) = _send(0, _in);
        // (S*) every raw slot outside the pinned new-only slots is equal ...
        if (_checkAllSlots(_p, ok, h, _s)) assert(vm.load(OLD, _s) == vm.load(NEW, _s));
        // ... and the pins: E3's entries unchanged, E2 written.
        assert(vm.load(NEW, _mapSlot(_p.z, 4)) == _p.uz);
        if (ok) assert(vm.load(NEW, _mapSlot(h, 3)) == bytes32(_in.ts));
        if (!(ok && _p.y == h)) assert(vm.load(NEW, _mapSlot(_p.y, 3)) == _p.uy);
    }

    // Non-vacuity: EXPECTED TO FAIL (hevm must print a counterexample). run.sh checks that.

    /// @notice E1 is real: without the precondition, an unsafe target separates the two.
    function prove_nonvacuity_sendMessage_unsafeTarget(SendIn memory _in, Pre memory _p) public {
        vm.assume(!_safe(_in.target));
        _seedHevm(_p);
        _send(0, _in);
    }

    /// @notice E2 is real: OLD does not hold the timestamp NEW writes.
    function prove_nonvacuity_sendMessage_timestampSlot(SendIn memory _in, Pre memory _p) public {
        vm.assume(_safe(_in.target));
        _seedHevm(_p);
        (bool ok, bytes32 h) = _send(0, _in);
        if (ok) assert(vm.load(OLD, _mapSlot(h, 3)) == vm.load(NEW, _mapSlot(h, 3)));
    }

    /// @notice Reachability witness: a successful send is explored.
    function prove_nonvacuity_sendMessage_successReachable(SendIn memory _in, Pre memory _p) public {
        vm.assume(_safe(_in.target));
        _seedHevm(_p);
        (bool ok,) = _send(0, _in);
        assert(!ok);
    }
}

/// @notice Halmos engine (halmos, check_*), every listed message length.
contract L2ToL2Equivalence_Halmos is L2ToL2EquivalenceBase {
    function _sendCheck(uint256 _len, SendIn memory _in, Pre memory _p, bytes32 _q) internal {
        vm.assume(_safe(_in.target));
        _seed(_p);
        (bool ok, bytes32 h) = _send(_len, _in);
        _checkSendMappings(_in, _p, ok, h, _q);
    }

    function check_sendMessage_len0(SendIn memory _in, Pre memory _p, bytes32 _q) public {
        _sendCheck(0, _in, _p, _q);
    }

    function check_sendMessage_len4(SendIn memory _in, Pre memory _p, bytes32 _q) public {
        _sendCheck(4, _in, _p, _q);
    }

    function check_sendMessage_len37(SendIn memory _in, Pre memory _p, bytes32 _q) public {
        _sendCheck(37, _in, _p, _q);
    }

    function check_sendMessage_len100(SendIn memory _in, Pre memory _p, bytes32 _q) public {
        _sendCheck(100, _in, _p, _q);
    }

    function check_sendMessage_len128(SendIn memory _in, Pre memory _p, bytes32 _q) public {
        _sendCheck(128, _in, _p, _q);
    }

    function _relayCheck(uint256 _len, RelayIn memory _in, Env memory _e, Pre memory _p, bytes32 _q) internal {
        vm.assume(_targetOk(_in.targetWord));
        _seed(_p);
        _relay(_len, _in, _e);
        _checkRelayMappings(_p, _q);
    }

    function check_relayMessage_len0(RelayIn memory _in, Env memory _e, Pre memory _p, bytes32 _q) public {
        _relayCheck(0, _in, _e, _p, _q);
    }

    function check_relayMessage_len4(RelayIn memory _in, Env memory _e, Pre memory _p, bytes32 _q) public {
        _relayCheck(4, _in, _e, _p, _q);
    }

    function check_relayMessage_len37(RelayIn memory _in, Env memory _e, Pre memory _p, bytes32 _q) public {
        _relayCheck(37, _in, _e, _p, _q);
    }

    function check_relayMessage_len100(RelayIn memory _in, Env memory _e, Pre memory _p, bytes32 _q) public {
        _relayCheck(100, _in, _e, _p, _q);
    }

    // Non-vacuity: EXPECTED TO FAIL (halmos must print a counterexample). run.sh checks that.

    /// @notice E1 is real for send.
    function check_nonvacuity_sendMessage_unsafeTarget(SendIn memory _in, Pre memory _p) public {
        vm.assume(!_safe(_in.target));
        _seed(_p);
        _send(37, _in);
    }

    /// @notice E2 is real: OLD does not hold the timestamp NEW writes.
    function check_nonvacuity_sendMessage_timestampSlot(SendIn memory _in, Pre memory _p) public {
        vm.assume(_safe(_in.target));
        _seed(_p);
        (bool ok, bytes32 h) = _send(37, _in);
        if (ok) assert(vm.load(OLD, _mapSlot(h, 3)) == vm.load(NEW, _mapSlot(h, 3)));
    }

    /// @notice Reachability witness: a successful send is explored.
    function check_nonvacuity_sendMessage_successReachable(SendIn memory _in, Pre memory _p) public {
        vm.assume(_safe(_in.target));
        _seed(_p);
        (bool ok,) = _send(37, _in);
        assert(!ok);
    }

    /// @notice E1 is real for relay: TargetMock vs an unsafe target (no code here, so OLD succeeds, NEW reverts).
    function check_nonvacuity_relayMessage_unsafeTarget(RelayIn memory _in, Env memory _e, Pre memory _p) public {
        address t = address(uint160(uint256(_in.targetWord)));
        vm.assume(t == TARGET || !_safe(t));
        _seed(_p);
        _relay(37, _in, _e);
    }

    /// @notice Reachability witness: a relay reaches TargetMock, which sees the right context, and succeeds.
    function check_nonvacuity_relayMessage_successReachable(RelayIn memory _in, Env memory _e, Pre memory _p) public {
        vm.assume(address(uint160(uint256(_in.targetWord))) == TARGET);
        _seed(_p);
        assert(!_relaySeesContext(37, _in, _e));
    }
}
