name: tag build

on:
  push:
    tags:
      - 'autorelayer-interop/v*'
      - 'ponder-interop/v*'
      - 'sponsored-sender/v*'

jobs:
  prep:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      image_name: ${{ steps.parse-tag.outputs.image_name }}
      version: ${{ steps.parse-tag.outputs.version }}
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e # v6
        with:
          fetch-depth: 0
      - name: Parse tag
        uses: ethereum-optimism/factory/actions/parse-tag@fdcd6acceb0cbad90040e0be9f59a1ad60e65a86
        id: parse-tag

  release:
    needs: prep
    uses: ethereum-optimism/factory/.github/workflows/docker.yaml@fdcd6acceb0cbad90040e0be9f59a1ad60e65a86
    with:
      mode: bake
      image_name: ${{ needs.prep.outputs.image_name }}
      bake_file: docker-bake.hcl
      target: ${{ needs.prep.outputs.image_name }}
      tag: ${{ needs.prep.outputs.version }}
      gcp_project_id: ${{ vars.GCP_PROJECT_ID_OPLABS_TOOLS_ARTIFACTS }}
      registry: us-docker.pkg.dev/oplabs-tools-artifacts/internal-images
      set: |
        *.args.GIT_COMMIT=${{ github.sha }}
    permissions:
      contents: read
      id-token: write
      attestations: write
