
data:
	eth2-val-tools keystores --source-min=0 --source-max=64 \
		--source-mnemonic="test test test test test test test test test test test junk" --out-loc=data && \
		rm -rf data/lodestar-secrets data/nimbus-keys data/prysm data/teku-keys data/teku-secrets


