name: Dependency Review

on: pull_request

jobs:
  dependency-review:
    uses: ethereum-optimism/factory/.github/workflows/dependency-review.yaml@0a5a01da201169813de992b8c2dac6e7999f5d51
    permissions:
      contents: read
      pull-requests: write
