name: Proof Runner Deployment Status
on:
  status
jobs:
  handle-proof-runner:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Slack Payload
      run: |
        echo '{"Check Status": "${{ github.event.state }}"}' > payload.json

    - name: Send Status Check to Slack
      uses: slackapi/slack-github-action@v1.26.0
      with:
        payload-file-path: "./payload.json"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
