name: OpenSSF Scorecard

on:
  push:
    branches:
      - add-scorecard-workflow

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Run Scorecard
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget -qO- https://github.com/ossf/scorecard/releases/download/v5.1.1/scorecard_5.1.1_linux_amd64.tar.gz | tar xz
          ./scorecard --repo=github.com/ethereum-optimism/optimism --format=json | tee scorecard.json
          echo "---"
          ./scorecard --repo=github.com/ethereum-optimism/optimism

      - name: Upload results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: scorecard-results
          path: scorecard.json
