name: tag build

on:
  push:
    tags:
      - '*/v*' # Match tags like op-node/v1.2.3

jobs:
  prep:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      image_name: ${{ steps.parse-tag.outputs.image_name }}
      version: ${{ steps.parse-tag.outputs.version }}
      versions: ${{ steps.prep.outputs.versions }}
      kona_version: ${{ steps.prep.outputs.kona_version }}
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e # v6
        with:
          fetch-depth: 0
      - uses: ./.github/actions/docker-build-prep
        id: prep
      - name: Parse tag
        uses: ethereum-optimism/factory/actions/parse-tag@240b16167a5f5aa789270fa9c0efbfa9f010b7e7
        id: parse-tag

  release:
    needs: prep
    uses: ethereum-optimism/factory/.github/workflows/docker.yaml@d04222c229c50320f513afe678b3264869ea11a9
    with:
      mode: bake
      image_name: ${{ needs.prep.outputs.image_name }}
      bake_file: docker-bake.hcl
      target: ${{ needs.prep.outputs.image_name }}
      tag: ${{ needs.prep.outputs.version }}
      gcp_project_id: ${{ vars.GCP_PROJECT_ID_OPLABS_TOOLS_ARTIFACTS }}
      registry: us-docker.pkg.dev/oplabs-tools-artifacts/oss
      env: |
        GIT_VERSION=${{ fromJson(needs.prep.outputs.versions)[needs.prep.outputs.image_name] }}
        KONA_VERSION=${{ needs.prep.outputs.kona_version }}
      set: |
        *.args.GIT_COMMIT=${{ github.sha }}
        *.args.GIT_DATE=${{ github.event.head_commit.timestamp }}
    permissions:
      contents: read
      id-token: write
      attestations: write
