FROM ethereumoptimism/builder:latest
RUN apt-get update && apt-get install -y bash git python build-essential

WORKDIR /optimism
RUN yarn
RUN yarn build
COPY packages/omgx/wallet/package.json ./packages/omgx/wallet/package.json
COPY ./packages/omgx ./packages/omgx

COPY ./patches ./patches
RUN yarn

WORKDIR /optimism/packages/omgx/wallet
RUN yarn build

CMD ["true"]
