FROM golang:1.16 as builder

COPY ./go/op-exporter /app/
WORKDIR /app/
RUN make build

FROM alpine:3.13
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/op-exporter /usr/local/bin/
ENTRYPOINT ["op-exporter"]
CMD ["--help"]
