FROM ethereumoptimism/builder:latest

WORKDIR /optimism
COPY packages/omgx/contracts/package.json ./packages/omgx/contracts/package.json
COPY packages/omgx/message-relayer-fast/package.json ./packages/omgx/message-relayer-fast/package.json
COPY ./packages/omgx ./packages/omgx

COPY ./patches ./patches

RUN yarn

WORKDIR /optimism/packages/omgx/message-relayer-fast
RUN yarn build

WORKDIR /optimism/packages/omgx/contracts
RUN yarn build

CMD ["true"]
